"use strict";

/**
 * The checks the hooks under this directory apply, kept free of I/O so a unit
 * test can state each rule; the guards read stdin and decide the exit code.
 * Every rule here enforces a line of AGENTS.md — the message names which.
 */

/** @typedef {{ userEmail?: string }} CommandContext */
/** @typedef {{ exists: boolean }} EditContext */

/** A command token boundary: start, or a shell separator before the word */
const AT_WORD = String.raw`(?:^|[\s;&|(])`;

const JEST_REGEXP = new RegExp(
	`${AT_WORD}(?:(?:yarn|npx|pnpm)\\s+jest\\b|node_modules[\\\\/]\\.bin[\\\\/]jest\\b|node_modules[\\\\/]jest(?:-cli)?[\\\\/]bin[\\\\/]jest)`
);

const NPM_REGEXP = new RegExp(
	`${AT_WORD}npm\\s+(?:install|i|ci|add|uninstall|remove|rm|un|update|up|run|run-script|test|t|exec|x|link|publish|start)\\b`
);

const FULL_TEST_REGEXP = new RegExp(
	`${AT_WORD}yarn\\s+(?:run\\s+)?test(?=$|[\\s;&|)])`
);

const CI_ONLY_SUITE_REGEXP = new RegExp(
	`${AT_WORD}yarn\\s+(?:run\\s+)?(?:test|cover):(?:test262|html5lib|css-parsing|integration(?::[ab])?|syntax-equivalence|minify-corpora)\\b`
);

const PIPED_TEST_REGEXP = new RegExp(
	`${AT_WORD}yarn\\s+(?:run\\s+)?(?:test|cover)[\\w:-]*[^|\\n]*\\|\\s*(?:grep|rg|tail|head|wc)\\b`
);

const GENERATED_IN_COMMAND = String.raw`\S*(?:types\.d\.ts|\.check\.js|\.check\.d\.ts|schemas[\\/]\S+\.json|lib[\\/](?:css|html|javascript)[\\/]data\.js|syntax-printer-data\.js|internalSerializables\.js)\b`;

const WRITES_GENERATED_REGEXP = new RegExp(
	`(?:\\b(?:sed|perl)\\s+-[\\w-]*i[\\w-]*\\s+[^;&|]*|\\btee\\s+(?:-a\\s+)?|>>?\\s*)(${GENERATED_IN_COMMAND})`
);

const MERGE_MAIN_REGEXP =
	/\bgit\s+merge\s+(?:[^;&|]*\s)?(?:origin\/)?main\b|\bgit\s+pull\b(?![^;&|]*--rebase)[^;&|]*\bmain\b/;

const CO_AUTHORED_REGEXP = /\bgit\s+commit\b[^]*co-authored-by/i;

const AUTHORING_GIT_REGEXP =
	/\bgit\s+(?:-[cC]\s+\S+\s+|--?\S+\s+)*(?:commit|rebase|cherry-pick|am|revert)\b/;

const BOT_EMAIL_REGEXP = /anthropic\.com$|\[bot\]|^noreply@|bot@/i;

/**
 * @param {string} command the shell command Claude Code is about to run
 * @param {CommandContext} context what the guard read from the environment
 * @returns {string | undefined} why AGENTS.md forbids it, or nothing when allowed
 */
const checkCommand = (command, context = {}) => {
	if (JEST_REGEXP.test(command)) {
		return 'Blocked by AGENTS.md: never run jest directly, the ESM and test262 suites need `--experimental-vm-modules`. Use `yarn test:base --testPathPatterns="<pattern>"` or `yarn test:basic --testNamePattern="<case>"`.';
	}
	if (NPM_REGEXP.test(command)) {
		return "Blocked by AGENTS.md: use yarn, not npm. Every command is a `package.json` script (`yarn <script>`).";
	}
	if (FULL_TEST_REGEXP.test(command)) {
		return 'Blocked by AGENTS.md: `yarn test` runs the full suite, which only CI sweeps. Run the touched cases: `yarn test:base --testPathPatterns="<pattern>"`.';
	}
	if (CI_ONLY_SUITE_REGEXP.test(command)) {
		return "Blocked by AGENTS.md: the spec-conformance suites and the integration matrix run only in CI (tens of minutes, and a busy machine manufactures timeouts). Run the `configCases/` relevant to the change instead.";
	}
	if (PIPED_TEST_REGEXP.test(command)) {
		return "Blocked by AGENTS.md: never read pass/fail through a pipe, it discards jest's exit code. Run the command plain and read the `Tests:` line, or narrow the pattern until the output is short.";
	}
	const writesGenerated = WRITES_GENERATED_REGEXP.exec(command);
	if (writesGenerated) {
		return `Blocked by AGENTS.md: ${writesGenerated[1]} is generated by \`yarn fix:special\`. Edit the JSDoc, declaration or generator it derives from, then regenerate.`;
	}
	if (MERGE_MAIN_REGEXP.test(command)) {
		return "Blocked by docs/pull-requests.md: never merge `main` into a branch (the merge commit takes the committer's identity and fails the CLA check). Rebase: `git -c user.name=<login> -c user.email=<email> rebase origin/main`.";
	}
	if (CO_AUTHORED_REGEXP.test(command)) {
		return "Blocked by docs/pull-requests.md: no `Co-authored-by` trailers, the requester is the only author. Disclose AI use in the PR body's **Use of AI** section instead.";
	}
	if (
		AUTHORING_GIT_REGEXP.test(command) &&
		!/user\.email=|GIT_AUTHOR_EMAIL=/.test(command) &&
		context.userEmail &&
		BOT_EMAIL_REGEXP.test(context.userEmail)
	) {
		return `Blocked by docs/pull-requests.md: git's configured author is a bot (${context.userEmail}), which fails the CLA check. Pass the requester's identity: \`git -c user.name=<login> -c user.email=<id>+<login>@users.noreply.github.com ${command.replace(/^.*?\bgit\s+/, "")}\`.`;
	}
	return undefined;
};

const GENERATED_FILE_REGEXP =
	/^(?:types\.d\.ts|schemas\/.*\.(?:json|check\.js|check\.d\.ts)|lib\/(?:css|html|javascript)\/data\.js|lib\/javascript\/syntax-printer-data\.js|lib\/util\/internalSerializables\.js)$/;

const LIB_MARKDOWN_REGEXP = /^lib\/.*\.md$/;

const LIB_ROOT_PLUGIN_REGEXP = /^lib\/[^/]*Plugin\.js$/;

/**
 * @param {string} relativePath the edited file, relative to the repo root with `/` separators
 * @param {EditContext} context what the guard read from the filesystem
 * @returns {string | undefined} why AGENTS.md forbids the edit, or nothing when allowed
 */
const checkEdit = (relativePath, context) => {
	if (GENERATED_FILE_REGEXP.test(relativePath)) {
		return `Blocked by AGENTS.md: ${relativePath} is generated by \`yarn fix:special\`. Edit what it derives from (a JSDoc typedef in lib/, declarations/WebpackOptions.ts, or the generator in tooling/) and regenerate; never hand-write what the generator would emit.`;
	}
	if (LIB_MARKDOWN_REGEXP.test(relativePath)) {
		return "Blocked by AGENTS.md: documentation lives in docs/, never under lib/, which is published.";
	}
	if (LIB_ROOT_PLUGIN_REGEXP.test(relativePath) && !context.exists) {
		return "Blocked by AGENTS.md: a plugin never belongs in lib/ root. Put it in the directory for what it acts on (see docs/architecture.md), adding a directory and its bullet when none fits.";
	}
	return undefined;
};

/**
 * Picks the edited files the Stop hook should lint: inside the repo, still
 * present, and named once.
 * @param {string[]} relativePaths every recorded edit, relative to the repo root
 * @param {(relativePath: string) => boolean} exists whether a path is still a file
 * @returns {string[]} the paths to check, in first-edit order
 */
const selectEditedFiles = (relativePaths, exists) => {
	const seen = new Set();
	const selected = [];
	for (const relativePath of relativePaths) {
		if (
			relativePath === "" ||
			relativePath.startsWith("../") ||
			relativePath === ".." ||
			seen.has(relativePath) ||
			!exists(relativePath)
		) {
			continue;
		}
		seen.add(relativePath);
		selected.push(relativePath);
	}
	return selected;
};

/**
 * @param {string[]} relativePaths the edited files
 * @returns {boolean} whether `types.d.ts` may have gone stale
 */
const touchesDeclaredTypes = (relativePaths) =>
	relativePaths.some(
		(relativePath) =>
			/^lib\/.*\.js$/.test(relativePath) ||
			relativePath.startsWith("declarations/")
	);

module.exports = {
	checkCommand,
	checkEdit,
	selectEditedFiles,
	touchesDeclaredTypes
};
