codecov:
  branch: main
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: off
      basic:
        flags: basic
        target: auto
      types:
        flags: types
        target: auto
      unit:
        flags: unit
        target: auto
      integration:
        flags: integration
        target: auto
    patch:
      default: off
      types:
        flags: types
        target: 90%
        base: pr
      unit:
        flags: unit
        target: 90%
        base: pr
      basic:
        flags: basic
        target: 90%
        base: pr
      integration:
        flags: integration
        target: 90%
        base: pr
    changes:
      default: off
      types:
        flags: types
        target: 0%
      basic:
        flags: basic
        target: 0%
      unit:
        flags: unit
        target: 0%
      integration:
        flags: integration
        target: 0%
comment: off
flags:
  basic:
    joined: false
  types:
    joined: false
