codecov:
  branch: main

flags:
  tests:
    carryforward: true
  types:
    carryforward: true

components:
  - identifier: tests
    name: Tests Coverage
    flag: tests

  - identifier: types
    name: Type Coverage
    flag: types

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: false

      tests:
        flags:
          - tests
        target: auto

      types:
        flags:
          - types
        target: auto

    patch:
      default: false

      tests:
        flags:
          - tests
        target: 90%
        base: pr

      types:
        target: 90%
        base: pr
        flags:
          - types

    changes:
      default: false

      tests:
        flags:
          - tests

      types:
        flags:
          - types

ignore:
  - "**/*.runtime.js"
  - "schemas/**/*"
  - "examples/**/*"
  # TODO webpack 6 remove
  - "lib/ChunkTemplate.js"
  - "lib/MainTemplate.js"
  - "lib/ModuleTemplate.js"

comment: off
