module.exports = [
	{ code: /DEP_WEBPACK_RULE_LOADER_OPTIONS_STRING/ },
	{ code: /DEP_WEBPACK_RULE_LOADER_OPTIONS_STRING/ },
	{ code: /DEP_WEBPACK_RULE_LOADER_OPTIONS_STRING/ },
	{ code: /DEP_WEBPACK_RULE_LOADER_OPTIONS_STRING/ },
	{ code: /DEP_WEBPACK_RULE_LOADER_OPTIONS_STRING/ },
	{ code: /DEP_WEBPACK_RULE_LOADER_OPTIONS_STRING/ },
	{ code: /DEP_WEBPACK_RULE_LOADER_OPTIONS_STRING/ }
];
