"use strict";

// Generated against the parser behavior: character references in attribute
// values are decoded before srcset parsing (entity-encoded ASCII whitespace
// separates candidates, like in browsers), so parse-error messages and
// unresolvable URLs below contain the decoded characters, while rewrite
// spans still map back to the raw source text.
module.exports = [
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'image\.png 480w 2x broken' at 'broken'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'image\.png broken' at 'broken'/,
	/Bad value for attribute "srcset" on element "img": Must contain one or more image candidate strings/,
	/Bad value for attribute "srcset" on element "img": Must contain one or more image candidate strings/,
	/Bad value for attribute "srcset" on element "img": Must contain one or more image candidate strings/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'image\.png 0h, image\.png 800w' at '0h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in ',a foo' at 'foo'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'a \(,' at '\(,'/,
	/Bad value for attribute "srcset" on element "img": Must contain one or more image candidate strings/,
	/Bad value for attribute "srcset" on element "img": Must contain one or more image candidate strings/,
	/Module not found: Error: Can't resolve '\u000B\u000Bdata:,a\u000B\u000B1x\u000B\u000B'/,
	/Module not found: Error: Can't resolve '\u000E\u000Edata:,a\u000E\u000E1x\u000E\u000E'/,
	/Module not found: Error: Can't resolve '\u000F\u000Fdata:,a\u000F\u000F1x\u000F\u000F'/,
	/Module not found: Error: Can't resolve '\u0010\u0010data:,a\u0010\u00101x\u0010\u0010'/,
	/Module not found: Error: Can't resolve '\u00A0data:,a'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \( , data:,b 1x, \), data:,c' at '\( , data:,b 1x, \)'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \(\(\( , data:,b 1x, \), data:,c' at '\(\(\( , data:,b 1x, \)'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \[ , data:,b 1x, \], data:,c' at '\['/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \{ , data:,b 1x, \}, data:,c' at '\{'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a, data:,b \(' at '\('/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a, data:,b \( {2}' at '\( {2}'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a, data:,b \(,' at '\(,'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a, data:,b \(x' at '\(x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a, data:,b \(\)' at '\(\)'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \(, data:,b' at '\(, data:,b'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \/\*, data:,b, data:,c \*\/' at '\/\*'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \/\/, data:,b' at '\/\/'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a foo' at 'foo'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a foo foo' at 'foo'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a foo 1x' at '1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a foo 1x foo' at 'foo'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a foo 1w' at '1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a foo 1w foo' at 'foo'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1x 1x' at '1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1w' at '1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1h 1h' at '1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1x' at '1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1x 1w' at '1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1h 1x' at '1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1h 1w 1x' at '1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1x 1w 1h' at '1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1h foo' at 'foo'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a foo 1h' at '1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 0w' at '0w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a -1w' at '-1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w -1w' at '-1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\.0w' at '1\.0w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\.0w' at '1\.0w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1e0w' at '1e0w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1e0w' at '1e0w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1www' at '1www'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1www' at '1www'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \+1w' at '\+1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1W' at '1W'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1W' at '1W'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a Infinityw' at 'Infinityw'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w Infinityw' at 'Infinityw'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a NaNw' at 'NaNw'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w NaNw' at 'NaNw'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 0x1w' at '0x1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u0001w' at '1\u0001w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u00A0w' at '1\u00A0w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u1680w' at '1\u1680w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2000w' at '1\u2000w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2001w' at '1\u2001w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2002w' at '1\u2002w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2003w' at '1\u2003w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2004w' at '1\u2004w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2005w' at '1\u2005w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2006w' at '1\u2006w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2007w' at '1\u2007w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2008w' at '1\u2008w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2009w' at '1\u2009w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u200Aw' at '1\u200Aw'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u200Cw' at '1\u200Cw'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u200Dw' at '1\u200Dw'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u202Fw' at '1\u202Fw'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u205Fw' at '1\u205Fw'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u3000w' at '1\u3000w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\uFEFFw' at '1\uFEFFw'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u00011w' at '\u00011w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u00A01w' at '\u00A01w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u16801w' at '\u16801w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20001w' at '\u20001w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20011w' at '\u20011w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20021w' at '\u20021w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20031w' at '\u20031w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20041w' at '\u20041w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20051w' at '\u20051w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20061w' at '\u20061w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20071w' at '\u20071w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20081w' at '\u20081w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20091w' at '\u20091w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u200A1w' at '\u200A1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u200C1w' at '\u200C1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u200D1w' at '\u200D1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u202F1w' at '\u202F1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u205F1w' at '\u205F1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u30001w' at '\u30001w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \uFEFF1w' at '\uFEFF1w'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1x -0x' at '-0x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a -1x' at '-1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1x -1x' at '-1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a -x' at '-x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \.x' at '\.x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a -\.x' at '-\.x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\.x' at '1\.x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1x 1\.5e1x' at '1\.5e1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1x 1e1\.5x' at '1e1\.5x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1x 1\.0x' at '1\.0x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \+1x' at '\+1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1X' at '1X'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a Infinityx' at 'Infinityx'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a NaNx' at 'NaNx'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 0x1x' at '0x1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 0X1x' at '0X1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u0001x' at '1\u0001x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u00A0x' at '1\u00A0x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u1680x' at '1\u1680x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2000x' at '1\u2000x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2001x' at '1\u2001x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2002x' at '1\u2002x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2003x' at '1\u2003x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2004x' at '1\u2004x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2005x' at '1\u2005x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2006x' at '1\u2006x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2007x' at '1\u2007x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2008x' at '1\u2008x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u2009x' at '1\u2009x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u200Ax' at '1\u200Ax'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u200Cx' at '1\u200Cx'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u200Dx' at '1\u200Dx'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u202Fx' at '1\u202Fx'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u205Fx' at '1\u205Fx'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\u3000x' at '1\u3000x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1\uFEFFx' at '1\uFEFFx'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u00011x' at '\u00011x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u00A01x' at '\u00A01x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u16801x' at '\u16801x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20001x' at '\u20001x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20011x' at '\u20011x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20021x' at '\u20021x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20031x' at '\u20031x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20041x' at '\u20041x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20051x' at '\u20051x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20061x' at '\u20061x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20071x' at '\u20071x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20081x' at '\u20081x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u20091x' at '\u20091x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u200A1x' at '\u200A1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u200C1x' at '\u200C1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u200D1x' at '\u200D1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u202F1x' at '\u202F1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u205F1x' at '\u205F1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \u30001x' at '\u30001x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a \uFEFF1x' at '\uFEFF1x'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 0h' at '0h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w -1h' at '-1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\.0h' at '1\.0h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1e0h' at '1e0h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1hhh' at '1hhh'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1H' at '1H'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w Infinityh' at 'Infinityh'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w NaNh' at 'NaNh'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 0x1h' at '0x1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 0X1h' at '0X1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u0001h' at '1\u0001h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u00A0h' at '1\u00A0h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u1680h' at '1\u1680h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u2000h' at '1\u2000h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u2001h' at '1\u2001h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u2002h' at '1\u2002h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u2003h' at '1\u2003h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u2004h' at '1\u2004h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u2005h' at '1\u2005h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u2006h' at '1\u2006h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u2007h' at '1\u2007h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u2008h' at '1\u2008h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u2009h' at '1\u2009h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u200Ah' at '1\u200Ah'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u200Ch' at '1\u200Ch'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u200Dh' at '1\u200Dh'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u202Fh' at '1\u202Fh'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u205Fh' at '1\u205Fh'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\u3000h' at '1\u3000h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w 1\uFEFFh' at '1\uFEFFh'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u00011h' at '\u00011h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u00A01h' at '\u00A01h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u16801h' at '\u16801h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u20001h' at '\u20001h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u20011h' at '\u20011h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u20021h' at '\u20021h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u20031h' at '\u20031h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u20041h' at '\u20041h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u20051h' at '\u20051h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u20061h' at '\u20061h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u20071h' at '\u20071h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u20081h' at '\u20081h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u20091h' at '\u20091h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u200A1h' at '\u200A1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u200C1h' at '\u200C1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u200D1h' at '\u200D1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u202F1h' at '\u202F1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u205F1h' at '\u205F1h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \u30001h' at '\u30001h'/,
	/Bad value for attribute "srcset" on element "img": Invalid srcset descriptor found in 'data:,a 1w \uFEFF1h' at '\uFEFF1h'/,
	/Bad value for attribute "srcset" on element "img": Must contain one or more image candidate strings/,
	/Bad value for attribute "srcset" on element "img": Must contain one or more image candidate strings/
];
