// usually this is generated by typescript `enum common { C }`
var common = /* @__PURE__ */ ((common) => {
  common[common["C"] = 1] = "C";
  return common;
})(common || {}); // the `{}` (inside `common || {}`) has side effect
export { common }
