import { jsx as _jsx } from "react/jsx-runtime";
// Generated by Framer (7e38f14)
import * as React from "react";
import { motion, addPropertyControls, cx, useVariantState, useAddVariantProps, withCSS, LayoutGroup, ControlType, addFonts, Text as Text1, Stack } from "framer";
import { useRandomID } from "https://framer.com/m/framer/randomID.js@^1.0.0";
const enabledGestures = {
    "JdUDMq_5J": {
        "hover": true,
        "pressed": true
    },
    "yM6MP0SOJ": {
        "hover": true,
        "pressed": true
    }
};
const cycleOrder = [
    "JdUDMq_5J",
    "yM6MP0SOJ"
];
const variantClassNames = {
    "JdUDMq_5J": "framer-v-7gtv3v",
    "yM6MP0SOJ": "framer-v-1rf6xal"
};
const humanReadableVariantMap = {
    "Large": "JdUDMq_5J",
    "Small": "yM6MP0SOJ"
};
const transitions = {
    "default": {
        "type": "spring",
        "ease": [
            0.44,
            0,
            0.56,
            1
        ],
        "duration": 0.3,
        "delay": 0,
        "stiffness": 500,
        "damping": 60,
        "mass": 1
    }
};
const Component = /*#__PURE__*/ React.forwardRef(function({ style , className , layoutId , width , height , variant: outerVariant = "JdUDMq_5J" , title: gNFMfYrIy = "Get Started - It's Free" , ...restProps }, ref) {
    const outerVariantId = humanReadableVariantMap[outerVariant];
    const variant = outerVariantId || outerVariant;
    const { variants , baseVariant , gestureVariant , classNames , transition , setVariant , setGestureState  } = useVariantState({
        defaultVariant: "JdUDMq_5J",
        variant,
        transitions,
        variantClassNames,
        enabledGestures,
        cycleOrder
    });
    const variantProps = React.useMemo(()=>({
            "yM6MP0SOJ": {
                "JdUDMq_5J": {
                    "gap": 0,
                    "data-framer-name": "Small",
                    "__contentWrapperStyle": {
                        "width": "auto",
                        "height": "auto",
                        "padding": "0px 0px 0px 0px"
                    }
                },
                "LFNeAeMYh": {
                    "__contentWrapperStyle": {
                        "width": "auto",
                        "height": "auto",
                        "padding": "12px 24px 12px 24px"
                    }
                },
                "DNzDubC29": {
                    "rawHTML": "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0'><span style='-webkit-text-fill-color: hsl(0, 0%, 0%); font-family: &quot;GT Walsheim Medium&quot;, serif; font-size: 18px; letter-spacing: 0px; line-height: 1.2; text-align: center'>Get Started - It&#39;s Free</span><br></div></div>",
                    "alignment": "center",
                    "fonts": [
                        "CUSTOM;GT Walsheim Medium"
                    ]
                }
            }
        })
    , []);
    const addVariantProps = useAddVariantProps(baseVariant, gestureVariant, variantProps);
    const defaultLayoutId = useRandomID();
    return(/*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
        children: /*#__PURE__*/ _jsx(motion.div, {
            initial: variant,
            animate: variants,
            className: cx("framer-8GiPU", classNames),
            style: {
                "display": "contents",
                "pointerEvents": "auto"
            },
            onHoverStart: ()=>setGestureState({
                    isHovered: true
                })
            ,
            onHoverEnd: ()=>setGestureState({
                    isHovered: false
                })
            ,
            onTapStart: ()=>setGestureState({
                    isPressed: true
                })
            ,
            onTap: ()=>setGestureState({
                    isPressed: false
                })
            ,
            onTapCancel: ()=>setGestureState({
                    isPressed: false
                })
            ,
            children: /*#__PURE__*/ _jsx(Stack, {
                ...restProps,
                style: {
                    "borderBottomLeftRadius": 20,
                    "borderBottomRightRadius": 20,
                    "borderTopRightRadius": 20,
                    "borderTopLeftRadius": 20,
                    "WebkitFilter": "brightness(1)",
                    "filter": "brightness(1)",
                    "rotate": 0,
                    "--border-bottom-width": "2px",
                    "--border-top-width": "2px",
                    "--border-right-width": "2px",
                    "--border-left-width": "2px",
                    "--border-style": "solid",
                    "--border-color": "rgba(34, 34, 34, 0.05)",
                    ...style
                },
                layoutId: "JdUDMq_5J",
                className: cx("framer-7gtv3v", className),
                background: null,
                direction: "vertical",
                distribution: "center",
                alignment: "center",
                gap: 10,
                __fromCanvasComponent: true,
                __contentWrapperStyle: {
                    "width": "auto",
                    "height": "auto",
                    "padding": "0px 0px 0px 0px"
                },
                center: false,
                "data-framer-name": "Large",
                "data-border": true,
                variants: {
                    "JdUDMq_5J-pressed": {
                        "WebkitFilter": "brightness(1)",
                        "filter": "brightness(1)",
                        "boxShadow": "none"
                    },
                    "yM6MP0SOJ": {
                        "--border-bottom-width": "1px",
                        "--border-top-width": "1px",
                        "--border-right-width": "1px",
                        "--border-left-width": "1px",
                        "--border-style": "solid",
                        "--border-color": "rgba(34, 34, 34, 0.05)",
                        "borderBottomLeftRadius": 10,
                        "borderBottomRightRadius": 10,
                        "borderTopRightRadius": 10,
                        "borderTopLeftRadius": 10
                    },
                    "yM6MP0SOJ-pressed": {
                        "WebkitFilter": "brightness(1)",
                        "filter": "brightness(1)",
                        "boxShadow": "none"
                    }
                },
                transition: transition,
                ref: ref,
                ...addVariantProps("JdUDMq_5J"),
                children: /*#__PURE__*/ _jsx(Stack, {
                    style: {
                        "borderBottomLeftRadius": 20,
                        "borderBottomRightRadius": 20,
                        "borderTopRightRadius": 20,
                        "borderTopLeftRadius": 20,
                        "WebkitFilter": "brightness(1)",
                        "filter": "brightness(1)",
                        "backgroundColor": "rgb(255, 255, 255)",
                        "rotate": 0
                    },
                    layoutId: "LFNeAeMYh",
                    className: "framer-sj6d8b",
                    direction: "vertical",
                    distribution: "center",
                    alignment: "center",
                    gap: 10,
                    __fromCanvasComponent: true,
                    __contentWrapperStyle: {
                        "width": "auto",
                        "height": "auto",
                        "padding": "18px 23px 18px 23px"
                    },
                    center: false,
                    variants: {
                        "JdUDMq_5J-hover": {
                            "WebkitFilter": "brightness(1)",
                            "filter": "brightness(1)",
                            "boxShadow": "0px 0px 0px 6px rgba(0, 153, 255, 0.25)"
                        },
                        "JdUDMq_5J-pressed": {
                            "WebkitFilter": "brightness(0.8)",
                            "filter": "brightness(0.8)",
                            "boxShadow": "0px 0px 0px 8px rgba(0, 153, 255, 0.25)"
                        },
                        "yM6MP0SOJ": {
                            "borderBottomLeftRadius": 10,
                            "borderBottomRightRadius": 10,
                            "borderTopRightRadius": 10,
                            "borderTopLeftRadius": 10
                        },
                        "yM6MP0SOJ-hover": {
                            "WebkitFilter": "brightness(1)",
                            "filter": "brightness(1)",
                            "boxShadow": "0px 0px 0px 4px rgba(0, 153, 255, 0.25)"
                        },
                        "yM6MP0SOJ-pressed": {
                            "WebkitFilter": "brightness(0.8)",
                            "filter": "brightness(0.8)",
                            "boxShadow": "0px 0px 0px 5px rgba(0, 153, 255, 0.25)"
                        }
                    },
                    transition: transition,
                    ...addVariantProps("LFNeAeMYh"),
                    children: /*#__PURE__*/ _jsx(Text1, {
                        style: {
                            "rotate": 0
                        },
                        withExternalLayout: true,
                        verticalAlignment: "top",
                        __fromCanvasComponent: true,
                        alignment: "center",
                        fonts: [
                            "CUSTOM;GT Walsheim Bold"
                        ],
                        layoutId: "DNzDubC29",
                        className: "framer-10fmji3",
                        rawHTML: "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0'><span style='-webkit-text-fill-color: hsl(0, 0%, 0%); font-family: &quot;GT Walsheim Bold&quot;, serif; font-size: 32px; letter-spacing: -0.8px; line-height: 1; text-align: center'>Get Started - It&#39;s Free</span><br></div></div>",
                        text: gNFMfYrIy,
                        transition: transition,
                        ...addVariantProps("DNzDubC29")
                    })
                })
            })
        })
    }));
});
const css = [
    ".framer-8GiPU [data-border=\"true\"]::after { content: \"\"; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none;}",
    ".framer-8GiPU .framer-7gtv3v {position: relative; overflow: visible; width: min-content; height: min-content;}",
    ".framer-8GiPU .framer-sj6d8b {position: relative; overflow: visible; width: min-content; height: min-content; flex: none;}",
    ".framer-8GiPU .framer-10fmji3 {position: relative; overflow: visible; width: auto; height: auto; flex: none; white-space: pre;}",
    ".framer-8GiPU.framer-v-7gtv3v .framer-7gtv3v {cursor: pointer;}",
    ".framer-8GiPU.framer-v-1rf6xal .framer-7gtv3v {cursor: pointer;}"
];
/**
 * This is a generated Framer component.
 * @framerVariables {"gNFMfYrIy": "title"}
 * @framerCanvasComponentVariantDetails {"propertyName": "variant", "data": {"default": {"layout": ["auto", "auto"]}, "XfBCAaOEs": {"layout": ["auto", "auto"]}, "j1DylS2lR": {"layout": ["auto", "auto"]}, "yM6MP0SOJ": {"layout": ["auto", "auto"]}, "X_Z5eFZZe": {"layout": ["auto", "auto"]}, "iiJFag7O0": {"layout": ["auto", "auto"]}}}
 * @framerIntrinsicHeight 68
 * @framerIntrinsicWidth 358
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight any
 */ const FramermY56S67Qe = withCSS(Component, css);
export default FramermY56S67Qe;
FramermY56S67Qe.displayName = "Button Copy";
FramermY56S67Qe.defaultProps = {
    "width": 358,
    "height": 68
};
addPropertyControls(FramermY56S67Qe, {
    "variant": {
        "type": ControlType.Enum,
        "title": "Variant",
        "options": [
            "JdUDMq_5J",
            "yM6MP0SOJ"
        ],
        "optionTitles": [
            "Large",
            "Small"
        ]
    },
    "gNFMfYrIy": {
        "type": ControlType.String,
        "title": "Title",
        "defaultValue": "Get Started - It's Free"
    }
});
addFonts(FramermY56S67Qe, [
    {
        "url": new URL("assets/BEQRVDgs6J93DgS3UCYfVmYVd2E.ttf", import.meta.url).href,
        "family": "GT Walsheim Bold",
        "moduleAsset": {
            "url": "assets/BEQRVDgs6J93DgS3UCYfVmYVd2E.ttf",
            "localModuleIdentifier": "local-module:canvasComponent/mY56S67Qe:default"
        }
    }
]);

export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"FramermY56S67Qe","slots":[],"annotations":{"framerContractVersion":"1","framerSupportedLayoutHeight":"any","framerIntrinsicWidth":"358","framerVariables":"{\"gNFMfYrIy\": \"title\"}","framerSupportedLayoutWidth":"any","framerCanvasComponentVariantDetails":"{\"propertyName\": \"variant\", \"data\": {\"default\": {\"layout\": [\"auto\", \"auto\"]}, \"XfBCAaOEs\": {\"layout\": [\"auto\", \"auto\"]}, \"j1DylS2lR\": {\"layout\": [\"auto\", \"auto\"]}, \"yM6MP0SOJ\": {\"layout\": [\"auto\", \"auto\"]}, \"X_Z5eFZZe\": {\"layout\": [\"auto\", \"auto\"]}, \"iiJFag7O0\": {\"layout\": [\"auto\", \"auto\"]}}}","framerIntrinsicHeight":"68"}},"Props":{"type":"tsType","annotations":{"framerContractVersion":"1"}}}}
//# sourceMappingURL=./mY56S67Qe.map