import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Generated by Framer (e3d8fe7)
import * as React from "react";
import { motion, addPropertyControls, cx, useVariantState, useAddVariantProps, withCSS, LayoutGroup, ControlType, addFonts, Vector, Text as Text1, Stack, getFonts } from "framer";
import { useRandomID } from "https://framer.com/m/framer/randomID.js@^1.0.0";
import ButtonCopy from "https://framerusercontent.com/modules/p01zhxb9qUP7ZeOgCyuQ/QTjbAw1R1kcZUIbTURIa/mY56S67Qe.js";
const ButtonCopyFonts = getFonts(ButtonCopy);
const cycleOrder = [
    "dc0ziLF3g"
];
const variantClassNames = {
    "dc0ziLF3g": "framer-v-ohii1q"
};
const humanReadableVariantMap = {
};
const transitions = {
    "default": {
        "type": "spring",
        "ease": [
            0.44,
            0,
            0.56,
            1
        ],
        "duration": 0.3,
        "delay": 0,
        "stiffness": 500,
        "damping": 60,
        "mass": 1
    }
};
const Component = /*#__PURE__*/ React.forwardRef(function({ style , className , layoutId , width , height , variant: outerVariant = "dc0ziLF3g" , title: wf1sevtWn = "Framer" , title2: nnECCdgm9 = "Teams" , title3: ferVJgFLu = "Learn" , title4: eWqJD03US = "Pricing" , title5: LtfM4dXsU = "Blog" , title6: e08sGuU1G = "Updates" , title7: gWcaP3Mvb = "Support" , title8: XB38VrmmL = "Search" , title9: bZ9RndTr5 = "Sign in" , ...restProps }, ref) {
    const outerVariantId = humanReadableVariantMap[outerVariant];
    const variant = outerVariantId || outerVariant;
    const { variants , baseVariant , gestureVariant , classNames , transition , setVariant , setGestureState  } = useVariantState({
        defaultVariant: "dc0ziLF3g",
        variant,
        transitions,
        variantClassNames,
        cycleOrder
    });
    const variantProps = React.useMemo(()=>({
        })
    , []);
    const addVariantProps = useAddVariantProps(baseVariant, gestureVariant, variantProps);
    const defaultLayoutId = useRandomID();
    return(/*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
        children: /*#__PURE__*/ _jsx(motion.div, {
            initial: variant,
            animate: variants,
            className: cx("framer-jNexl", classNames),
            style: {
                "display": "contents"
            },
            onHoverStart: ()=>setGestureState({
                    isHovered: true
                })
            ,
            onHoverEnd: ()=>setGestureState({
                    isHovered: false
                })
            ,
            onTapStart: ()=>setGestureState({
                    isPressed: true
                })
            ,
            onTap: ()=>setGestureState({
                    isPressed: false
                })
            ,
            onTapCancel: ()=>setGestureState({
                    isPressed: false
                })
            ,
            children: /*#__PURE__*/ _jsxs(Stack, {
                ...restProps,
                style: {
                    "boxShadow": "0px 1px 2px 0px rgba(0, 0, 0, 0.1)",
                    "backgroundColor": "rgba(255, 255, 255, 0)",
                    ...style
                },
                layoutId: "dc0ziLF3g",
                className: cx("framer-ohii1q", className),
                direction: "horizontal",
                distribution: "center",
                alignment: "center",
                gap: 40,
                __fromCanvasComponent: true,
                __contentWrapperStyle: {
                    "width": "100%",
                    "height": "100%",
                    "padding": "0px 20px 0px 40px"
                },
                center: false,
                "data-framer-name": "Variant 1",
                transition: transition,
                ref: ref,
                ...addVariantProps("dc0ziLF3g"),
                children: [
                    /*#__PURE__*/ _jsxs(Stack, {
                        style: {
                        },
                        layoutId: "Dl39olcSq",
                        className: "framer-xyjp4i",
                        background: null,
                        direction: "horizontal",
                        distribution: "center",
                        alignment: "center",
                        gap: 16,
                        __fromCanvasComponent: true,
                        __contentWrapperStyle: {
                            "width": "auto",
                            "height": "100%",
                            "padding": "0px 0px 0px 0px"
                        },
                        center: false,
                        transition: transition,
                        ...addVariantProps("Dl39olcSq"),
                        children: [
                            /*#__PURE__*/ _jsx(motion.div, {
                                style: {
                                },
                                layout: "position",
                                layoutId: "quMjAJ8qV",
                                className: "framer-w8lahp",
                                background: null,
                                transition: transition,
                                ...addVariantProps("quMjAJ8qV"),
                                children: /*#__PURE__*/ _jsx(Vector, {
                                    style: {
                                    },
                                    d: "M 0 0 L 16 0 L 16 8 L 8 8 Z M 0 8 L 8 8 L 16 16 L 8 16 L 8 24 L 0 16 Z",
                                    id: "ZuBdtkIrm",
                                    isRootVectorNode: true,
                                    shapeId: "id_ZuBdtkIrm",
                                    strokeClipId: "id_ZuBdtkIrm_clip",
                                    rect: {
                                        "x": 0,
                                        "y": 0,
                                        "width": 16,
                                        "height": 24
                                    },
                                    strokeAlpha: 0,
                                    name: "Unite",
                                    rotation: 0,
                                    strokeEnabled: false,
                                    fill: "hsl(0, 0%, 100%)",
                                    transition: transition,
                                    ...addVariantProps("ZuBdtkIrm")
                                })
                            }),
                            /*#__PURE__*/ _jsx(Text1, {
                                style: {
                                },
                                withExternalLayout: true,
                                verticalAlignment: "top",
                                __fromCanvasComponent: true,
                                fonts: [
                                    "CUSTOM;GT Walsheim Medium"
                                ],
                                layoutId: "nYgV3XOT_",
                                className: "framer-1wah04g",
                                fontFamily: "\\\"Inter\\\", sans-serif",
                                textColor: "rgb(0, 0, 0)",
                                fontSize: 16,
                                textTransform: "none",
                                textDecoration: "none",
                                linkTextDecoration: "underline",
                                rawHTML: "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0; text-align: start'><span style='-webkit-text-fill-color: hsl(0, 0%, 100%); font-family: &quot;GT Walsheim Medium&quot;, serif; font-size: 18px; letter-spacing: 0px; line-height: 1.2em; text-decoration: none; text-transform: none'>Framer</span><br></div></div>",
                                text: wf1sevtWn,
                                transition: transition,
                                ...addVariantProps("nYgV3XOT_")
                            })
                        ]
                    }),
                    /*#__PURE__*/ _jsx(Text1, {
                        style: {
                            "opacity": 0.7
                        },
                        withExternalLayout: true,
                        verticalAlignment: "center",
                        __fromCanvasComponent: true,
                        fonts: [
                            "CUSTOM;GT Walsheim Regular"
                        ],
                        layoutId: "RBi9hGIeC",
                        className: "framer-lyi0vt",
                        fontFamily: "\\\"Inter\\\", sans-serif",
                        textColor: "rgb(0, 0, 0)",
                        fontSize: 16,
                        textTransform: "none",
                        textDecoration: "none",
                        linkTextDecoration: "underline",
                        rawHTML: "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0; text-align: start'><span style='-webkit-text-fill-color: hsl(0, 0%, 100%); font-family: &quot;GT Walsheim Regular&quot;, serif; font-size: 18px; letter-spacing: 0px; line-height: 1.2em; text-decoration: none; text-transform: none'>Teams</span><br></div></div>",
                        text: nnECCdgm9,
                        transition: transition,
                        ...addVariantProps("RBi9hGIeC")
                    }),
                    /*#__PURE__*/ _jsxs(Stack, {
                        style: {
                        },
                        layoutId: "qbiSIjoSR",
                        className: "framer-7vun88",
                        background: null,
                        direction: "horizontal",
                        distribution: "center",
                        alignment: "center",
                        gap: 10,
                        __fromCanvasComponent: true,
                        __contentWrapperStyle: {
                            "width": "auto",
                            "height": "100%",
                            "padding": "0px 0px 0px 0px"
                        },
                        center: false,
                        transition: transition,
                        ...addVariantProps("qbiSIjoSR"),
                        children: [
                            /*#__PURE__*/ _jsx(Text1, {
                                style: {
                                    "opacity": 0.7
                                },
                                withExternalLayout: true,
                                verticalAlignment: "top",
                                __fromCanvasComponent: true,
                                fonts: [
                                    "CUSTOM;GT Walsheim Regular"
                                ],
                                layoutId: "zlWhbtCu5",
                                className: "framer-1s6zs5w",
                                fontFamily: "\\\"Inter\\\", sans-serif",
                                textColor: "rgb(0, 0, 0)",
                                fontSize: 16,
                                textTransform: "none",
                                textDecoration: "none",
                                linkTextDecoration: "underline",
                                rawHTML: "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0; text-align: start'><span style='-webkit-text-fill-color: hsl(0, 0%, 100%); font-family: &quot;GT Walsheim Regular&quot;, serif; font-size: 18px; letter-spacing: 0px; line-height: 1.2em; text-decoration: none; text-transform: none'>Learn</span><br></div></div>",
                                text: ferVJgFLu,
                                transition: transition,
                                ...addVariantProps("zlWhbtCu5")
                            }),
                            /*#__PURE__*/ _jsx(motion.div, {
                                style: {
                                },
                                layout: "position",
                                layoutId: "RY8o8UWZF",
                                className: "framer-17l6slg",
                                background: null,
                                transition: transition,
                                ...addVariantProps("RY8o8UWZF"),
                                children: /*#__PURE__*/ _jsx(Vector, {
                                    style: {
                                    },
                                    d: "M 0 0 L 3.5 3.5 L 7 0",
                                    id: "K66xnq6Vh",
                                    isRootVectorNode: true,
                                    shapeId: "id_K66xnq6Vh",
                                    strokeClipId: "id_K66xnq6Vh_clip",
                                    rect: {
                                        "x": 1.5,
                                        "y": 3.5,
                                        "width": 7,
                                        "height": 3.5
                                    },
                                    strokeAlpha: 1,
                                    name: "Path",
                                    rotation: 0,
                                    lineCap: "round",
                                    lineJoin: "miter",
                                    strokeColor: "hsl(0, 0%, 100%)",
                                    strokeDashArray: "0",
                                    strokeDashOffset: 0,
                                    strokeMiterLimit: 4,
                                    strokeEnabled: true,
                                    insideStroke: false,
                                    strokeWidth: 1.5,
                                    fill: null,
                                    transition: transition,
                                    ...addVariantProps("K66xnq6Vh")
                                })
                            })
                        ]
                    }),
                    /*#__PURE__*/ _jsx(Text1, {
                        style: {
                            "opacity": 0.7
                        },
                        withExternalLayout: true,
                        verticalAlignment: "center",
                        __fromCanvasComponent: true,
                        fonts: [
                            "CUSTOM;GT Walsheim Regular"
                        ],
                        layoutId: "sHbzYbRuZ",
                        className: "framer-1iqk0r3",
                        fontFamily: "\\\"Inter\\\", sans-serif",
                        textColor: "rgb(0, 0, 0)",
                        fontSize: 16,
                        textTransform: "none",
                        textDecoration: "none",
                        linkTextDecoration: "underline",
                        rawHTML: "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0; text-align: start'><span style='-webkit-text-fill-color: hsl(0, 0%, 100%); font-family: &quot;GT Walsheim Regular&quot;, serif; font-size: 18px; letter-spacing: 0px; line-height: 1.2em; text-decoration: none; text-transform: none'>Pricing</span><br></div></div>",
                        text: eWqJD03US,
                        transition: transition,
                        ...addVariantProps("sHbzYbRuZ")
                    }),
                    /*#__PURE__*/ _jsx(Text1, {
                        style: {
                            "opacity": 0.7
                        },
                        withExternalLayout: true,
                        verticalAlignment: "center",
                        __fromCanvasComponent: true,
                        fonts: [
                            "CUSTOM;GT Walsheim Regular"
                        ],
                        layoutId: "Z0XahMD9j",
                        className: "framer-1mxww97",
                        fontFamily: "\\\"Inter\\\", sans-serif",
                        textColor: "rgb(0, 0, 0)",
                        fontSize: 16,
                        textTransform: "none",
                        textDecoration: "none",
                        linkTextDecoration: "underline",
                        rawHTML: "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0; text-align: start'><span style='-webkit-text-fill-color: hsl(0, 0%, 100%); font-family: &quot;GT Walsheim Regular&quot;, serif; font-size: 18px; letter-spacing: 0px; line-height: 1.2em; text-decoration: none; text-transform: none'>Blog</span><br></div></div>",
                        text: LtfM4dXsU,
                        transition: transition,
                        ...addVariantProps("Z0XahMD9j")
                    }),
                    /*#__PURE__*/ _jsx(Text1, {
                        style: {
                            "opacity": 0.7
                        },
                        withExternalLayout: true,
                        verticalAlignment: "center",
                        __fromCanvasComponent: true,
                        fonts: [
                            "CUSTOM;GT Walsheim Regular"
                        ],
                        layoutId: "I6gXcT1jY",
                        className: "framer-wzd3xb",
                        fontFamily: "\\\"Inter\\\", sans-serif",
                        textColor: "rgb(0, 0, 0)",
                        fontSize: 16,
                        textTransform: "none",
                        textDecoration: "none",
                        linkTextDecoration: "underline",
                        rawHTML: "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0; text-align: start'><span style='-webkit-text-fill-color: hsl(0, 0%, 100%); font-family: &quot;GT Walsheim Regular&quot;, serif; font-size: 18px; letter-spacing: 0px; line-height: 1.2em; text-decoration: none; text-transform: none'>Updates</span><br></div></div>",
                        text: e08sGuU1G,
                        transition: transition,
                        ...addVariantProps("I6gXcT1jY")
                    }),
                    /*#__PURE__*/ _jsx(Text1, {
                        style: {
                            "opacity": 0.7
                        },
                        withExternalLayout: true,
                        verticalAlignment: "center",
                        __fromCanvasComponent: true,
                        fonts: [
                            "CUSTOM;GT Walsheim Regular"
                        ],
                        layoutId: "HmHUN7GeP",
                        className: "framer-9krjmi",
                        fontFamily: "\\\"Inter\\\", sans-serif",
                        textColor: "rgb(0, 0, 0)",
                        fontSize: 16,
                        textTransform: "none",
                        textDecoration: "none",
                        linkTextDecoration: "underline",
                        rawHTML: "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0; text-align: start'><span style='-webkit-text-fill-color: hsl(0, 0%, 100%); font-family: &quot;GT Walsheim Regular&quot;, serif; font-size: 18px; letter-spacing: 0px; line-height: 1.2em; text-decoration: none; text-transform: none'>Support</span><br></div></div>",
                        text: gWcaP3Mvb,
                        transition: transition,
                        ...addVariantProps("HmHUN7GeP")
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                        style: {
                        },
                        layoutId: "i6R0yLzNH",
                        className: "framer-1njl44n",
                        background: null,
                        transition: transition,
                        ...addVariantProps("i6R0yLzNH")
                    }),
                    /*#__PURE__*/ _jsxs(Stack, {
                        style: {
                        },
                        layoutId: "J59AkoqlS",
                        className: "framer-nxhaxd",
                        background: null,
                        direction: "horizontal",
                        distribution: "center",
                        alignment: "center",
                        gap: 10,
                        __fromCanvasComponent: true,
                        __contentWrapperStyle: {
                            "width": "auto",
                            "height": "100%",
                            "padding": "0px 0px 0px 0px"
                        },
                        center: false,
                        transition: transition,
                        ...addVariantProps("J59AkoqlS"),
                        children: [
                            /*#__PURE__*/ _jsxs(motion.div, {
                                style: {
                                    "opacity": 0.7
                                },
                                layout: "position",
                                layoutId: "mLY_tQJlX",
                                className: "framer-1bjcj0r",
                                background: null,
                                transition: transition,
                                ...addVariantProps("mLY_tQJlX"),
                                children: [
                                    /*#__PURE__*/ _jsx(Vector, {
                                        style: {
                                        },
                                        d: "M 6.5 0 C 10.089850873900158 0 13 2.9101491260998418 13 6.5 C 13 10.089850873900158 10.089850873900158 13 6.5 13 C 2.9101491260998418 13 0 10.089850873900158 0 6.5 C 0 2.9101491260998418 2.9101491260998418 0 6.5 0 Z",
                                        id: "IL31wU3z3",
                                        isRootVectorNode: true,
                                        shapeId: "id_IL31wU3z3",
                                        strokeClipId: "id_IL31wU3z3_clip",
                                        rect: {
                                            "x": 1,
                                            "y": 1,
                                            "width": 13,
                                            "height": 13
                                        },
                                        strokeAlpha: 1,
                                        name: "Oval",
                                        rotation: 0,
                                        lineCap: "butt",
                                        lineJoin: "miter",
                                        strokeColor: "hsl(0, 0%, 100%)",
                                        strokeDashArray: "0",
                                        strokeDashOffset: 0,
                                        strokeMiterLimit: 4,
                                        strokeEnabled: true,
                                        insideStroke: true,
                                        strokeWidth: 4,
                                        fill: null,
                                        transition: transition,
                                        ...addVariantProps("IL31wU3z3")
                                    }),
                                    /*#__PURE__*/ _jsx(Vector, {
                                        style: {
                                        },
                                        d: "M 0 0 L 3 3",
                                        id: "HpuUDU_yY",
                                        isRootVectorNode: true,
                                        shapeId: "id_HpuUDU_yY",
                                        strokeClipId: "id_HpuUDU_yY_clip",
                                        rect: {
                                            "x": 11.5,
                                            "y": 11.5,
                                            "width": 3,
                                            "height": 3
                                        },
                                        strokeAlpha: 1,
                                        name: "Path",
                                        rotation: 0,
                                        lineCap: "round",
                                        lineJoin: "miter",
                                        strokeColor: "hsl(0, 0%, 100%)",
                                        strokeDashArray: "0",
                                        strokeDashOffset: 0,
                                        strokeMiterLimit: 4,
                                        strokeEnabled: true,
                                        insideStroke: false,
                                        strokeWidth: 2,
                                        fill: null,
                                        transition: transition,
                                        ...addVariantProps("HpuUDU_yY")
                                    })
                                ]
                            }),
                            /*#__PURE__*/ _jsx(Text1, {
                                style: {
                                    "opacity": 0.7
                                },
                                withExternalLayout: true,
                                verticalAlignment: "top",
                                __fromCanvasComponent: true,
                                fonts: [
                                    "CUSTOM;GT Walsheim Regular"
                                ],
                                layoutId: "EKo83mX6n",
                                className: "framer-6voint",
                                fontFamily: "\\\"Inter\\\", sans-serif",
                                textColor: "rgb(0, 0, 0)",
                                fontSize: 16,
                                textTransform: "none",
                                textDecoration: "none",
                                linkTextDecoration: "underline",
                                rawHTML: "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0; text-align: start'><span style='-webkit-text-fill-color: hsl(0, 0%, 100%); font-family: &quot;GT Walsheim Regular&quot;, serif; font-size: 18px; letter-spacing: 0px; line-height: 1.2em; text-decoration: none; text-transform: none'>Search</span><br></div></div>",
                                text: XB38VrmmL,
                                transition: transition,
                                ...addVariantProps("EKo83mX6n")
                            })
                        ]
                    }),
                    /*#__PURE__*/ _jsx(Text1, {
                        style: {
                            "opacity": 0.7
                        },
                        withExternalLayout: true,
                        verticalAlignment: "top",
                        __fromCanvasComponent: true,
                        fonts: [
                            "CUSTOM;GT Walsheim Regular"
                        ],
                        layoutId: "HfvN0o4jR",
                        className: "framer-1l59c7w",
                        fontFamily: "\\\"Inter\\\", sans-serif",
                        textColor: "rgb(0, 0, 0)",
                        fontSize: 16,
                        textTransform: "none",
                        textDecoration: "none",
                        linkTextDecoration: "underline",
                        rawHTML: "<div style='font-size: 0; line-height: 0; tab-size: 4; white-space: inherit; word-wrap: inherit'><div style='direction: ltr; font-size: 0; text-align: start'><span style='-webkit-text-fill-color: hsl(0, 0%, 100%); font-family: &quot;GT Walsheim Regular&quot;, serif; font-size: 18px; letter-spacing: 0px; line-height: 1.2em; text-decoration: none; text-transform: none'>Sign in</span><br></div></div>",
                        text: bZ9RndTr5,
                        transition: transition,
                        ...addVariantProps("HfvN0o4jR")
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                        style: {
                        },
                        layoutId: "ib6L9j15V-container",
                        className: "framer-1qld7i5-container",
                        transition: transition,
                        ...addVariantProps("ib6L9j15V-container"),
                        children: /*#__PURE__*/ _jsx(ButtonCopy, {
                            width: "100%",
                            height: "100%",
                            layoutId: "ib6L9j15V",
                            id: "ib6L9j15V",
                            variant: "yM6MP0SOJ",
                            title: "Get started–it’s free",
                            transition: transition,
                            ...addVariantProps("ib6L9j15V")
                        })
                    })
                ]
            })
        })
    }));
});
const css = [
    ".framer-jNexl [data-border=\"true\"]::after { content: \"\"; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none;}",
    ".framer-jNexl .framer-ohii1q { position: relative; overflow: visible; width: 1800px; height: 80px; }",
    ".framer-jNexl .framer-xyjp4i, .framer-jNexl .framer-nxhaxd { position: relative; overflow: visible; width: min-content; height: 100%; flex: none; }",
    ".framer-jNexl .framer-w8lahp { position: relative; width: 16px; height: 24px; flex: none; }",
    ".framer-jNexl .framer-1wah04g, .framer-jNexl .framer-1s6zs5w, .framer-jNexl .framer-9krjmi, .framer-jNexl .framer-6voint, .framer-jNexl .framer-1l59c7w { position: relative; overflow: visible; width: auto; height: auto; flex: none; white-space: pre; }",
    ".framer-jNexl .framer-lyi0vt, .framer-jNexl .framer-1iqk0r3, .framer-jNexl .framer-1mxww97, .framer-jNexl .framer-wzd3xb { position: relative; overflow: hidden; width: auto; height: 100%; flex: none; white-space: pre; }",
    ".framer-jNexl .framer-7vun88 { position: relative; overflow: visible; width: min-content; height: 80px; flex: none; }",
    ".framer-jNexl .framer-17l6slg { position: relative; width: 10px; height: 9px; flex: none; }",
    ".framer-jNexl .framer-1njl44n { position: relative; overflow: visible; width: 1px; height: 100%; flex: 1 0 0px; }",
    ".framer-jNexl .framer-1bjcj0r { position: relative; width: 16px; height: 16px; flex: none; }",
    ".framer-jNexl .framer-1qld7i5-container { position: relative; width: auto; height: auto; flex: none; }"
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 80
 * @framerIntrinsicWidth 1800
 * @framerCanvasComponentVariantDetails {"propertyName": "variant", "data": {"default": {"layout": ["fixed", "fixed"]}}}
 * @framerVariables {"wf1sevtWn": "title", "nnECCdgm9": "title2", "ferVJgFLu": "title3", "eWqJD03US": "title4", "LtfM4dXsU": "title5", "e08sGuU1G": "title6", "gWcaP3Mvb": "title7", "XB38VrmmL": "title8", "bZ9RndTr5": "title9"}
 */ const FramerPVCYaCHXB = withCSS(Component, css);
export default FramerPVCYaCHXB;
FramerPVCYaCHXB.displayName = "Nav";
FramerPVCYaCHXB.defaultProps = {
    "width": 1800,
    "height": 80
};
addPropertyControls(FramerPVCYaCHXB, {
    "wf1sevtWn": {
        "type": ControlType.String,
        "title": "Title",
        "defaultValue": "Framer",
        "displayTextArea": false
    },
    "nnECCdgm9": {
        "type": ControlType.String,
        "title": "Title 2",
        "defaultValue": "Teams",
        "displayTextArea": false
    },
    "ferVJgFLu": {
        "type": ControlType.String,
        "title": "Title 3",
        "defaultValue": "Learn",
        "displayTextArea": false
    },
    "eWqJD03US": {
        "type": ControlType.String,
        "title": "Title 4",
        "defaultValue": "Pricing",
        "displayTextArea": false
    },
    "LtfM4dXsU": {
        "type": ControlType.String,
        "title": "Title 5",
        "defaultValue": "Blog",
        "displayTextArea": false
    },
    "e08sGuU1G": {
        "type": ControlType.String,
        "title": "Title 6",
        "defaultValue": "Updates",
        "displayTextArea": false
    },
    "gWcaP3Mvb": {
        "type": ControlType.String,
        "title": "Title 7",
        "defaultValue": "Support",
        "displayTextArea": false
    },
    "XB38VrmmL": {
        "type": ControlType.String,
        "title": "Title 8",
        "defaultValue": "Search",
        "displayTextArea": false
    },
    "bZ9RndTr5": {
        "type": ControlType.String,
        "title": "Title 9",
        "defaultValue": "Sign in",
        "displayTextArea": false
    }
});
addFonts(FramerPVCYaCHXB, [
    {
        "url": new URL("assets/lYafHVZwqgZrS8IJan5h2BTNNK0.ttf", import.meta.url).href,
        "family": "GT Walsheim Medium",
        "moduleAsset": {
            "url": "assets/lYafHVZwqgZrS8IJan5h2BTNNK0.ttf",
            "localModuleIdentifier": "local-module:canvasComponent/PVCYaCHXB:default"
        }
    },
    {
        "url": new URL("assets/8TMEc25pgQJN4vUT0GWMDu1xY.ttf", import.meta.url).href,
        "family": "GT Walsheim Regular",
        "moduleAsset": {
            "url": "assets/8TMEc25pgQJN4vUT0GWMDu1xY.ttf",
            "localModuleIdentifier": "local-module:canvasComponent/PVCYaCHXB:default"
        }
    },
    ...ButtonCopyFonts
]);

export const __FramerMetadata__ = {"exports":{"Props":{"type":"tsType","annotations":{"framerContractVersion":"1"}},"default":{"type":"reactComponent","name":"FramerPVCYaCHXB","slots":[],"annotations":{"framerIntrinsicWidth":"1800","framerContractVersion":"1","framerIntrinsicHeight":"80","framerVariables":"{\"wf1sevtWn\": \"title\", \"nnECCdgm9\": \"title2\", \"ferVJgFLu\": \"title3\", \"eWqJD03US\": \"title4\", \"LtfM4dXsU\": \"title5\", \"e08sGuU1G\": \"title6\", \"gWcaP3Mvb\": \"title7\", \"XB38VrmmL\": \"title8\", \"bZ9RndTr5\": \"title9\"}","framerCanvasComponentVariantDetails":"{\"propertyName\": \"variant\", \"data\": {\"default\": {\"layout\": [\"fixed\", \"fixed\"]}}}"}}}}
//# sourceMappingURL=./PVCYaCHXB.map