module.exports = [
	{ code: /DEP_WEBPACK_CHUNK_GROUP_GET_MODULE_INDEX_2/ },
	{ code: /DEP_WEBPACK_CHUNK_MODULES_ITERABLE/ },
	{ code: /DEP_WEBPACK_CHUNK_TEMPLATE_RENDER_MANIFEST/ },
	{ code: /DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK/ },
	{ code: /DEP_WEBPACK_MAIN_TEMPLATE_GET_ASSET_PATH/ },
	{ code: /DEP_WEBPACK_MAIN_TEMPLATE_HASH_FOR_CHUNK/ },
	{ code: /DEP_WEBPACK_MAIN_TEMPLATE_OUTPUT_OPTIONS/ },
	{ code: /DEP_WEBPACK_MAIN_TEMPLATE_RENDER_CURRENT_HASH_CODE/ },
	{ code: /DEP_WEBPACK_MAIN_TEMPLATE_RENDER_MANIFEST/ },
	{ code: /DEP_WEBPACK_MAIN_TEMPLATE_REQUIRE_FN/ },
	{ code: /DEP_WEBPACK_MODULE_ID/ },
	{ code: /DEP_WEBPACK_MODULE_UPDATE_HASH/ }
];
