"use strict";

const fs = require("fs");

/** @typedef {import("webpack").Compiler} Compiler */

// A valid JS identifier can be a named export; other keys (e.g. `--foo` custom
// properties exported as `foo-bar`) are only reachable via `import * as styles`.
const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

/**
 * Renders a CSS module's export map into a `.d.ts`. webpack's native CSS
 * defaults to `namedExports: true`, so each identifier-safe name is emitted as a
 * `export const … : string`, matching `import { foo } from "./x.module.css"`.
 * @param {Map<string, string>} exports the original-name -> scoped-name map
 * @returns {string} the `.d.ts` contents
 */
const toDts = (exports) => {
	const lines = ["// Generated by CssModuleTypesPlugin. Do not edit."];
	for (const name of exports.keys()) {
		if (IDENTIFIER.test(name)) lines.push(`export const ${name}: string;`);
	}
	return `${lines.join("\n")}\n`;
};

/**
 * Writes a TypeScript declaration **next to each CSS module** (e.g.
 * `style.module.css.d.ts` beside `style.module.css`) so editors and `tsc` type
 * `import … from "./x.module.css"`. The names come from
 * `module.buildInfo.cssData.exports` (a `Map<string, string>` of original name
 * -> generated scoped name) — the same source webpack uses for the JS exports,
 * so no separate parse of the CSS is needed. Commit the generated `.d.ts`
 * files, or add `*.module.css.d.ts` to `.gitignore` — either works.
 */
class CssModuleTypesPlugin {
	/**
	 * @param {Compiler} compiler the compiler
	 * @returns {void}
	 */
	apply(compiler) {
		const { Compilation } = compiler.webpack;

		compiler.hooks.thisCompilation.tap(
			"CssModuleTypesPlugin",
			(compilation) => {
				compilation.hooks.processAssets.tap(
					{
						name: "CssModuleTypesPlugin",
						stage: Compilation.PROCESS_ASSETS_STAGE_ADDITIONAL
					},
					() => {
						for (const module of compilation.modules) {
							const cssData =
								/** @type {{ exports?: Map<string, string> }=} */
								(module.buildInfo && module.buildInfo.cssData);
							if (!cssData || !cssData.exports || cssData.exports.size === 0) {
								continue;
							}
							const { resource } =
								/** @type {import("webpack").NormalModule} */ (module);
							fs.writeFileSync(`${resource}.d.ts`, toDts(cssData.exports));
						}
					}
				);
			}
		);
	}
}

/** @type {import("webpack").Configuration} */
const config = {
	output: {
		uniqueName: "app"
	},
	experiments: {
		css: true
	},
	plugins: [new CssModuleTypesPlugin()]
};

module.exports = config;
