/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Emanuele Stoppa @ematipico
*/

"use strict";

/**
 * @typedef {Object} FlagDefinition
 * @property {String} [name] The name of the flag
 * @property {Function} [type] The typology of the flag. Using a function can force also a validation
 * @property {any} [defaultValue] The default value to give to the flag. Can be anything.
 * @property {String} [description] The description of the flag.
 * @property {String} [link] Link to the documentation.
 * @property {Boolean} [multiple] Can contain multiple values.
 * @property {String} [usage] Shows how to use the flag
 * @property {String} [alias] A shortcut to use the flag
 */

/**
 *
 * @type {FlagDefinition[]}
 */
const flags = [
	{
		name: "entry",
		type: String,
		defaultValue: null,
		description: "The entry point of your application.",
		link: "https://webpack.js.org/concepts/#entry"
	},
	{
		name: "config",
		usage:
			"--config <path to webpack configuration file> e.g. ./webpack.config.js",
		alias: "c",
		type: String,
		defaultValue: null,
		description: "Provide path to a webpack configuration file",
		link: "https://webpack.js.org/configuration/"
	},
	{
		name: "merge",
		usage:
			"--merge <path to configuration to be merged> e.g. ./webpack.config.js",
		alias: "m",
		type: String,
		description: "Merge a configuration file using webpack-merge",
		link: "https://github.com/survivejs/webpack-merge"
	},
	{
		name: "progress",
		usage: "--progress",
		type: Boolean,
		description: "Print compilation progress during build"
	},
	{
		name: "silent",
		usage: "--silent",
		type: Boolean,
		description: "Disable any output that webpack makes"
	},
	{
		name: "help",
		usage: "--help",
		type: Boolean,
		description: "Outputs list of supported flags"
	},
	{
		name: "defaults",
		usage: "--defaults",
		type: Boolean,
		description: "Allow webpack to set defaults aggresively",
		link: "https://github.com/webpack-contrib/webpack-defaults"
	},
	{
		name: "output",
		usage: "--output <path to output directory> e.g. ./dist/",
		alias: "o",
		type: String,
		description: "Output location of the file generated by webpack",
		link: "https://webpack.js.org/concepts/#output"
	},
	{
		name: "plugin",
		usage: "--plugin",
		type: String,
		description: "Load a given plugin",
		link: "https://webpack.js.org/plugins/"
	},
	{
		name: "global",
		usage: "--global myVar ./global.js",
		alias: "g",
		type: String,
		multiple: true,
		description: "Declares and exposes a global variable"
	},
	{
		name: "target",
		alias: "t",
		type: String,
		description: "Sets the build target",
		link: "https://webpack.js.org/configuration/target/#target"
	},
	{
		name: "watch",
		usage: "--watch",
		type: Boolean,
		alias: "w",
		description: "Watch for files changes",
		link: "https://webpack.js.org/configuration/watch/"
	},
	{
		name: "hot",
		usage: "--hot",
		alias: "h",
		type: Boolean,
		description: "Enables Hot Module Replacement",
		link: "https://webpack.js.org/concepts/hot-module-replacement/"
	},
	{
		name: "sourcemap",
		usage: "--sourcemap <sourcemap|eval|>",
		type: String,
		alias: "s",
		defaultValue: undefined,
		description: "Determine source maps to use",
		link: "https://webpack.js.org/configuration/devtool/#devtool"
	},
	{
		name: "prefetch",
		usage: "--prefetch <request>",
		type: String,
		description: "Prefetch this request",
		link: "https://webpack.js.org/plugins/prefetch-plugin/"
	},
	{
		name: "json",
		usage: "--json",
		type: Boolean,
		alias: "j",
		description: "Prints result as JSON"
	},
	{
		name: "standard",
		usage: "--standard",
		type: Boolean,
		description: "Prints standard output"
	},
	{
		name: "mode",
		usage: "--mode <development | production>",
		type: String,
		description: "Defines the mode to pass to webpack",
		link: "https://webpack.js.org/concepts/#mode"
	},
	{
		name: "version",
		usage: "--version",
		type: Boolean,
		description: "Get current version"
	},
	{
		name: "node-args",
		usage: '--node-args "--max-old-space-size=1024"',
		type: String,
		multiple: true,
		description: "NodeJS flags"
	}
];

module.exports = flags;
