/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/

"use strict";

// AUTO-GENERATED by tooling/generate-internal-serializables.js
// We need to include a list of requires here
// to allow webpack to be bundled with only static requires
// We could use a dynamic require(`../${request}`) but this
// would include too many modules and not every tool is able
// to process this
module.exports = {
	"asset/AssetModule": () => require("../asset/AssetModule"),
	"asset/RawDataUrlModule": () => require("../asset/RawDataUrlModule"),
	"cache/PackFileCacheStrategy": () =>
		require("../cache/PackFileCacheStrategy"),
	"cache/ResolverCachePlugin": () => require("../cache/ResolverCachePlugin"),
	"container/ContainerEntryDependency": () =>
		require("../container/ContainerEntryDependency"),
	"container/ContainerEntryModule": () =>
		require("../container/ContainerEntryModule"),
	"container/ContainerExposedDependency": () =>
		require("../container/ContainerExposedDependency"),
	"container/FallbackDependency": () =>
		require("../container/FallbackDependency"),
	"container/FallbackItemDependency": () =>
		require("../container/FallbackItemDependency"),
	"container/FallbackModule": () => require("../container/FallbackModule"),
	"container/RemoteModule": () => require("../container/RemoteModule"),
	"container/RemoteToExternalDependency": () =>
		require("../container/RemoteToExternalDependency"),
	"dependencies/AMDDefineDependency": () =>
		require("../dependencies/AMDDefineDependency"),
	"dependencies/AMDRequireArrayDependency": () =>
		require("../dependencies/AMDRequireArrayDependency"),
	"dependencies/AMDRequireContextDependency": () =>
		require("../dependencies/AMDRequireContextDependency"),
	"dependencies/AMDRequireDependenciesBlock": () =>
		require("../dependencies/AMDRequireDependenciesBlock"),
	"dependencies/AMDRequireDependency": () =>
		require("../dependencies/AMDRequireDependency"),
	"dependencies/AMDRequireItemDependency": () =>
		require("../dependencies/AMDRequireItemDependency"),
	"dependencies/CachedConstDependency": () =>
		require("../dependencies/CachedConstDependency"),
	"dependencies/CommonJsExportRequireDependency": () =>
		require("../dependencies/CommonJsExportRequireDependency"),
	"dependencies/CommonJsExportsDependency": () =>
		require("../dependencies/CommonJsExportsDependency"),
	"dependencies/CommonJsFullRequireDependency": () =>
		require("../dependencies/CommonJsFullRequireDependency"),
	"dependencies/CommonJsRequireContextDependency": () =>
		require("../dependencies/CommonJsRequireContextDependency"),
	"dependencies/CommonJsRequireDependency": () =>
		require("../dependencies/CommonJsRequireDependency"),
	"dependencies/CommonJsSelfReferenceDependency": () =>
		require("../dependencies/CommonJsSelfReferenceDependency"),
	"dependencies/ConstDependency": () =>
		require("../dependencies/ConstDependency"),
	"dependencies/ContextDependency": () =>
		require("../dependencies/ContextDependency"),
	"dependencies/ContextElementDependency": () =>
		require("../dependencies/ContextElementDependency"),
	"dependencies/CreateScriptUrlDependency": () =>
		require("../dependencies/CreateScriptUrlDependency"),
	"dependencies/CriticalDependencyWarning": () =>
		require("../dependencies/CriticalDependencyWarning"),
	"dependencies/CssIcssExportDependency": () =>
		require("../dependencies/CssIcssExportDependency"),
	"dependencies/CssIcssImportDependency": () =>
		require("../dependencies/CssIcssImportDependency"),
	"dependencies/CssIcssSymbolDependency": () =>
		require("../dependencies/CssIcssSymbolDependency"),
	"dependencies/CssImportDependency": () =>
		require("../dependencies/CssImportDependency"),
	"dependencies/CssUrlDependency": () =>
		require("../dependencies/CssUrlDependency"),
	"dependencies/DelegatedSourceDependency": () =>
		require("../dependencies/DelegatedSourceDependency"),
	"dependencies/DllEntryDependency": () =>
		require("../dependencies/DllEntryDependency"),
	"dependencies/EntryDependency": () =>
		require("../dependencies/EntryDependency"),
	"dependencies/ExportsInfoDependency": () =>
		require("../dependencies/ExportsInfoDependency"),
	"dependencies/ExternalModuleConstDependency": () =>
		require("../dependencies/ExternalModuleInitFragmentDependency"),
	"dependencies/ExternalModuleDependency": () =>
		require("../dependencies/ExternalModuleDependency"),
	"dependencies/ExternalModuleInitFragment": () =>
		require("../dependencies/ExternalModuleInitFragment"),
	"dependencies/ExternalModuleInitFragmentDependency": () =>
		require("../dependencies/ExternalModuleInitFragmentDependency"),
	"dependencies/HarmonyAcceptDependency": () =>
		require("../dependencies/HarmonyAcceptDependency"),
	"dependencies/HarmonyAcceptImportDependency": () =>
		require("../dependencies/HarmonyAcceptImportDependency"),
	"dependencies/HarmonyCompatibilityDependency": () =>
		require("../dependencies/HarmonyCompatibilityDependency"),
	"dependencies/HarmonyEvaluatedImportSpecifierDependency": () =>
		require("../dependencies/HarmonyEvaluatedImportSpecifierDependency"),
	"dependencies/HarmonyExportExpressionDependency": () =>
		require("../dependencies/HarmonyExportExpressionDependency"),
	"dependencies/HarmonyExportHeaderDependency": () =>
		require("../dependencies/HarmonyExportHeaderDependency"),
	"dependencies/HarmonyExportImportedSpecifierDependency": () =>
		require("../dependencies/HarmonyExportImportedSpecifierDependency"),
	"dependencies/HarmonyExportSpecifierDependency": () =>
		require("../dependencies/HarmonyExportSpecifierDependency"),
	"dependencies/HarmonyImportSideEffectDependency": () =>
		require("../dependencies/HarmonyImportSideEffectDependency"),
	"dependencies/HarmonyImportSpecifierDependency": () =>
		require("../dependencies/HarmonyImportSpecifierDependency"),
	"dependencies/HtmlEntryDependency": () =>
		require("../dependencies/HtmlEntryDependency"),
	"dependencies/HtmlInlineHtmlDependency": () =>
		require("../dependencies/HtmlInlineHtmlDependency"),
	"dependencies/HtmlInlineScriptDependency": () =>
		require("../dependencies/HtmlInlineScriptDependency"),
	"dependencies/HtmlInlineStyleDependency": () =>
		require("../dependencies/HtmlInlineStyleDependency"),
	"dependencies/HtmlSourceDependency": () =>
		require("../dependencies/HtmlSourceDependency"),
	"dependencies/ImportContextDependency": () =>
		require("../dependencies/ImportContextDependency"),
	"dependencies/ImportDependency": () =>
		require("../dependencies/ImportDependency"),
	"dependencies/ImportEagerDependency": () =>
		require("../dependencies/ImportEagerDependency"),
	"dependencies/ImportMetaContextDependency": () =>
		require("../dependencies/ImportMetaContextDependency"),
	"dependencies/ImportMetaGlobDependency": () =>
		require("../dependencies/ImportMetaGlobDependency"),
	"dependencies/ImportMetaHotAcceptDependency": () =>
		require("../dependencies/ImportMetaHotAcceptDependency"),
	"dependencies/ImportMetaHotDeclineDependency": () =>
		require("../dependencies/ImportMetaHotDeclineDependency"),
	"dependencies/ImportMetaResolveDependency": () =>
		require("../dependencies/ImportMetaResolveDependency"),
	"dependencies/ImportWeakDependency": () =>
		require("../dependencies/ImportWeakDependency"),
	"dependencies/JsonExportsDependency": () =>
		require("../dependencies/JsonExportsDependency"),
	"dependencies/LocalModule": () => require("../dependencies/LocalModule"),
	"dependencies/LocalModuleDependency": () =>
		require("../dependencies/LocalModuleDependency"),
	"dependencies/ModuleDecoratorDependency": () =>
		require("../dependencies/ModuleDecoratorDependency"),
	"dependencies/ModuleHotAcceptDependency": () =>
		require("../dependencies/ModuleHotAcceptDependency"),
	"dependencies/ModuleHotDeclineDependency": () =>
		require("../dependencies/ModuleHotDeclineDependency"),
	"dependencies/ModuleInitFragmentDependency": () =>
		require("../dependencies/ModuleInitFragmentDependency"),
	"dependencies/ProvidedDependency": () =>
		require("../dependencies/ProvidedDependency"),
	"dependencies/PureExpressionDependency": () =>
		require("../dependencies/PureExpressionDependency"),
	"dependencies/RequireContextDependency": () =>
		require("../dependencies/RequireContextDependency"),
	"dependencies/RequireEnsureDependenciesBlock": () =>
		require("../dependencies/RequireEnsureDependenciesBlock"),
	"dependencies/RequireEnsureDependency": () =>
		require("../dependencies/RequireEnsureDependency"),
	"dependencies/RequireEnsureItemDependency": () =>
		require("../dependencies/RequireEnsureItemDependency"),
	"dependencies/RequireHeaderDependency": () =>
		require("../dependencies/RequireHeaderDependency"),
	"dependencies/RequireIncludeDependency": () =>
		require("../dependencies/RequireIncludeDependency"),
	"dependencies/RequireIncludeDependencyParserPlugin": () =>
		require("../dependencies/RequireIncludeDependencyParserPlugin"),
	"dependencies/RequireResolveContextDependency": () =>
		require("../dependencies/RequireResolveContextDependency"),
	"dependencies/RequireResolveDependency": () =>
		require("../dependencies/RequireResolveDependency"),
	"dependencies/RequireResolveHeaderDependency": () =>
		require("../dependencies/RequireResolveHeaderDependency"),
	"dependencies/RuntimeRequirementsDependency": () =>
		require("../dependencies/RuntimeRequirementsDependency"),
	"dependencies/StaticExportsDependency": () =>
		require("../dependencies/StaticExportsDependency"),
	"dependencies/SystemPlugin": () => require("../dependencies/SystemPlugin"),
	"dependencies/TopLevelAwaitDependency": () =>
		require("../dependencies/TopLevelAwaitDependency"),
	"dependencies/URLContextDependency": () =>
		require("../dependencies/URLContextDependency"),
	"dependencies/URLDependency": () => require("../dependencies/URLDependency"),
	"dependencies/UnsupportedDependency": () =>
		require("../dependencies/UnsupportedDependency"),
	"dependencies/WebAssemblyExportImportedDependency": () =>
		require("../dependencies/WebAssemblyExportImportedDependency"),
	"dependencies/WebAssemblyImportDependency": () =>
		require("../dependencies/WebAssemblyImportDependency"),
	"dependencies/WebpackIsIncludedDependency": () =>
		require("../dependencies/WebpackIsIncludedDependency"),
	"dependencies/WorkerDependency": () =>
		require("../dependencies/WorkerDependency"),
	"dependencies/WorkletDependency": () =>
		require("../dependencies/WorkletDependency"),
	"dll/DelegatedModule": () => require("../dll/DelegatedModule"),
	"dll/DllModule": () => require("../dll/DllModule"),
	"errors/CommentCompilationWarning": () =>
		require("../errors/CommentCompilationWarning"),
	"errors/EnvironmentNotSupportAsyncWarning": () =>
		require("../errors/EnvironmentNotSupportAsyncWarning"),
	"errors/HookWebpackError": () => require("../errors/HookWebpackError"),
	"errors/InvalidDependenciesModuleWarning": () =>
		require("../errors/InvalidDependenciesModuleWarning"),
	"errors/JSONParseError": () => require("../errors/JSONParseError"),
	"errors/ModuleBuildError": () => require("../errors/ModuleBuildError"),
	"errors/ModuleDependencyWarning": () =>
		require("../errors/ModuleDependencyWarning"),
	"errors/ModuleError": () => require("../errors/ModuleError"),
	"errors/ModuleParseError": () => require("../errors/ModuleParseError"),
	"errors/ModuleWarning": () => require("../errors/ModuleWarning"),
	"errors/NodeStuffInWebError": () => require("../errors/NodeStuffInWebError"),
	"errors/NonErrorEmittedError": () =>
		require("../errors/NonErrorEmittedError"),
	"errors/UnhandledSchemeError": () =>
		require("../errors/UnhandledSchemeError"),
	"errors/UnsupportedFeatureWarning": () =>
		require("../errors/UnsupportedFeatureWarning"),
	"errors/WebpackError": () => require("../errors/WebpackError"),
	"html/HtmlModule": () => require("../html/HtmlModule"),
	"javascript/JavascriptModule": () =>
		require("../javascript/JavascriptModule"),
	"json/JsonData": () => require("../json/JsonData"),
	"json/JsonModule": () => require("../json/JsonModule"),
	"optimize/ConcatenatedModule": () =>
		require("../optimize/ConcatenatedModule"),
	"optimize/InlineExports": () => require("../optimize/InlineExports"),
	"sharing/ConsumeSharedFallbackDependency": () =>
		require("../sharing/ConsumeSharedFallbackDependency"),
	"sharing/ConsumeSharedModule": () =>
		require("../sharing/ConsumeSharedModule"),
	"sharing/ProvideForSharedDependency": () =>
		require("../sharing/ProvideForSharedDependency"),
	"sharing/ProvideSharedDependency": () =>
		require("../sharing/ProvideSharedDependency"),
	"sharing/ProvideSharedModule": () =>
		require("../sharing/ProvideSharedModule"),
	"util/LazySet": () => require("../util/LazySet"),
	"util/registerExternalSerializer": () => {
		// already registered
	},
	"wasm-async/AsyncWasmModule": () => require("../wasm-async/AsyncWasmModule"),
	"wasm-sync/SyncWasmModule": () => require("../wasm-sync/SyncWasmModule"),
	AsyncDependenciesBlock: () => require("../AsyncDependenciesBlock"),
	ContextModule: () => require("../ContextModule"),
	CssModule: () => require("../css/CssModule"),
	DependenciesBlock: () => require("../DependenciesBlock"),
	ExternalModule: () => require("../ExternalModule"),
	FileSystemInfo: () => require("../FileSystemInfo"),
	InitFragment: () => require("../InitFragment"),
	Module: () => require("../Module"),
	ModuleGraph: () => require("../ModuleGraph"),
	NodeStuffInWebError: () => require("../errors/NodeStuffInWebError"),
	NormalModule: () => require("../NormalModule"),
	RawDataUrlModule: () => require("../asset/RawDataUrlModule"),
	RawModule: () => require("../RawModule")
};
