/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/

"use strict";

// AUTO-GENERATED by tooling/generate-internal-serializables.js
// We need to include a list of requires here
// to allow webpack to be bundled with only static requires
// We could use a dynamic require(`../${request}`) but this
// would include too many modules and not every tool is able
// to process this
module.exports = {
	"asset/AssetModule": () => require("../asset/AssetModule"),
	"asset/RawDataUrlModule": () => require("../asset/RawDataUrlModule"),
	"cache/PackFileCacheStrategy": () =>
		require("../cache/PackFileCacheStrategy"),
	"cache/ResolverCachePlugin": () => require("../cache/ResolverCachePlugin"),
	"container/ContainerEntryDependency": () =>
		require("../container/ContainerEntryDependency"),
	"container/ContainerEntryModule": () =>
		require("../container/ContainerEntryModule"),
	"container/ContainerExposedDependency": () =>
		require("../container/ContainerExposedDependency"),
	"container/FallbackDependency": () =>
		require("../container/FallbackDependency"),
	"container/FallbackItemDependency": () =>
		require("../container/FallbackItemDependency"),
	"container/FallbackModule": () => require("../container/FallbackModule"),
	"container/RemoteModule": () => require("../container/RemoteModule"),
	"container/RemoteToExternalDependency": () =>
		require("../container/RemoteToExternalDependency"),
	"context/ContextModule": () => require("../context/ContextModule"),
	"dependencies/AMDDefineDependency": () =>
		require("../dependencies/amd/AMDDefineDependency"),
	"dependencies/AMDRequireArrayDependency": () =>
		require("../dependencies/amd/AMDRequireArrayDependency"),
	"dependencies/AMDRequireContextDependency": () =>
		require("../dependencies/amd/AMDRequireContextDependency"),
	"dependencies/AMDRequireDependenciesBlock": () =>
		require("../dependencies/amd/AMDRequireDependenciesBlock"),
	"dependencies/AMDRequireDependency": () =>
		require("../dependencies/amd/AMDRequireDependency"),
	"dependencies/AMDRequireItemDependency": () =>
		require("../dependencies/amd/AMDRequireItemDependency"),
	"dependencies/BuildTimeConstDependency": () =>
		require("../dependencies/BuildTimeConstDependency"),
	"dependencies/CachedConstDependency": () =>
		require("../dependencies/CachedConstDependency"),
	"dependencies/CommonJsExportRequireDependency": () =>
		require("../dependencies/commonjs/CommonJsExportRequireDependency"),
	"dependencies/CommonJsExportsDependency": () =>
		require("../dependencies/commonjs/CommonJsExportsDependency"),
	"dependencies/CommonJsFullRequireDependency": () =>
		require("../dependencies/commonjs/CommonJsFullRequireDependency"),
	"dependencies/CommonJsObjectExportDependency": () =>
		require("../dependencies/commonjs/CommonJsObjectExportDependency"),
	"dependencies/CommonJsRequireContextDependency": () =>
		require("../dependencies/commonjs/CommonJsRequireContextDependency"),
	"dependencies/CommonJsRequireDependency": () =>
		require("../dependencies/commonjs/CommonJsRequireDependency"),
	"dependencies/CommonJsSelfReferenceDependency": () =>
		require("../dependencies/commonjs/CommonJsSelfReferenceDependency"),
	"dependencies/ConstDependency": () =>
		require("../dependencies/ConstDependency"),
	"dependencies/ContextDependency": () =>
		require("../dependencies/context/ContextDependency"),
	"dependencies/ContextElementDependency": () =>
		require("../dependencies/context/ContextElementDependency"),
	"dependencies/CreateScriptUrlDependency": () =>
		require("../dependencies/worker/CreateScriptUrlDependency"),
	"dependencies/CriticalDependencyWarning": () =>
		require("../errors/CriticalDependencyWarning"),
	"dependencies/CssIcssExportDependency": () =>
		require("../dependencies/css/CssIcssExportDependency"),
	"dependencies/CssIcssImportDependency": () =>
		require("../dependencies/css/CssIcssImportDependency"),
	"dependencies/CssIcssSymbolDependency": () =>
		require("../dependencies/css/CssIcssSymbolDependency"),
	"dependencies/CssImportDependency": () =>
		require("../dependencies/css/CssImportDependency"),
	"dependencies/CssUrlDependency": () =>
		require("../dependencies/css/CssUrlDependency"),
	"dependencies/DelegatedSourceDependency": () =>
		require("../dll/DelegatedSourceDependency"),
	"dependencies/DllEntryDependency": () => require("../dll/DllEntryDependency"),
	"dependencies/ESMAcceptDependency": () =>
		require("../dependencies/esm/ESMAcceptDependency"),
	"dependencies/ESMAcceptImportDependency": () =>
		require("../dependencies/esm/ESMAcceptImportDependency"),
	"dependencies/ESMCompatibilityDependency": () =>
		require("../dependencies/esm/ESMCompatibilityDependency"),
	"dependencies/ESMEvaluatedImportSpecifierDependency": () =>
		require("../dependencies/esm/ESMEvaluatedImportSpecifierDependency"),
	"dependencies/ESMExportExpressionDependency": () =>
		require("../dependencies/esm/ESMExportExpressionDependency"),
	"dependencies/ESMExportHeaderDependency": () =>
		require("../dependencies/esm/ESMExportHeaderDependency"),
	"dependencies/ESMExportImportedSpecifierDependency": () =>
		require("../dependencies/esm/ESMExportImportedSpecifierDependency"),
	"dependencies/ESMExportSpecifierDependency": () =>
		require("../dependencies/esm/ESMExportSpecifierDependency"),
	"dependencies/ESMImportBareSideEffectDependency": () =>
		require("../dependencies/esm/ESMImportBareSideEffectDependency"),
	"dependencies/ESMImportSideEffectDependency": () =>
		require("../dependencies/esm/ESMImportSideEffectDependency"),
	"dependencies/ESMImportSpecifierDependency": () =>
		require("../dependencies/esm/ESMImportSpecifierDependency"),
	"dependencies/EntryDependency": () =>
		require("../dependencies/EntryDependency"),
	"dependencies/ExportsInfoDependency": () =>
		require("../dependencies/ExportsInfoDependency"),
	"dependencies/ExternalModuleConstDependency": () =>
		require("../node/ExternalModuleInitFragmentDependency"),
	"dependencies/ExternalModuleDependency": () =>
		require("../node/ExternalModuleDependency"),
	"dependencies/ExternalModuleInitFragment": () =>
		require("../node/ExternalModuleInitFragment"),
	"dependencies/ExternalModuleInitFragmentDependency": () =>
		require("../node/ExternalModuleInitFragmentDependency"),
	"dependencies/HarmonyAcceptDependency": () =>
		require("../dependencies/esm/ESMAcceptDependency"),
	"dependencies/HarmonyAcceptImportDependency": () =>
		require("../dependencies/esm/ESMAcceptImportDependency"),
	"dependencies/HarmonyCompatibilityDependency": () =>
		require("../dependencies/esm/ESMCompatibilityDependency"),
	"dependencies/HarmonyEvaluatedImportSpecifierDependency": () =>
		require("../dependencies/esm/ESMEvaluatedImportSpecifierDependency"),
	"dependencies/HarmonyExportExpressionDependency": () =>
		require("../dependencies/esm/ESMExportExpressionDependency"),
	"dependencies/HarmonyExportHeaderDependency": () =>
		require("../dependencies/esm/ESMExportHeaderDependency"),
	"dependencies/HarmonyExportImportedSpecifierDependency": () =>
		require("../dependencies/esm/ESMExportImportedSpecifierDependency"),
	"dependencies/HarmonyExportSpecifierDependency": () =>
		require("../dependencies/esm/ESMExportSpecifierDependency"),
	"dependencies/HarmonyImportBareSideEffectDependency": () =>
		require("../dependencies/esm/ESMImportBareSideEffectDependency"),
	"dependencies/HarmonyImportSideEffectDependency": () =>
		require("../dependencies/esm/ESMImportSideEffectDependency"),
	"dependencies/HarmonyImportSpecifierDependency": () =>
		require("../dependencies/esm/ESMImportSpecifierDependency"),
	"dependencies/HtmlEntryDependency": () =>
		require("../dependencies/html/HtmlEntryDependency"),
	"dependencies/HtmlInlineHtmlDependency": () =>
		require("../dependencies/html/HtmlInlineHtmlDependency"),
	"dependencies/HtmlInlineScriptDependency": () =>
		require("../dependencies/html/HtmlInlineScriptDependency"),
	"dependencies/HtmlInlineStyleDependency": () =>
		require("../dependencies/html/HtmlInlineStyleDependency"),
	"dependencies/HtmlSourceDependency": () =>
		require("../dependencies/html/HtmlSourceDependency"),
	"dependencies/ImportContextDependency": () =>
		require("../dependencies/ImportContextDependency"),
	"dependencies/ImportDependency": () =>
		require("../dependencies/ImportDependency"),
	"dependencies/ImportEagerDependency": () =>
		require("../dependencies/ImportEagerDependency"),
	"dependencies/ImportMetaContextDependency": () =>
		require("../dependencies/context/ImportMetaContextDependency"),
	"dependencies/ImportMetaGlobDependency": () =>
		require("../dependencies/context/ImportMetaGlobDependency"),
	"dependencies/ImportMetaHotAcceptDependency": () =>
		require("../dependencies/hmr/ImportMetaHotAcceptDependency"),
	"dependencies/ImportMetaHotDeclineDependency": () =>
		require("../dependencies/hmr/ImportMetaHotDeclineDependency"),
	"dependencies/ImportMetaMainDependency": () =>
		require("../dependencies/ImportMetaMainDependency"),
	"dependencies/ImportMetaResolveDependency": () =>
		require("../dependencies/ImportMetaResolveDependency"),
	"dependencies/ImportWeakDependency": () =>
		require("../dependencies/ImportWeakDependency"),
	"dependencies/JsonExportsDependency": () =>
		require("../json/JsonExportsDependency"),
	"dependencies/LocalModule": () => require("../dependencies/amd/LocalModule"),
	"dependencies/LocalModuleDependency": () =>
		require("../dependencies/amd/LocalModuleDependency"),
	"dependencies/ModuleDecoratorDependency": () =>
		require("../dependencies/ModuleDecoratorDependency"),
	"dependencies/ModuleHotAcceptDependency": () =>
		require("../dependencies/hmr/ModuleHotAcceptDependency"),
	"dependencies/ModuleHotDeclineDependency": () =>
		require("../dependencies/hmr/ModuleHotDeclineDependency"),
	"dependencies/ModuleInitFragmentDependency": () =>
		require("../dependencies/ModuleInitFragmentDependency"),
	"dependencies/ProvidedDependency": () =>
		require("../dependencies/ProvidedDependency"),
	"dependencies/PureExpressionDependency": () =>
		require("../dependencies/PureExpressionDependency"),
	"dependencies/RequireContextDependency": () =>
		require("../dependencies/context/RequireContextDependency"),
	"dependencies/RequireEnsureDependenciesBlock": () =>
		require("../dependencies/commonjs/RequireEnsureDependenciesBlock"),
	"dependencies/RequireEnsureDependency": () =>
		require("../dependencies/commonjs/RequireEnsureDependency"),
	"dependencies/RequireEnsureItemDependency": () =>
		require("../dependencies/commonjs/RequireEnsureItemDependency"),
	"dependencies/RequireHeaderDependency": () =>
		require("../dependencies/commonjs/RequireHeaderDependency"),
	"dependencies/RequireIncludeDependency": () =>
		require("../dependencies/commonjs/RequireIncludeDependency"),
	"dependencies/RequireIncludeDependencyParserPlugin": () =>
		require("../dependencies/commonjs/RequireIncludeDependencyParserPlugin"),
	"dependencies/RequireResolveContextDependency": () =>
		require("../dependencies/commonjs/RequireResolveContextDependency"),
	"dependencies/RequireResolveDependency": () =>
		require("../dependencies/commonjs/RequireResolveDependency"),
	"dependencies/RequireResolveHeaderDependency": () =>
		require("../dependencies/commonjs/RequireResolveHeaderDependency"),
	"dependencies/RuntimeRequirementsDependency": () =>
		require("../dependencies/RuntimeRequirementsDependency"),
	"dependencies/StaticExportsDependency": () =>
		require("../dependencies/StaticExportsDependency"),
	"dependencies/SystemPlugin": () =>
		require("../dependencies/system/SystemPlugin"),
	"dependencies/TopLevelAwaitDependency": () =>
		require("../dependencies/TopLevelAwaitDependency"),
	"dependencies/URLContextDependency": () =>
		require("../dependencies/URLContextDependency"),
	"dependencies/URLDependency": () => require("../dependencies/URLDependency"),
	"dependencies/UnsupportedDependency": () =>
		require("../dependencies/UnsupportedDependency"),
	"dependencies/WebAssemblyExportImportedDependency": () =>
		require("../dependencies/WebAssemblyExportImportedDependency"),
	"dependencies/WebAssemblyImportDependency": () =>
		require("../dependencies/WebAssemblyImportDependency"),
	"dependencies/WebpackIsIncludedDependency": () =>
		require("../dependencies/WebpackIsIncludedDependency"),
	"dependencies/WorkerDependency": () =>
		require("../dependencies/worker/WorkerDependency"),
	"dependencies/WorkletDependency": () =>
		require("../dependencies/worker/WorkletDependency"),
	"dependencies/amd/AMDDefineDependency": () =>
		require("../dependencies/amd/AMDDefineDependency"),
	"dependencies/amd/AMDRequireArrayDependency": () =>
		require("../dependencies/amd/AMDRequireArrayDependency"),
	"dependencies/amd/AMDRequireContextDependency": () =>
		require("../dependencies/amd/AMDRequireContextDependency"),
	"dependencies/amd/AMDRequireDependenciesBlock": () =>
		require("../dependencies/amd/AMDRequireDependenciesBlock"),
	"dependencies/amd/AMDRequireDependency": () =>
		require("../dependencies/amd/AMDRequireDependency"),
	"dependencies/amd/AMDRequireItemDependency": () =>
		require("../dependencies/amd/AMDRequireItemDependency"),
	"dependencies/amd/LocalModule": () =>
		require("../dependencies/amd/LocalModule"),
	"dependencies/amd/LocalModuleDependency": () =>
		require("../dependencies/amd/LocalModuleDependency"),
	"dependencies/commonjs/CommonJsExportRequireDependency": () =>
		require("../dependencies/commonjs/CommonJsExportRequireDependency"),
	"dependencies/commonjs/CommonJsExportsDependency": () =>
		require("../dependencies/commonjs/CommonJsExportsDependency"),
	"dependencies/commonjs/CommonJsFullRequireDependency": () =>
		require("../dependencies/commonjs/CommonJsFullRequireDependency"),
	"dependencies/commonjs/CommonJsObjectExportDependency": () =>
		require("../dependencies/commonjs/CommonJsObjectExportDependency"),
	"dependencies/commonjs/CommonJsRequireContextDependency": () =>
		require("../dependencies/commonjs/CommonJsRequireContextDependency"),
	"dependencies/commonjs/CommonJsRequireDependency": () =>
		require("../dependencies/commonjs/CommonJsRequireDependency"),
	"dependencies/commonjs/CommonJsSelfReferenceDependency": () =>
		require("../dependencies/commonjs/CommonJsSelfReferenceDependency"),
	"dependencies/commonjs/RequireEnsureDependenciesBlock": () =>
		require("../dependencies/commonjs/RequireEnsureDependenciesBlock"),
	"dependencies/commonjs/RequireEnsureDependency": () =>
		require("../dependencies/commonjs/RequireEnsureDependency"),
	"dependencies/commonjs/RequireEnsureItemDependency": () =>
		require("../dependencies/commonjs/RequireEnsureItemDependency"),
	"dependencies/commonjs/RequireHeaderDependency": () =>
		require("../dependencies/commonjs/RequireHeaderDependency"),
	"dependencies/commonjs/RequireIncludeDependency": () =>
		require("../dependencies/commonjs/RequireIncludeDependency"),
	"dependencies/commonjs/RequireIncludeDependencyParserPlugin": () =>
		require("../dependencies/commonjs/RequireIncludeDependencyParserPlugin"),
	"dependencies/commonjs/RequireResolveContextDependency": () =>
		require("../dependencies/commonjs/RequireResolveContextDependency"),
	"dependencies/commonjs/RequireResolveDependency": () =>
		require("../dependencies/commonjs/RequireResolveDependency"),
	"dependencies/commonjs/RequireResolveHeaderDependency": () =>
		require("../dependencies/commonjs/RequireResolveHeaderDependency"),
	"dependencies/context/ContextDependency": () =>
		require("../dependencies/context/ContextDependency"),
	"dependencies/context/ContextElementDependency": () =>
		require("../dependencies/context/ContextElementDependency"),
	"dependencies/context/ImportMetaContextDependency": () =>
		require("../dependencies/context/ImportMetaContextDependency"),
	"dependencies/context/ImportMetaGlobDependency": () =>
		require("../dependencies/context/ImportMetaGlobDependency"),
	"dependencies/context/RequireContextDependency": () =>
		require("../dependencies/context/RequireContextDependency"),
	"dependencies/css/CssIcssExportDependency": () =>
		require("../dependencies/css/CssIcssExportDependency"),
	"dependencies/css/CssIcssImportDependency": () =>
		require("../dependencies/css/CssIcssImportDependency"),
	"dependencies/css/CssIcssSymbolDependency": () =>
		require("../dependencies/css/CssIcssSymbolDependency"),
	"dependencies/css/CssImportDependency": () =>
		require("../dependencies/css/CssImportDependency"),
	"dependencies/css/CssUrlDependency": () =>
		require("../dependencies/css/CssUrlDependency"),
	"dependencies/esm/ESMAcceptDependency": () =>
		require("../dependencies/esm/ESMAcceptDependency"),
	"dependencies/esm/ESMAcceptImportDependency": () =>
		require("../dependencies/esm/ESMAcceptImportDependency"),
	"dependencies/esm/ESMCompatibilityDependency": () =>
		require("../dependencies/esm/ESMCompatibilityDependency"),
	"dependencies/esm/ESMEvaluatedImportSpecifierDependency": () =>
		require("../dependencies/esm/ESMEvaluatedImportSpecifierDependency"),
	"dependencies/esm/ESMExportExpressionDependency": () =>
		require("../dependencies/esm/ESMExportExpressionDependency"),
	"dependencies/esm/ESMExportHeaderDependency": () =>
		require("../dependencies/esm/ESMExportHeaderDependency"),
	"dependencies/esm/ESMExportImportedSpecifierDependency": () =>
		require("../dependencies/esm/ESMExportImportedSpecifierDependency"),
	"dependencies/esm/ESMExportSpecifierDependency": () =>
		require("../dependencies/esm/ESMExportSpecifierDependency"),
	"dependencies/esm/ESMImportBareSideEffectDependency": () =>
		require("../dependencies/esm/ESMImportBareSideEffectDependency"),
	"dependencies/esm/ESMImportSideEffectDependency": () =>
		require("../dependencies/esm/ESMImportSideEffectDependency"),
	"dependencies/esm/ESMImportSpecifierDependency": () =>
		require("../dependencies/esm/ESMImportSpecifierDependency"),
	"dependencies/hmr/ImportMetaHotAcceptDependency": () =>
		require("../dependencies/hmr/ImportMetaHotAcceptDependency"),
	"dependencies/hmr/ImportMetaHotDeclineDependency": () =>
		require("../dependencies/hmr/ImportMetaHotDeclineDependency"),
	"dependencies/hmr/ModuleHotAcceptDependency": () =>
		require("../dependencies/hmr/ModuleHotAcceptDependency"),
	"dependencies/hmr/ModuleHotDeclineDependency": () =>
		require("../dependencies/hmr/ModuleHotDeclineDependency"),
	"dependencies/html/HtmlEntryDependency": () =>
		require("../dependencies/html/HtmlEntryDependency"),
	"dependencies/html/HtmlInlineHtmlDependency": () =>
		require("../dependencies/html/HtmlInlineHtmlDependency"),
	"dependencies/html/HtmlInlineScriptDependency": () =>
		require("../dependencies/html/HtmlInlineScriptDependency"),
	"dependencies/html/HtmlInlineStyleDependency": () =>
		require("../dependencies/html/HtmlInlineStyleDependency"),
	"dependencies/html/HtmlSourceDependency": () =>
		require("../dependencies/html/HtmlSourceDependency"),
	"dependencies/system/SystemPlugin": () =>
		require("../dependencies/system/SystemPlugin"),
	"dependencies/worker/CreateScriptUrlDependency": () =>
		require("../dependencies/worker/CreateScriptUrlDependency"),
	"dependencies/worker/WorkerDependency": () =>
		require("../dependencies/worker/WorkerDependency"),
	"dependencies/worker/WorkletDependency": () =>
		require("../dependencies/worker/WorkletDependency"),
	"dll/DelegatedModule": () => require("../dll/DelegatedModule"),
	"dll/DelegatedSourceDependency": () =>
		require("../dll/DelegatedSourceDependency"),
	"dll/DllEntryDependency": () => require("../dll/DllEntryDependency"),
	"dll/DllModule": () => require("../dll/DllModule"),
	"errors/CommentCompilationWarning": () =>
		require("../errors/CommentCompilationWarning"),
	"errors/CriticalDependencyWarning": () =>
		require("../errors/CriticalDependencyWarning"),
	"errors/EnvironmentNotSupportAsyncWarning": () =>
		require("../errors/EnvironmentNotSupportAsyncWarning"),
	"errors/HookWebpackError": () => require("../errors/HookWebpackError"),
	"errors/ImportedBindingAssignmentError": () =>
		require("../errors/ImportedBindingAssignmentError"),
	"errors/InvalidDependenciesModuleWarning": () =>
		require("../errors/InvalidDependenciesModuleWarning"),
	"errors/JSONParseError": () => require("../errors/JSONParseError"),
	"errors/ModuleBuildError": () => require("../errors/ModuleBuildError"),
	"errors/ModuleDependencyError": () =>
		require("../errors/ModuleDependencyError"),
	"errors/ModuleDependencyWarning": () =>
		require("../errors/ModuleDependencyWarning"),
	"errors/ModuleError": () => require("../errors/ModuleError"),
	"errors/ModuleParseError": () => require("../errors/ModuleParseError"),
	"errors/ModuleWarning": () => require("../errors/ModuleWarning"),
	"errors/NodeStuffInWebError": () => require("../errors/NodeStuffInWebError"),
	"errors/NonErrorEmittedError": () =>
		require("../errors/NonErrorEmittedError"),
	"errors/UnhandledSchemeError": () =>
		require("../errors/UnhandledSchemeError"),
	"errors/UnsupportedFeatureWarning": () =>
		require("../errors/UnsupportedFeatureWarning"),
	"errors/WebpackError": () => require("../errors/WebpackError"),
	"externals/ExternalModule": () => require("../externals/ExternalModule"),
	"fs/FileSystemInfo": () => require("../fs/FileSystemInfo"),
	"graph/AsyncDependenciesBlock": () =>
		require("../graph/AsyncDependenciesBlock"),
	"graph/DependenciesBlock": () => require("../graph/DependenciesBlock"),
	"graph/ModuleGraph": () => require("../graph/ExportsInfo"),
	"html/HtmlModule": () => require("../html/HtmlModule"),
	"javascript/JavascriptModule": () =>
		require("../javascript/JavascriptModule"),
	"json/JsonData": () => require("../json/JsonData"),
	"json/JsonExportsDependency": () => require("../json/JsonExportsDependency"),
	"json/JsonModule": () => require("../json/JsonModule"),
	"module/Module": () => require("../module/Module"),
	"module/NormalModule": () => require("../module/NormalModule"),
	"module/RawModule": () => require("../module/RawModule"),
	"node/ExternalModuleDependency": () =>
		require("../node/ExternalModuleDependency"),
	"node/ExternalModuleInitFragment": () =>
		require("../node/ExternalModuleInitFragment"),
	"node/ExternalModuleInitFragmentDependency": () =>
		require("../node/ExternalModuleInitFragmentDependency"),
	"optimize/ConcatenatedModule": () =>
		require("../optimize/ConcatenatedModule"),
	"optimize/InlineExports": () => require("../optimize/InlineExports"),
	"sharing/ConsumeSharedFallbackDependency": () =>
		require("../sharing/ConsumeSharedFallbackDependency"),
	"sharing/ConsumeSharedModule": () =>
		require("../sharing/ConsumeSharedModule"),
	"sharing/ProvideForSharedDependency": () =>
		require("../sharing/ProvideForSharedDependency"),
	"sharing/ProvideSharedDependency": () =>
		require("../sharing/ProvideSharedDependency"),
	"sharing/ProvideSharedModule": () =>
		require("../sharing/ProvideSharedModule"),
	"template/InitFragment": () => require("../template/InitFragment"),
	"util/LazySet": () => require("../util/LazySet"),
	"util/registerExternalSerializer": () => {
		// already registered
	},
	"wasm-async/AsyncWasmModule": () => require("../wasm/AsyncWasmModule"),
	"wasm-sync/SyncWasmModule": () => require("../wasm-sync/SyncWasmModule"),
	"wasm/AsyncWasmModule": () => require("../wasm/AsyncWasmModule"),
	AsyncDependenciesBlock: () => require("../graph/AsyncDependenciesBlock"),
	ContextModule: () => require("../context/ContextModule"),
	CssModule: () => require("../css/CssModule"),
	DependenciesBlock: () => require("../graph/DependenciesBlock"),
	ExternalModule: () => require("../externals/ExternalModule"),
	FileSystemInfo: () => require("../fs/FileSystemInfo"),
	InitFragment: () => require("../template/InitFragment"),
	Module: () => require("../module/Module"),
	ModuleGraph: () => require("../graph/ExportsInfo"),
	NodeStuffInWebError: () => require("../errors/NodeStuffInWebError"),
	NormalModule: () => require("../module/NormalModule"),
	RawDataUrlModule: () => require("../asset/RawDataUrlModule"),
	RawModule: () => require("../module/RawModule")
};
