"use strict";

module.exports = [
	{ message: /Selector ":global\(\.foo\)" is not pure/ },
	{ message: /Selector "\.foo, :global\(\.bar\)" is not pure/ },
	{ message: /Selector ":global\(\.bar\), \.foo" is not pure/ },
	{ message: /Selector "input" is not pure/ },
	{ message: /Selector "\[type="radio"\]" is not pure/ },
	{ message: /Selector "@keyframes :global\(foo\)" is not pure/ },
	{ message: /Selector "&:hover" is not pure/ },
	{ message: /Selector ":global\(\.bar\)" is not pure/ },
	{ message: /Selector ":global\(\.bar\)" is not pure/ },
	{ message: /Selector ":global\(\.foo\)" is not pure/ },
	{ message: /Selector ":global\(\.bar\)" is not pure/ },
	{ message: /Selector ":global\(\.baz\)" is not pure/ },
	{ message: /Selector "&:hover" is not pure/ },
	{ message: /Selector "& :global\(\.bar\)" is not pure/ },
	{ message: /Selector ":global\(\.bar\)" is not pure/ },
	{ message: /Selector ":global\(\.foo\)" is not pure/ },
	{ message: /Selector ":global\(\.foo\)" is not pure/ },
	{ message: /Selector ":global\(\.foo\)" is not pure/ },
	{ message: /Selector ":global\(\.bar\)" is not pure/ },
	{ message: /Selector "&::-webkit-scrollbar" is not pure/ },
	{ message: /Selector "@keyframes :global\(fadeIn\)" is not pure/ },
	{ message: /Selector ":global\(\.animate\)" is not pure/ },
	{ message: /Selector ":global\(\.foo\)" is not pure/ },
	{ message: /Selector ":global\(\.foo\)" is not pure/ },
	{ message: /Selector ":global\(\.foo\)" is not pure/ },
	{ message: /Selector "span" is not pure/ },
	{ message: /Selector "& > span" is not pure/ },
	{ message: /Selector "& > span" is not pure/ },
	{ message: /Selector "& > span" is not pure/ },
	{ message: /Selector "&" is not pure/ },
	{ message: /Selector "div" is not pure/ },
	{ message: /Selector "div" is not pure/ },
	{ message: /Selector "div" is not pure/ },
	{ message: /Selector "div" is not pure/ },
	{ message: /Selector "div" is not pure/ },
	{ message: /Selector "div" is not pure/ },
	{ message: /Selector "div" is not pure/ },
	{ message: /Selector "div" is not pure/ },
	{ message: /Selector "div" is not pure/ },
	{ message: /Selector "html" is not pure/ },
	{ message: /Selector "html" is not pure/ },
	{ message: /Selector "button" is not pure/ },
	{ message: /Selector "button" is not pure/ }
];
