/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author sheo13666q @sheo13666q
*/

// GENERATED by tooling/generate-css-data.js — do not edit.
// Sources: mdn-data 2.29.0, color-name 1.1.4.

"use strict";

// Properties whose value is CSS's `{1,4}` box notation, where an omitted value
// is copied from the opposite side. That makes a repeated value redundant:
// `margin:1px 1px 1px 1px` is `margin:1px`. `border-radius` collapses each side
// of its `/` independently.
const BOX_SHORTHANDS = new Set([
	"border-color",
	"border-image-outset",
	"border-image-width",
	"border-radius",
	"border-style",
	"border-width",
	"corner-shape",
	"inset",
	"margin",
	"mask-border-outset",
	"mask-border-width",
	"padding",
	"scroll-margin",
	"scroll-padding"
]);

// The subset carrying a second box after a `/`, which collapses on its own.
const SLASH_BOX_SHORTHANDS = new Set(["border-radius"]);

// The four longhands each box shorthand sets, in `top right bottom left` order.
// Only the families whose longhands are the four sides: merging those into the
// shorthand sets exactly the same properties, resetting nothing extra. Corner
// families (`border-radius`) are absent — `{1,4}` orders their longhands
// differently.
// prettier-ignore
const BOX_LONGHANDS = new Map([
	["border-color", ["border-top-color", "border-right-color", "border-bottom-color", "border-left-color"]],
	["border-style", ["border-top-style", "border-right-style", "border-bottom-style", "border-left-style"]],
	["border-width", ["border-top-width", "border-right-width", "border-bottom-width", "border-left-width"]],
	["inset", ["top", "right", "bottom", "left"]],
	["margin", ["margin-top", "margin-right", "margin-bottom", "margin-left"]],
	["padding", ["padding-top", "padding-right", "padding-bottom", "padding-left"]],
	["scroll-margin", ["scroll-margin-top", "scroll-margin-right", "scroll-margin-bottom", "scroll-margin-left"]],
	["scroll-padding", ["scroll-padding-top", "scroll-padding-right", "scroll-padding-bottom", "scroll-padding-left"]]
]);

// The name prefix a declaration between two box longhands must not carry for the
// merge to step over it. The shorthand's first segment, which is deliberately
// wider than the family: `border-color` blocks every `border*` property, since
// `border`, `border-top` and `border-block-start-color` all write its longhands
// and `mdn-data`'s `computed` lists only some of them.
const BOX_FAMILY_PREFIX = new Map([
	["border-color", "border"],
	["border-style", "border"],
	["border-width", "border"],
	["inset", "inset"],
	["margin", "margin"],
	["padding", "padding"],
	["scroll-margin", "scroll"],
	["scroll-padding", "scroll"]
]);

// Functions that take a `<color>` directly, so a hash among their arguments is a
// hex color rather than a case-sensitive reference (`element(#id)`). Only direct
// arguments: a gradient nested in `image-set()` is matched as the gradient.
const COLOR_ARGUMENT_FUNCTIONS = new Set([
	"color",
	"color-mix",
	"conic-gradient",
	"cross-fade",
	"drop-shadow",
	"image",
	"light-dark",
	"linear-gradient",
	"radial-gradient",
	"repeating-conic-gradient",
	"repeating-linear-gradient",
	"repeating-radial-gradient"
]);

// Functions that substitute an arbitrary token sequence, so two identical
// references need not be one repeated value: with `--x:1px 2px`,
// `margin:var(--x) var(--x)` is four values, not two.
const SUBSTITUTION_FUNCTIONS = new Set([
	"attr",
	"env",
	"first-valid",
	"if",
	"inherit",
	"paint",
	"random-item",
	"var"
]);

// CSS Values 4's math functions: everything inside one is a math expression, so
// `*` and `/` there are operators, and the whitespace around them carries nothing.
const MATH_FUNCTIONS = new Set([
	"abs",
	"acos",
	"asin",
	"atan",
	"atan2",
	"calc",
	"calc-size",
	"clamp",
	"cos",
	"exp",
	"hypot",
	"log",
	"max",
	"min",
	"mod",
	"pow",
	"rem",
	"round",
	"sign",
	"sin",
	"sqrt",
	"tan"
]);

// A CSS-wide keyword is only valid as the whole value, so a box repeating one is
// invalid and already discarded — collapsing it would switch the declaration on.
const CSS_WIDE_KEYWORDS = new Set([
	"inherit",
	"initial",
	"revert",
	"revert-layer",
	"unset"
]);

// `<easing-function>` argument lists that are exactly a shorter keyword, keyed
// by the arguments as `Number` prints them.
const CUBIC_BEZIER_KEYWORDS = new Map([
	["0.25,0.1,0.25,1", "ease"],
	["0,0,1,1", "linear"],
	["0.42,0,1,1", "ease-in"],
	["0,0,0.58,1", "ease-out"],
	["0.42,0,0.58,1", "ease-in-out"]
]);

// The two `flex` values CSS Flexbox 7.1.1 gives a keyword spelling.
const FLEX_KEYWORDS = new Map([
	["0 0 auto", "none"],
	["1 1 auto", "auto"]
]);

// The `font-weight` keywords CSS Fonts 4 §2.2 defines as a number, which is what
// `getComputedStyle().fontWeight` reports either way.
const FONT_WEIGHT_NUMBERS = new Map([
	["normal", "400"],
	["bold", "700"]
]);

// Selectors 4 §3.3: the pseudo-elements engines must also accept with one colon,
// so their second colon carries nothing.
const LEGACY_PSEUDO_ELEMENTS = new Set([
	"before",
	"after",
	"first-line",
	"first-letter"
]);

// What may follow the `*` a compound selector implies: another simple selector
// in the same compound. A separator between them would be a descendant
// combinator instead, and `|` makes the `*` a namespace's, not a redundant one.
const COMPOUND_CONTINUATIONS = new Set([":", ".", "#", "["]);

// The properties whose zero length keeps its unit — the one place it is still
// load-bearing.
const ZERO_UNIT_KEEPING_PROPERTIES = new Set(["flex", "flex-basis"]);

// At-rules whose empty block is inert, so dropping it changes nothing.
const DROPPABLE_WHEN_EMPTY_AT_RULES = new Set([
	"media",
	"supports",
	"container"
]);

// The units fixed against each other (CSS Values 4 §6.2, §8), as
// `unit -> [group, how many of the group's base unit one is]`. Two units in the
// same group convert into each other exactly when the ratio is binary-exact.
/** @type {Map<string, [string, number]>} */
const ABSOLUTE_UNIT_SCALE = new Map([
	["px", ["length", 381]],
	["pc", ["length", 6096]],
	["pt", ["length", 508]],
	["in", ["length", 36576]],
	["cm", ["length", 14400]],
	["mm", ["length", 1440]],
	["q", ["length", 360]],
	["ms", ["time", 1]],
	["s", ["time", 1000]]
]);

// The units a conversion may emit. Every one is CSS 2.1's, so rewriting into it
// cannot outrun what an engine reading the stylesheet already parses.
const UNIT_CONVERSION_TARGETS = new Set([
	"px",
	"pc",
	"pt",
	"in",
	"cm",
	"mm",
	"ms",
	"s"
]);

// The angle units. Excluded from rounding: `rotate()` runs its argument through
// trig, which turns a truncated digit into a different computed matrix.
const ANGLE_UNITS = new Set(["deg", "grad", "rad", "turn"]);

// Shorthand -> every longhand it writes, the relation followed all the way down
// (`border` reaches `border-top-color` only through `border-color`). `all` is
// absent: it writes every property there is.
const PROPERTY_LONGHANDS = new Map([
	[
		"-moz-outline-radius",
		[
			"-moz-outline-radius-bottomleft",
			"-moz-outline-radius-bottomright",
			"-moz-outline-radius-topleft",
			"-moz-outline-radius-topright"
		]
	],
	[
		"-ms-content-zoom-limit",
		["-ms-content-zoom-limit-max", "-ms-content-zoom-limit-min"]
	],
	[
		"-ms-content-zoom-snap",
		["-ms-content-zoom-snap-points", "-ms-content-zoom-snap-type"]
	],
	[
		"-ms-scroll-limit",
		[
			"-ms-scroll-limit-x-max",
			"-ms-scroll-limit-x-min",
			"-ms-scroll-limit-y-max",
			"-ms-scroll-limit-y-min"
		]
	],
	["-ms-scroll-snap-x", ["-ms-scroll-snap-points-x", "-ms-scroll-snap-type"]],
	["-ms-scroll-snap-y", ["-ms-scroll-snap-points-y", "-ms-scroll-snap-type"]],
	[
		"-webkit-border-after",
		[
			"border-block-end-color",
			"border-block-end-style",
			"border-block-end-width"
		]
	],
	[
		"-webkit-border-before",
		[
			"border-block-start-color",
			"border-block-start-style",
			"border-block-start-width"
		]
	],
	[
		"-webkit-border-end",
		[
			"border-inline-end-color",
			"border-inline-end-style",
			"border-inline-end-width"
		]
	],
	[
		"-webkit-border-start",
		[
			"border-inline-start-color",
			"border-inline-start-style",
			"border-inline-start-width"
		]
	],
	[
		"-webkit-mask",
		[
			"-webkit-mask-attachment",
			"-webkit-mask-clip",
			"-webkit-mask-image",
			"-webkit-mask-origin",
			"-webkit-mask-position",
			"-webkit-mask-repeat"
		]
	],
	[
		"-webkit-text-stroke",
		["-webkit-text-stroke-color", "-webkit-text-stroke-width"]
	],
	[
		"animation",
		[
			"animation-delay",
			"animation-direction",
			"animation-duration",
			"animation-fill-mode",
			"animation-iteration-count",
			"animation-name",
			"animation-play-state",
			"animation-timeline",
			"animation-timing-function"
		]
	],
	["animation-range", ["animation-range-end", "animation-range-start"]],
	[
		"background",
		[
			"background-attachment",
			"background-clip",
			"background-color",
			"background-image",
			"background-origin",
			"background-position-x",
			"background-position-y",
			"background-repeat",
			"background-size"
		]
	],
	["background-position", ["background-position-x", "background-position-y"]],
	[
		"border",
		[
			"border-bottom-color",
			"border-bottom-style",
			"border-bottom-width",
			"border-left-color",
			"border-left-style",
			"border-left-width",
			"border-right-color",
			"border-right-style",
			"border-right-width",
			"border-top-color",
			"border-top-style",
			"border-top-width"
		]
	],
	[
		"border-block",
		[
			"border-block-end-color",
			"border-block-end-style",
			"border-block-end-width",
			"border-block-start-color",
			"border-block-start-style",
			"border-block-start-width"
		]
	],
	[
		"border-block-color",
		["border-block-end-color", "border-block-start-color"]
	],
	[
		"border-block-end",
		[
			"border-block-end-color",
			"border-block-end-style",
			"border-block-end-width"
		]
	],
	[
		"border-block-start",
		[
			"border-block-start-color",
			"border-block-start-style",
			"border-block-start-width"
		]
	],
	[
		"border-block-style",
		["border-block-end-style", "border-block-start-style"]
	],
	[
		"border-block-width",
		["border-block-end-width", "border-block-start-width"]
	],
	[
		"border-bottom",
		["border-bottom-color", "border-bottom-style", "border-bottom-width"]
	],
	[
		"border-color",
		[
			"border-bottom-color",
			"border-left-color",
			"border-right-color",
			"border-top-color"
		]
	],
	[
		"border-image",
		[
			"border-image-outset",
			"border-image-repeat",
			"border-image-slice",
			"border-image-source",
			"border-image-width"
		]
	],
	[
		"border-inline",
		[
			"border-inline-end-color",
			"border-inline-end-style",
			"border-inline-end-width",
			"border-inline-start-color",
			"border-inline-start-style",
			"border-inline-start-width"
		]
	],
	[
		"border-inline-color",
		["border-inline-end-color", "border-inline-start-color"]
	],
	[
		"border-inline-end",
		[
			"border-inline-end-color",
			"border-inline-end-style",
			"border-inline-end-width"
		]
	],
	[
		"border-inline-start",
		[
			"border-inline-start-color",
			"border-inline-start-style",
			"border-inline-start-width"
		]
	],
	[
		"border-inline-style",
		["border-inline-end-style", "border-inline-start-style"]
	],
	[
		"border-inline-width",
		["border-inline-end-width", "border-inline-start-width"]
	],
	[
		"border-left",
		["border-left-color", "border-left-style", "border-left-width"]
	],
	[
		"border-radius",
		[
			"border-bottom-left-radius",
			"border-bottom-right-radius",
			"border-top-left-radius",
			"border-top-right-radius"
		]
	],
	[
		"border-right",
		["border-right-color", "border-right-style", "border-right-width"]
	],
	[
		"border-style",
		[
			"border-bottom-style",
			"border-left-style",
			"border-right-style",
			"border-top-style"
		]
	],
	["border-top", ["border-top-color", "border-top-style", "border-top-width"]],
	[
		"border-width",
		[
			"border-bottom-width",
			"border-left-width",
			"border-right-width",
			"border-top-width"
		]
	],
	["caret", ["caret-animation", "caret-color", "caret-shape"]],
	[
		"column-rule",
		["column-rule-color", "column-rule-style", "column-rule-width"]
	],
	["columns", ["column-count", "column-height", "column-width"]],
	[
		"contain-intrinsic-size",
		["contain-intrinsic-height", "contain-intrinsic-width"]
	],
	["container", ["container-name", "container-type"]],
	[
		"corner-block-end-shape",
		["corner-end-end-shape", "corner-end-start-shape"]
	],
	[
		"corner-block-start-shape",
		["corner-start-end-shape", "corner-start-start-shape"]
	],
	[
		"corner-bottom-shape",
		["corner-bottom-left-shape", "corner-bottom-right-shape"]
	],
	[
		"corner-inline-end-shape",
		["corner-end-end-shape", "corner-start-end-shape"]
	],
	[
		"corner-inline-start-shape",
		["corner-start-end-shape", "corner-start-start-shape"]
	],
	["corner-left-shape", ["corner-bottom-left-shape", "corner-top-left-shape"]],
	[
		"corner-right-shape",
		["corner-bottom-right-shape", "corner-top-right-shape"]
	],
	[
		"corner-shape",
		[
			"corner-bottom-left-shape",
			"corner-bottom-right-shape",
			"corner-top-left-shape",
			"corner-top-right-shape"
		]
	],
	["corner-top-shape", ["corner-top-left-shape", "corner-top-right-shape"]],
	["flex", ["flex-basis", "flex-grow", "flex-shrink"]],
	["flex-flow", ["flex-direction", "flex-wrap"]],
	[
		"font",
		[
			"font-family",
			"font-size",
			"font-stretch",
			"font-style",
			"font-variant",
			"font-weight",
			"line-height"
		]
	],
	["gap", ["column-gap", "row-gap"]],
	[
		"grid",
		[
			"column-gap",
			"grid-auto-columns",
			"grid-auto-flow",
			"grid-auto-rows",
			"grid-column-gap",
			"grid-row-gap",
			"grid-template-areas",
			"grid-template-columns",
			"grid-template-rows",
			"row-gap"
		]
	],
	[
		"grid-area",
		["grid-column-end", "grid-column-start", "grid-row-end", "grid-row-start"]
	],
	["grid-column", ["grid-column-end", "grid-column-start"]],
	["grid-gap", ["grid-column-gap", "grid-row-gap"]],
	["grid-row", ["grid-row-end", "grid-row-start"]],
	[
		"grid-template",
		["grid-template-areas", "grid-template-columns", "grid-template-rows"]
	],
	["inset", ["bottom", "left", "right", "top"]],
	["inset-block", ["inset-block-end", "inset-block-start"]],
	["inset-inline", ["inset-inline-end", "inset-inline-start"]],
	["interest-delay", ["interest-delay-end", "interest-delay-start"]],
	[
		"list-style",
		["list-style-image", "list-style-position", "list-style-type"]
	],
	["margin", ["margin-bottom", "margin-left", "margin-right", "margin-top"]],
	["margin-block", ["margin-block-end", "margin-block-start"]],
	["margin-inline", ["margin-inline-end", "margin-inline-start"]],
	[
		"mask",
		[
			"mask-clip",
			"mask-composite",
			"mask-image",
			"mask-mode",
			"mask-origin",
			"mask-position",
			"mask-repeat",
			"mask-size"
		]
	],
	[
		"mask-border",
		[
			"mask-border-mode",
			"mask-border-outset",
			"mask-border-repeat",
			"mask-border-slice",
			"mask-border-source",
			"mask-border-width"
		]
	],
	[
		"offset",
		[
			"offset-anchor",
			"offset-distance",
			"offset-path",
			"offset-position",
			"offset-rotate"
		]
	],
	["outline", ["outline-color", "outline-style", "outline-width"]],
	["overflow", ["overflow-x", "overflow-y"]],
	["overscroll-behavior", ["overscroll-behavior-x", "overscroll-behavior-y"]],
	[
		"padding",
		["padding-bottom", "padding-left", "padding-right", "padding-top"]
	],
	["padding-block", ["padding-block-end", "padding-block-start"]],
	["padding-inline", ["padding-inline-end", "padding-inline-start"]],
	["place-content", ["align-content", "justify-content"]],
	["place-items", ["align-items", "justify-items"]],
	["place-self", ["align-self", "justify-self"]],
	["position-try", ["position-try-fallbacks", "position-try-order"]],
	[
		"scroll-margin",
		[
			"scroll-margin-bottom",
			"scroll-margin-left",
			"scroll-margin-right",
			"scroll-margin-top"
		]
	],
	[
		"scroll-margin-block",
		["scroll-margin-block-end", "scroll-margin-block-start"]
	],
	[
		"scroll-margin-inline",
		["scroll-margin-inline-end", "scroll-margin-inline-start"]
	],
	[
		"scroll-padding",
		[
			"scroll-padding-bottom",
			"scroll-padding-left",
			"scroll-padding-right",
			"scroll-padding-top"
		]
	],
	[
		"scroll-padding-block",
		["scroll-padding-block-end", "scroll-padding-block-start"]
	],
	[
		"scroll-padding-inline",
		["scroll-padding-inline-end", "scroll-padding-inline-start"]
	],
	["scroll-timeline", ["scroll-timeline-axis", "scroll-timeline-name"]],
	[
		"text-decoration",
		[
			"text-decoration-color",
			"text-decoration-line",
			"text-decoration-style",
			"text-decoration-thickness"
		]
	],
	["text-emphasis", ["text-emphasis-color", "text-emphasis-style"]],
	["text-wrap", ["text-wrap-mode", "text-wrap-style"]],
	[
		"timeline-trigger",
		[
			"timeline-trigger-activation-range-end",
			"timeline-trigger-activation-range-start",
			"timeline-trigger-active-range-end",
			"timeline-trigger-active-range-start",
			"timeline-trigger-name",
			"timeline-trigger-source"
		]
	],
	[
		"timeline-trigger-activation-range",
		[
			"timeline-trigger-activation-range-end",
			"timeline-trigger-activation-range-start"
		]
	],
	[
		"timeline-trigger-active-range",
		["timeline-trigger-active-range-end", "timeline-trigger-active-range-start"]
	],
	[
		"transition",
		[
			"transition-behavior",
			"transition-delay",
			"transition-duration",
			"transition-property",
			"transition-timing-function"
		]
	],
	["view-timeline", ["view-timeline-axis", "view-timeline-name"]]
]);

// The inverse: longhand -> every shorthand that can write it. What a cascade
// question asks, so it is the direction stored rather than inverted on use.
const PROPERTY_WRITERS = new Map([
	["-moz-outline-radius-bottomleft", ["-moz-outline-radius"]],
	["-moz-outline-radius-bottomright", ["-moz-outline-radius"]],
	["-moz-outline-radius-topleft", ["-moz-outline-radius"]],
	["-moz-outline-radius-topright", ["-moz-outline-radius"]],
	["-ms-content-zoom-limit-max", ["-ms-content-zoom-limit"]],
	["-ms-content-zoom-limit-min", ["-ms-content-zoom-limit"]],
	["-ms-content-zoom-snap-points", ["-ms-content-zoom-snap"]],
	["-ms-content-zoom-snap-type", ["-ms-content-zoom-snap"]],
	["-ms-scroll-limit-x-max", ["-ms-scroll-limit"]],
	["-ms-scroll-limit-x-min", ["-ms-scroll-limit"]],
	["-ms-scroll-limit-y-max", ["-ms-scroll-limit"]],
	["-ms-scroll-limit-y-min", ["-ms-scroll-limit"]],
	["-ms-scroll-snap-points-x", ["-ms-scroll-snap-x"]],
	["-ms-scroll-snap-points-y", ["-ms-scroll-snap-y"]],
	["-ms-scroll-snap-type", ["-ms-scroll-snap-x", "-ms-scroll-snap-y"]],
	["-webkit-mask-attachment", ["-webkit-mask"]],
	["-webkit-mask-clip", ["-webkit-mask"]],
	["-webkit-mask-image", ["-webkit-mask"]],
	["-webkit-mask-origin", ["-webkit-mask"]],
	["-webkit-mask-position", ["-webkit-mask"]],
	["-webkit-mask-repeat", ["-webkit-mask"]],
	["-webkit-text-stroke-color", ["-webkit-text-stroke"]],
	["-webkit-text-stroke-width", ["-webkit-text-stroke"]],
	["align-content", ["place-content"]],
	["align-items", ["place-items"]],
	["align-self", ["place-self"]],
	["animation-delay", ["animation"]],
	["animation-direction", ["animation"]],
	["animation-duration", ["animation"]],
	["animation-fill-mode", ["animation"]],
	["animation-iteration-count", ["animation"]],
	["animation-name", ["animation"]],
	["animation-play-state", ["animation"]],
	["animation-range-end", ["animation-range"]],
	["animation-range-start", ["animation-range"]],
	["animation-timeline", ["animation"]],
	["animation-timing-function", ["animation"]],
	["background-attachment", ["background"]],
	["background-clip", ["background"]],
	["background-color", ["background"]],
	["background-image", ["background"]],
	["background-origin", ["background"]],
	["background-position-x", ["background", "background-position"]],
	["background-position-y", ["background", "background-position"]],
	["background-repeat", ["background"]],
	["background-size", ["background"]],
	[
		"border-block-end-color",
		[
			"-webkit-border-after",
			"border-block",
			"border-block-color",
			"border-block-end"
		]
	],
	[
		"border-block-end-style",
		[
			"-webkit-border-after",
			"border-block",
			"border-block-end",
			"border-block-style"
		]
	],
	[
		"border-block-end-width",
		[
			"-webkit-border-after",
			"border-block",
			"border-block-end",
			"border-block-width"
		]
	],
	[
		"border-block-start-color",
		[
			"-webkit-border-before",
			"border-block",
			"border-block-color",
			"border-block-start"
		]
	],
	[
		"border-block-start-style",
		[
			"-webkit-border-before",
			"border-block",
			"border-block-start",
			"border-block-style"
		]
	],
	[
		"border-block-start-width",
		[
			"-webkit-border-before",
			"border-block",
			"border-block-start",
			"border-block-width"
		]
	],
	["border-bottom-color", ["border", "border-bottom", "border-color"]],
	["border-bottom-left-radius", ["border-radius"]],
	["border-bottom-right-radius", ["border-radius"]],
	["border-bottom-style", ["border", "border-bottom", "border-style"]],
	["border-bottom-width", ["border", "border-bottom", "border-width"]],
	["border-image-outset", ["border-image"]],
	["border-image-repeat", ["border-image"]],
	["border-image-slice", ["border-image"]],
	["border-image-source", ["border-image"]],
	["border-image-width", ["border-image"]],
	[
		"border-inline-end-color",
		[
			"-webkit-border-end",
			"border-inline",
			"border-inline-color",
			"border-inline-end"
		]
	],
	[
		"border-inline-end-style",
		[
			"-webkit-border-end",
			"border-inline",
			"border-inline-end",
			"border-inline-style"
		]
	],
	[
		"border-inline-end-width",
		[
			"-webkit-border-end",
			"border-inline",
			"border-inline-end",
			"border-inline-width"
		]
	],
	[
		"border-inline-start-color",
		[
			"-webkit-border-start",
			"border-inline",
			"border-inline-color",
			"border-inline-start"
		]
	],
	[
		"border-inline-start-style",
		[
			"-webkit-border-start",
			"border-inline",
			"border-inline-start",
			"border-inline-style"
		]
	],
	[
		"border-inline-start-width",
		[
			"-webkit-border-start",
			"border-inline",
			"border-inline-start",
			"border-inline-width"
		]
	],
	["border-left-color", ["border", "border-color", "border-left"]],
	["border-left-style", ["border", "border-left", "border-style"]],
	["border-left-width", ["border", "border-left", "border-width"]],
	["border-right-color", ["border", "border-color", "border-right"]],
	["border-right-style", ["border", "border-right", "border-style"]],
	["border-right-width", ["border", "border-right", "border-width"]],
	["border-top-color", ["border", "border-color", "border-top"]],
	["border-top-left-radius", ["border-radius"]],
	["border-top-right-radius", ["border-radius"]],
	["border-top-style", ["border", "border-style", "border-top"]],
	["border-top-width", ["border", "border-top", "border-width"]],
	["bottom", ["inset"]],
	["caret-animation", ["caret"]],
	["caret-color", ["caret"]],
	["caret-shape", ["caret"]],
	["column-count", ["columns"]],
	["column-gap", ["gap", "grid"]],
	["column-height", ["columns"]],
	["column-rule-color", ["column-rule"]],
	["column-rule-style", ["column-rule"]],
	["column-rule-width", ["column-rule"]],
	["column-width", ["columns"]],
	["contain-intrinsic-height", ["contain-intrinsic-size"]],
	["contain-intrinsic-width", ["contain-intrinsic-size"]],
	["container-name", ["container"]],
	["container-type", ["container"]],
	[
		"corner-bottom-left-shape",
		["corner-bottom-shape", "corner-left-shape", "corner-shape"]
	],
	[
		"corner-bottom-right-shape",
		["corner-bottom-shape", "corner-right-shape", "corner-shape"]
	],
	[
		"corner-end-end-shape",
		["corner-block-end-shape", "corner-inline-end-shape"]
	],
	["corner-end-start-shape", ["corner-block-end-shape"]],
	[
		"corner-start-end-shape",
		[
			"corner-block-start-shape",
			"corner-inline-end-shape",
			"corner-inline-start-shape"
		]
	],
	[
		"corner-start-start-shape",
		["corner-block-start-shape", "corner-inline-start-shape"]
	],
	[
		"corner-top-left-shape",
		["corner-left-shape", "corner-shape", "corner-top-shape"]
	],
	[
		"corner-top-right-shape",
		["corner-right-shape", "corner-shape", "corner-top-shape"]
	],
	["flex-basis", ["flex"]],
	["flex-direction", ["flex-flow"]],
	["flex-grow", ["flex"]],
	["flex-shrink", ["flex"]],
	["flex-wrap", ["flex-flow"]],
	["font-family", ["font"]],
	["font-size", ["font"]],
	["font-stretch", ["font"]],
	["font-style", ["font"]],
	["font-variant", ["font"]],
	["font-weight", ["font"]],
	["grid-auto-columns", ["grid"]],
	["grid-auto-flow", ["grid"]],
	["grid-auto-rows", ["grid"]],
	["grid-column-end", ["grid-area", "grid-column"]],
	["grid-column-gap", ["grid", "grid-gap"]],
	["grid-column-start", ["grid-area", "grid-column"]],
	["grid-row-end", ["grid-area", "grid-row"]],
	["grid-row-gap", ["grid", "grid-gap"]],
	["grid-row-start", ["grid-area", "grid-row"]],
	["grid-template-areas", ["grid", "grid-template"]],
	["grid-template-columns", ["grid", "grid-template"]],
	["grid-template-rows", ["grid", "grid-template"]],
	["inset-block-end", ["inset-block"]],
	["inset-block-start", ["inset-block"]],
	["inset-inline-end", ["inset-inline"]],
	["inset-inline-start", ["inset-inline"]],
	["interest-delay-end", ["interest-delay"]],
	["interest-delay-start", ["interest-delay"]],
	["justify-content", ["place-content"]],
	["justify-items", ["place-items"]],
	["justify-self", ["place-self"]],
	["left", ["inset"]],
	["line-height", ["font"]],
	["list-style-image", ["list-style"]],
	["list-style-position", ["list-style"]],
	["list-style-type", ["list-style"]],
	["margin-block-end", ["margin-block"]],
	["margin-block-start", ["margin-block"]],
	["margin-bottom", ["margin"]],
	["margin-inline-end", ["margin-inline"]],
	["margin-inline-start", ["margin-inline"]],
	["margin-left", ["margin"]],
	["margin-right", ["margin"]],
	["margin-top", ["margin"]],
	["mask-border-mode", ["mask-border"]],
	["mask-border-outset", ["mask-border"]],
	["mask-border-repeat", ["mask-border"]],
	["mask-border-slice", ["mask-border"]],
	["mask-border-source", ["mask-border"]],
	["mask-border-width", ["mask-border"]],
	["mask-clip", ["mask"]],
	["mask-composite", ["mask"]],
	["mask-image", ["mask"]],
	["mask-mode", ["mask"]],
	["mask-origin", ["mask"]],
	["mask-position", ["mask"]],
	["mask-repeat", ["mask"]],
	["mask-size", ["mask"]],
	["offset-anchor", ["offset"]],
	["offset-distance", ["offset"]],
	["offset-path", ["offset"]],
	["offset-position", ["offset"]],
	["offset-rotate", ["offset"]],
	["outline-color", ["outline"]],
	["outline-style", ["outline"]],
	["outline-width", ["outline"]],
	["overflow-x", ["overflow"]],
	["overflow-y", ["overflow"]],
	["overscroll-behavior-x", ["overscroll-behavior"]],
	["overscroll-behavior-y", ["overscroll-behavior"]],
	["padding-block-end", ["padding-block"]],
	["padding-block-start", ["padding-block"]],
	["padding-bottom", ["padding"]],
	["padding-inline-end", ["padding-inline"]],
	["padding-inline-start", ["padding-inline"]],
	["padding-left", ["padding"]],
	["padding-right", ["padding"]],
	["padding-top", ["padding"]],
	["position-try-fallbacks", ["position-try"]],
	["position-try-order", ["position-try"]],
	["right", ["inset"]],
	["row-gap", ["gap", "grid"]],
	["scroll-margin-block-end", ["scroll-margin-block"]],
	["scroll-margin-block-start", ["scroll-margin-block"]],
	["scroll-margin-bottom", ["scroll-margin"]],
	["scroll-margin-inline-end", ["scroll-margin-inline"]],
	["scroll-margin-inline-start", ["scroll-margin-inline"]],
	["scroll-margin-left", ["scroll-margin"]],
	["scroll-margin-right", ["scroll-margin"]],
	["scroll-margin-top", ["scroll-margin"]],
	["scroll-padding-block-end", ["scroll-padding-block"]],
	["scroll-padding-block-start", ["scroll-padding-block"]],
	["scroll-padding-bottom", ["scroll-padding"]],
	["scroll-padding-inline-end", ["scroll-padding-inline"]],
	["scroll-padding-inline-start", ["scroll-padding-inline"]],
	["scroll-padding-left", ["scroll-padding"]],
	["scroll-padding-right", ["scroll-padding"]],
	["scroll-padding-top", ["scroll-padding"]],
	["scroll-timeline-axis", ["scroll-timeline"]],
	["scroll-timeline-name", ["scroll-timeline"]],
	["text-decoration-color", ["text-decoration"]],
	["text-decoration-line", ["text-decoration"]],
	["text-decoration-style", ["text-decoration"]],
	["text-decoration-thickness", ["text-decoration"]],
	["text-emphasis-color", ["text-emphasis"]],
	["text-emphasis-style", ["text-emphasis"]],
	["text-wrap-mode", ["text-wrap"]],
	["text-wrap-style", ["text-wrap"]],
	[
		"timeline-trigger-activation-range-end",
		["timeline-trigger", "timeline-trigger-activation-range"]
	],
	[
		"timeline-trigger-activation-range-start",
		["timeline-trigger", "timeline-trigger-activation-range"]
	],
	[
		"timeline-trigger-active-range-end",
		["timeline-trigger", "timeline-trigger-active-range"]
	],
	[
		"timeline-trigger-active-range-start",
		["timeline-trigger", "timeline-trigger-active-range"]
	],
	["timeline-trigger-name", ["timeline-trigger"]],
	["timeline-trigger-source", ["timeline-trigger"]],
	["top", ["inset"]],
	["transition-behavior", ["transition"]],
	["transition-delay", ["transition"]],
	["transition-duration", ["transition"]],
	["transition-property", ["transition"]],
	["transition-timing-function", ["transition"]],
	["view-timeline-axis", ["view-timeline"]],
	["view-timeline-name", ["view-timeline"]]
]);

// Properties whose grammar can reach an `<integer>`. Deliberately wide: a
// non-integer where an integer is expected is rounded rather than dropped
// (`z-index: calc(1.5)` computes to `2`), so this is read to refuse a rewrite,
// and one name too many costs only that rewrite.
const INTEGER_PROPERTIES = new Set([
	"-ms-grid-columns",
	"-ms-grid-rows",
	"-ms-hyphenate-limit-chars",
	"-ms-hyphenate-limit-lines",
	"-webkit-line-clamp",
	"animation",
	"animation-timing-function",
	"box-flex-group",
	"box-ordinal-group",
	"column-count",
	"counter-increment",
	"counter-reset",
	"counter-set",
	"font-feature-settings",
	"grid-area",
	"grid-column",
	"grid-column-end",
	"grid-column-start",
	"grid-row",
	"grid-row-end",
	"grid-row-start",
	"grid-template-columns",
	"grid-template-rows",
	"hyphenate-limit-chars",
	"initial-letter",
	"line-clamp",
	"math-depth",
	"max-lines",
	"order",
	"orphans",
	"reading-order",
	"tab-size",
	"text-combine-upright",
	"transition",
	"transition-timing-function",
	"widows",
	"z-index"
]);

// Properties every one of whose numeric leaves `mdn-data` annotates as
// non-negative. Deliberately narrow, being read to allow a rewrite: a property
// the dataset leaves unannotated is simply absent, so a bare negative is never
// mistaken for one an engine would have clamped.
const NON_NEGATIVE_PROPERTIES = new Set([
	"-webkit-mask-size",
	"animation-duration",
	"aspect-ratio",
	"background-size",
	"border-bottom-left-radius",
	"border-bottom-right-radius",
	"border-image-outset",
	"border-image-slice",
	"border-image-width",
	"border-radius",
	"border-top-left-radius",
	"border-top-right-radius",
	"column-height",
	"column-width",
	"dynamic-range-limit",
	"font-palette",
	"font-size",
	"font-weight",
	"font-width",
	"mask-size",
	"overflow-clip-margin",
	"padding-bottom",
	"padding-left",
	"padding-right",
	"padding-top",
	"zoom"
]);

// Packed `0xrrggbb` -> the shortest named color with that value. Only names that
// can beat `#rrggbb`; anything longer would never be picked.
const RGB_TO_NAME = new Map([
	[0x000080, "navy"],
	[0x008000, "green"],
	[0x008080, "teal"],
	[0x4b0082, "indigo"],
	[0x800000, "maroon"],
	[0x800080, "purple"],
	[0x808000, "olive"],
	[0x808080, "gray"],
	[0xa0522d, "sienna"],
	[0xa52a2a, "brown"],
	[0xc0c0c0, "silver"],
	[0xcd853f, "peru"],
	[0xd2b48c, "tan"],
	[0xda70d6, "orchid"],
	[0xdda0dd, "plum"],
	[0xee82ee, "violet"],
	[0xf0e68c, "khaki"],
	[0xf0ffff, "azure"],
	[0xf5deb3, "wheat"],
	[0xf5f5dc, "beige"],
	[0xfa8072, "salmon"],
	[0xfaf0e6, "linen"],
	[0xff0000, "red"],
	[0xff6347, "tomato"],
	[0xff7f50, "coral"],
	[0xffa500, "orange"],
	[0xffc0cb, "pink"],
	[0xffd700, "gold"],
	[0xffe4c4, "bisque"],
	[0xfffafa, "snow"],
	[0xfffff0, "ivory"]
]);

module.exports.ABSOLUTE_UNIT_SCALE = ABSOLUTE_UNIT_SCALE;
module.exports.ANGLE_UNITS = ANGLE_UNITS;
module.exports.BOX_FAMILY_PREFIX = BOX_FAMILY_PREFIX;
module.exports.BOX_LONGHANDS = BOX_LONGHANDS;
module.exports.BOX_SHORTHANDS = BOX_SHORTHANDS;
module.exports.COLOR_ARGUMENT_FUNCTIONS = COLOR_ARGUMENT_FUNCTIONS;
module.exports.COMPOUND_CONTINUATIONS = COMPOUND_CONTINUATIONS;
module.exports.CSS_WIDE_KEYWORDS = CSS_WIDE_KEYWORDS;
module.exports.CUBIC_BEZIER_KEYWORDS = CUBIC_BEZIER_KEYWORDS;
module.exports.DROPPABLE_WHEN_EMPTY_AT_RULES = DROPPABLE_WHEN_EMPTY_AT_RULES;
module.exports.FLEX_KEYWORDS = FLEX_KEYWORDS;
module.exports.FONT_WEIGHT_NUMBERS = FONT_WEIGHT_NUMBERS;
module.exports.INTEGER_PROPERTIES = INTEGER_PROPERTIES;
module.exports.LEGACY_PSEUDO_ELEMENTS = LEGACY_PSEUDO_ELEMENTS;
module.exports.MATH_FUNCTIONS = MATH_FUNCTIONS;
module.exports.NON_NEGATIVE_PROPERTIES = NON_NEGATIVE_PROPERTIES;
module.exports.PROPERTY_LONGHANDS = PROPERTY_LONGHANDS;
module.exports.PROPERTY_WRITERS = PROPERTY_WRITERS;
module.exports.RGB_TO_NAME = RGB_TO_NAME;
module.exports.SLASH_BOX_SHORTHANDS = SLASH_BOX_SHORTHANDS;
module.exports.SUBSTITUTION_FUNCTIONS = SUBSTITUTION_FUNCTIONS;
module.exports.UNIT_CONVERSION_TARGETS = UNIT_CONVERSION_TARGETS;
module.exports.ZERO_UNIT_KEEPING_PROPERTIES = ZERO_UNIT_KEEPING_PROPERTIES;
