/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BannerPlugin =
	| {
			/**
			 * Specifies the banner
			 */
			banner:
				| {
						[k: string]: any;
				  }
				| string;
			/**
			 * If true, banner will not be wrapped in a comment
			 */
			raw?: boolean;
			/**
			 * If true, the banner will only be added to the entry chunks
			 */
			entryOnly?: boolean;
			/**
			 * Include all modules that pass test assertion
			 */
			test?: Rules;
			/**
			 * Include all modules matching any of these conditions
			 */
			include?: Rules;
			/**
			 * Exclude all modules matching any of these conditions
			 */
			exclude?: Rules;
	  }
	| {
			[k: string]: any;
	  }
	| string;
export type Rules = Rule[] | Rule;
export type Rule =
	| {
			[k: string]: any;
	  }
	| string;
