/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IgnorePlugin =
	| {
			/**
			 * A RegExp to test the request against
			 */
			resourceRegExp?: {
				[k: string]: any;
			};
			/**
			 * A RegExp to test the context (directory) against
			 */
			contextRegExp?: {
				[k: string]: any;
			};
	  }
	| {
			/**
			 * A filter function for resource
			 */
			checkResource?: {
				[k: string]: any;
			};
			/**
			 * A filter function for context
			 */
			checkContext?: {
				[k: string]: any;
			};
	  };
