/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LoaderOptionsPlugin {
	/**
	 * Whether loaders should be in debug mode or not. debug will be removed as of webpack 3
	 */
	debug?: boolean;
	/**
	 * Where loaders can be switched to minimize mode
	 */
	minimize?: boolean;
	/**
	 * A configuration object that can be used to configure older loaders
	 */
	options?: {
		/**
		 * The context that can be used to configure older loaders
		 */
		context?: string;
		[k: string]: any;
	};
	[k: string]: any;
}
