it("should have correct local ident for css export locals", (done) => {
	Promise.all([
		import("./style.module.css"),
		import("./style.module.css?hash"),
		import("./style.module.css?hash-local"),
		import("./style.module.css?path-name-local"),
		import("./style.module.css?file-local"),
		import("./style.module.css?q#f"),
		import("./style.module.css?uniqueName-id-contenthash"),
		import("./style.module.css?hash-local-custom"),
		import("./style.module.css?uniquename-local"),
		import("./style.module.css?hash-base64-6"),
		import("./style.module.css?hash-6"),
		import("./style.module.css?fullhash-6"),
		import("./style.module.less"),
	]).then(([idLocal, hash, hashLocal, pathNameLocal, fileLocal, queryFragment, uniqueNameIdContenthash, hashLocalCustom, uniquenameLocal, hashBase64, hash6, fullhash6]) => {
		expect(idLocal).toMatchSnapshot();
		expect(hash).toMatchSnapshot();
		expect(hashLocal).toMatchSnapshot();
		expect(pathNameLocal).toMatchSnapshot();
		expect(fileLocal).toMatchSnapshot();
		expect(queryFragment).toMatchSnapshot();
		expect(uniqueNameIdContenthash).toMatchSnapshot();
		expect(hashLocalCustom).toMatchSnapshot();
		expect(uniquenameLocal).toMatchSnapshot();
		expect(hashBase64).toMatchSnapshot();
		expect(hash6).toMatchSnapshot();
		expect(fullhash6).toMatchSnapshot();
		done()
	}).catch(done)
});
