"use strict";

// cspell:ignore argnames autowhatever chartjs cryptojs defun dont farg fargs firestore hoofd instancesearch joda lvalues nonmatching redef syncfusion

// What swc's minifier does that webpack's does not yet, each with the tests
// whose output under their own options is bigger than swc's recorded one.
// Biggest group first: retire a test once it is no longer bigger.

/** @type {[string, string[]][]} */
const SWC_SMALLER_BY_REASON = [
	[
		"swc drops what nothing reads or what has no effect: unused variables and destructuring, side-effect-free `new Map()` and pure calls, an empty constructor",
		[
			"swc minifier: fixture/issues/11303/input.js",
			"swc minifier: fixture/issues/12192/input.js",
			"swc minifier: fixture/issues/12193/input.js",
			"swc minifier: fixture/issues/12204/nullish-arguments/input.js",
			"swc minifier: fixture/issues/12223/catch-return-no-finalizer-control/input.js",
			"swc minifier: fixture/issues/12223/nested-function-control/input.js",
			"swc minifier: fixture/issues/12227/input.js",
			"swc minifier: fixture/issues/12301/input.js",
			"swc minifier: fixture/issues/2262/1/input.js",
			"swc minifier: fixture/issues/6175/1/input.js",
			"swc minifier: fixture/issues/7331/2/input.js",
			"swc minifier: fixture/issues/8841/input.js",
			"swc minifier: fixture/issues/8974/input.js",
			"swc minifier: fixture/issues/9610-nested-defaults/input.js",
			"swc minifier: fixture/issues/9610/input.js",
			"swc minifier: fixture/issues/9922/1/input.js",
			"swc minifier: fixture/issues/do-while-false-terminal-jump/completion/unused-prefix-break/input.js",
			"swc minifier: fixture/issues/do-while-false-terminal-jump/completion/unused-prefix-continue/input.js",
			"swc minifier: fixture/issues/do-while-false-terminal-jump/directive-barrier/input.js",
			"swc minifier: fixture/no-side-effect/input.js",
			"swc minifier: fixture/simple/sequences/.0001/input.js",
			"swc minifier: pass-1/joda/2/input.js",
			"terser compress: arrow/call_args",
			"terser compress: arrow/call_args_drop_param",
			"terser compress: arrow/object_parens",
			"terser compress: asm/asm_function_expression",
			"terser compress: asm/asm_nested_functions",
			"terser compress: comparing/issue_2857_1",
			"terser compress: conditionals/cond_9",
			"terser compress: conditionals/equality_conditionals_true",
			"terser compress: conditionals/issue_1645_1",
			"terser compress: dead-code/dead_code_1",
			"terser compress: dead-code/dead_code_2_should_warn",
			"terser compress: dead-code/dead_code_2_should_warn_strict",
			"terser compress: dead-code/try_catch_finally",
			"terser compress: drop-unused/drop_assign",
			"terser compress: drop-unused/drop_toplevel_all",
			"terser compress: drop-unused/drop_toplevel_all_retain",
			"terser compress: drop-unused/drop_toplevel_retain",
			"terser compress: drop-unused/drop_toplevel_retain_array",
			"terser compress: drop-unused/issue_1715_1",
			"terser compress: drop-unused/issue_1715_2",
			"terser compress: drop-unused/issue_1715_4",
			"terser compress: drop-unused/issue_1968",
			"terser compress: drop-unused/issue_2136_1",
			"terser compress: drop-unused/issue_2226_1",
			"terser compress: drop-unused/issue_2418_1",
			"terser compress: drop-unused/issue_2418_2",
			"terser compress: drop-unused/issue_2418_3",
			"terser compress: drop-unused/issue_2418_4",
			"terser compress: drop-unused/issue_2418_5",
			"terser compress: evaluate/call_args",
			"terser compress: evaluate/call_args_drop_param",
			"terser compress: evaluate/issue_2926_1",
			"terser compress: functions/issue_2647_2",
			"terser compress: functions/issue_2647_3",
			"terser compress: harmony/array_spread_of_sequence",
			"terser compress: harmony/fat_arrow_as_param",
			"terser compress: harmony/issue_2794_4",
			"terser compress: harmony/issue_2794_6",
			"terser compress: harmony/object_spread_of_sequence",
			"terser compress: identity/inline_identity_dont_lose_this_when_arg",
			"terser compress: issue-1639/issue_1639_2",
			"terser compress: issue-269/regexp",
			"terser compress: issue-281/inner_var_for_in_1",
			"terser compress: issue-281/issue_1758",
			"terser compress: issue-281/negate_iife_4",
			"terser compress: issue-281/negate_iife_5",
			"terser compress: issue-281/negate_iife_5_off",
			"terser compress: issue-640/drop_value",
			"terser compress: issue-640/iife",
			"terser compress: labels/labels_10",
			"terser compress: labels/labels_5",
			"terser compress: loops/issue_2740_4",
			"terser compress: loops/issue_2740_6",
			"terser compress: loops/issue_2740_7",
			"terser compress: loops/issue_2740_8",
			"terser compress: reduce_vars/boolean_binary_assign",
			"terser compress: reduce_vars/defun_catch_1",
			"terser compress: reduce_vars/defun_catch_2",
			"terser compress: reduce_vars/defun_catch_3",
			"terser compress: reduce_vars/defun_catch_6",
			"terser compress: reduce_vars/escape_local_sequence",
			"terser compress: reduce_vars/issue_3140_5",
			"terser compress: reduce_vars/multi_def_3",
			"terser compress: reduce_vars/unsafe_evaluate_object_1"
		]
	],
	[
		"swc runs a transform the case's own options leave off (`evaluate`, `side_effects`, `unused`, `inline` levels, or any when the case sets none), so the gap is the options, not a missing transform",
		[
			"terser compress: collapse_vars/collapse_vars_repeated",
			"terser compress: collapse_vars/collapse_vars_self_reference",
			"terser compress: collapse_vars/issue_1631_3",
			"terser compress: comments/preserve_comments_by_default",
			"terser compress: conditionals/cond_8c",
			"terser compress: conditionals/no_evaluate",
			"terser compress: defaults/defaults_false",
			"terser compress: defaults/defaults_true_conditionals_false",
			"terser compress: defaults/defaults_true_evaluate_false",
			"terser compress: evaluate/Infinity_NaN_undefined_LHS",
			"terser compress: evaluate/pow_sequence_with_parens_exact",
			"terser compress: export/export_default_seq",
			"terser compress: export/issue_333",
			"terser compress: expression/pow",
			"terser compress: expression/pow_with_number_constants",
			"terser compress: expression/pow_with_parentheses",
			"terser compress: expression/pow_with_unary_between_brackets",
			"terser compress: functions/drop_lone_use_strict_arrows_1",
			"terser compress: functions/duplicate_arg_var",
			"terser compress: functions/empty_body",
			"terser compress: functions/inline_1",
			"terser compress: functions/inline_2",
			"terser compress: functions/inline_3",
			"terser compress: functions/inline_function_expressions",
			"terser compress: functions/inline_true",
			"terser compress: functions/inner_ref",
			"terser compress: functions/issue_1841_2",
			"terser compress: functions/issue_2620_1",
			"terser compress: functions/issue_2620_4",
			"terser compress: functions/issue_2842",
			"terser compress: functions/no_webkit",
			"terser compress: functions/non_ascii_function_identifier_name",
			"terser compress: functions/webkit",
			"terser compress: global_defs/expanded",
			"terser compress: hoist_props/issue_3071_3",
			"terser compress: if_return/issue_1437",
			"terser compress: issue-1609/chained_evaluation_1",
			"terser compress: issue-1609/chained_evaluation_2",
			"terser compress: issue-1656/f7",
			"terser compress: issue-2001/export_class_2",
			"terser compress: issue-2001/export_default_class_2",
			"terser compress: issue-2001/export_default_func_2",
			"terser compress: issue-2001/export_func_2",
			"terser compress: issue-281/issue_1254_negate_iife_true",
			"terser compress: issue-597/issue_1725",
			"terser compress: new/call_with_unary_arguments",
			"terser compress: new/dot_parenthesis_2",
			"terser compress: new/new_constructor_with_unary_arguments",
			"terser compress: numbers/hex_numbers_in_parentheses_for_prototype_functions",
			"terser compress: object/computed_property_names",
			"terser compress: parameters/default_arguments",
			"terser compress: reduce_vars/duplicate_lambda_defun_name_1",
			"terser compress: reduce_vars/iife_assign",
			"terser compress: reduce_vars/inner_var_for_in_1",
			"terser compress: reduce_vars/issue_1595_2",
			"terser compress: reduce_vars/issue_1595_3",
			"terser compress: reduce_vars/issue_1670_2",
			"terser compress: reduce_vars/issue_1670_4",
			"terser compress: reduce_vars/issue_1670_5",
			"terser compress: reduce_vars/issue_1814_2",
			"terser compress: reduce_vars/issue_2449",
			"terser compress: reduce_vars/issue_2450_4",
			"terser compress: reduce_vars/issue_2799_1",
			"terser compress: reduce_vars/issue_3113_1",
			"terser compress: reduce_vars/issue_3113_2",
			"terser compress: reduce_vars/issue_3113_5",
			"terser compress: reduce_vars/perf_1",
			"terser compress: reduce_vars/perf_5",
			"terser compress: reduce_vars/recursive_inlining_3",
			"terser compress: reduce_vars/toplevel_on_loops_1",
			"terser compress: reduce_vars/toplevel_on_loops_2",
			"terser compress: reduce_vars/unused_modified",
			"terser compress: reduce_vars/var_assign_1",
			"terser compress: reduce_vars/var_assign_2",
			"terser compress: reduce_vars/var_assign_3",
			"terser compress: reduce_vars/var_assign_5",
			"terser compress: sequences/iife",
			"terser compress: sequences/issue_1758",
			"terser compress: sequences/negate_iife_for",
			"terser compress: sequences/unsafe_undefined",
			"terser compress: switch/if_else7",
			"terser compress: template-string/regex_1",
			"terser compress: template-string/sequence_1",
			"terser compress: template-string/template_string_with_many_segments",
			"terser compress: template-string/template_strings",
			"terser compress: template-string/template_strings_ascii_only",
			"terser compress: transform/if_else_empty",
			"terser compress: try-catch/catch_destructuring_with_sequence",
			"terser compress: typeof/issue_2728_4"
		]
	],
	[
		"swc writes a variable's value at its one read and drops the variable, an alias of another binding or an assignment folded into its next read included",
		[
			"swc minifier: fixture/issues/10041/input.js",
			"swc minifier: fixture/issues/12118/input.js",
			"swc minifier: fixture/issues/12188/input.js",
			"swc minifier: fixture/issues/12380/input.js",
			"swc minifier: fixture/issues/2779/1/input.js",
			"swc minifier: fixture/issues/2779/2/input.js",
			"swc minifier: fixture/issues/3629/1/input.js",
			"swc minifier: fixture/issues/5846/input.js",
			"swc minifier: fixture/issues/5910/1/input.js",
			"swc minifier: fixture/issues/6049/1/input.js",
			"swc minifier: fixture/issues/6492/3/input.js",
			"swc minifier: fixture/issues/6492/4/input.js",
			"swc minifier: fixture/issues/7402/input.js",
			"swc minifier: fixture/issues/7500/input.js",
			"swc minifier: fixture/issues/7568/1/input.js",
			"swc minifier: fixture/issues/7739/1/input.js",
			"swc minifier: fixture/issues/7847/input.js",
			"swc minifier: fixture/issues/8173/input.js",
			"swc minifier: fixture/issues/8718/3/input.js",
			"swc minifier: fixture/issues/8718/4/input.js",
			"swc minifier: fixture/issues/8806/input.js",
			"swc minifier: fixture/issues/8923/input.js",
			"swc minifier: fixture/issues/8924/input.js",
			"swc minifier: fixture/issues/9610-keep-fargs/input.js",
			"swc minifier: fixture/issues/react-countup/2/input.js",
			"swc minifier: fixture/issues/react/hooks/1/input.js",
			"swc minifier: fixture/next/feedback-1/reduced/1/input.js",
			"swc minifier: fixture/pr/11446/input.js",
			"swc minifier: fixture/projects/react/10/input.js",
			"swc minifier: fixture/projects/react/11/input.js",
			"swc minifier: fixture/projects/react/9/input.js",
			"swc minifier: fixture/projects/yui/11/input.js",
			"swc minifier: fixture/reduced/3/input.js",
			"terser compress: classes/class_duplication_2",
			"terser compress: collapse_vars/collapse_vars_array",
			"terser compress: collapse_vars/collapse_vars_closures",
			"terser compress: collapse_vars/collapse_vars_side_effects_2",
			"terser compress: collapse_vars/collapse_vars_while",
			"terser compress: collapse_vars/issue_1537_destructuring_1",
			"terser compress: collapse_vars/issue_2187_1",
			"terser compress: collapse_vars/issue_2436_9",
			"terser compress: collapse_vars/var_defs",
			"terser compress: collapse_vars/var_side_effects_2",
			"terser compress: dead-code/issue_2233_2",
			"terser compress: drop-unused/cascade_drop_assign",
			"terser compress: drop-unused/issue_2768",
			"terser compress: drop-unused/issue_t161_top_retain_10",
			"terser compress: drop-unused/issue_t161_top_retain_12",
			"terser compress: drop-unused/issue_t161_top_retain_13",
			"terser compress: drop-unused/issue_t161_top_retain_14",
			"terser compress: drop-unused/vardef_value",
			"terser compress: evaluate/issue_2916_1",
			"terser compress: functions/duplicate_argnames",
			"terser compress: functions/issue_2531_1",
			"terser compress: functions/issue_2601_1",
			"terser compress: functions/issue_2620_2",
			"terser compress: functions/issue_2663_1",
			"terser compress: functions/issue_2663_3",
			"terser compress: harmony/issue_2874_3",
			"terser compress: harmony/object_spread_unsafe",
			"terser compress: hoist_props/issue_2473_4",
			"terser compress: hoist_props/issue_851_hoist_to_conflicting_name",
			"terser compress: hoist_props/name_collision_1",
			"terser compress: hoist_props/name_collision_2",
			"terser compress: hoist_props/name_collision_3",
			"terser compress: issue-1639/issue_1639_3",
			"terser compress: issue-t120/issue_t120_1",
			"terser compress: issue-t120/issue_t120_2",
			"terser compress: loops/dead_code_condition",
			"terser compress: pure_getters/issue_2265_2",
			"terser compress: pure_getters/set_immutable_2",
			"terser compress: pure_getters/set_immutable_4",
			"terser compress: reduce_vars/defun_inline_1",
			"terser compress: reduce_vars/defun_inline_2",
			"terser compress: reduce_vars/issue_1606",
			"terser compress: reduce_vars/issue_1850_4",
			"terser compress: reduce_vars/issue_294",
			"terser compress: reduce_vars/issue_3110_3",
			"terser compress: reduce_vars/regex_loop",
			"terser compress: reduce_vars/unsafe_evaluate_array_1",
			"terser compress: sequences/lift_sequences_2",
			"terser compress: sequences/lift_sequences_5",
			"terser compress: sequences/lift_sequences_6"
		]
	],
	[
		"swc inlines a function into its call site, where terser keeps the call: one used once, a small one used a few times, or an IIFE unwrapped into statements",
		[
			"swc minifier: fixture/issues/10532/input.js",
			"swc minifier: fixture/issues/10746/input.js",
			"swc minifier: fixture/issues/10876/1/input.js",
			"swc minifier: fixture/issues/10876/2/input.js",
			"swc minifier: fixture/issues/10876/3/input.js",
			"swc minifier: fixture/issues/11007/input.js",
			"swc minifier: fixture/issues/11103/input.js",
			"swc minifier: fixture/issues/11158/input.js",
			"swc minifier: fixture/issues/11512-exhaustive/fn-multi-use-default-side-effect/input.js",
			"swc minifier: fixture/issues/11512-exhaustive/fn-multi-use-default-unused/input.js",
			"swc minifier: fixture/issues/11512-exhaustive/iife-default-side-effect/input.js",
			"swc minifier: fixture/issues/11512-simple/input.js",
			"swc minifier: fixture/issues/11512/input.js",
			"swc minifier: fixture/issues/11755/input.js",
			"swc minifier: fixture/issues/11871/input.js",
			"swc minifier: fixture/issues/11983/input.js",
			"swc minifier: fixture/issues/12128/input.js",
			"swc minifier: fixture/issues/12177/input.js",
			"swc minifier: fixture/issues/12219/iife_rest_control_primitive/input.js",
			"swc minifier: fixture/issues/12226/input.js",
			"swc minifier: fixture/issues/12311/input.js",
			"swc minifier: fixture/issues/6279/1/input.js",
			"swc minifier: fixture/issues/6279/2/input.js",
			"swc minifier: fixture/issues/6751/1/input.js",
			"swc minifier: fixture/issues/6837/1/input.js",
			"swc minifier: fixture/issues/6837/2/input.js",
			"swc minifier: fixture/issues/7004/input.js",
			"swc minifier: fixture/issues/7241/input.js",
			"swc minifier: fixture/issues/7287/1/input.js",
			"swc minifier: fixture/issues/7784/1/input.js",
			"swc minifier: fixture/issues/7784/2/input.js",
			"swc minifier: fixture/issues/8271/input.js",
			"swc minifier: fixture/issues/8622/input.js",
			"swc minifier: fixture/issues/8826/input.js",
			"swc minifier: fixture/issues/9148/input.js",
			"swc minifier: fixture/issues/9468/input.js",
			"swc minifier: fixture/issues/9610-arrow-functions/input.js",
			"swc minifier: fixture/issues/9756/input.js",
			"swc minifier: fixture/issues/9785/input.js",
			"swc minifier: fixture/issues/cycle-1/input.js",
			"swc minifier: fixture/issues/cycle-2/input.js",
			"swc minifier: fixture/issues/pure-callee-call/input.js",
			"swc minifier: fixture/issues/react/hooks/3/input.js",
			"swc minifier: fixture/pr/7690/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/about-9ff906d607f52933d473/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/process-env-ea448cdafe7e87f74757/input.js",
			"swc minifier: fixture/projects/wmr/archive-1/chunks/prerender.93c6f601/input.js",
			"swc minifier: fixture/simple/inline/1/input.js",
			"swc minifier: fixture/simple/inline/3/input.js",
			"swc minifier: fixture/simple/inline/4/input.js",
			"swc minifier: full/issues/8288/input.js",
			"swc minifier: pass-1/9/1/input.js",
			"terser compress: block-scope/issue_334",
			"terser compress: collapse_vars/issue_2436_2",
			"terser compress: collapse_vars/issue_2436_3",
			"terser compress: collapse_vars/issue_2436_5",
			"terser compress: collapse_vars/issue_2453",
			"terser compress: collapse_vars/recursive_function_replacement",
			"terser compress: destructuring/issue_3205_2",
			"terser compress: destructuring/issue_3205_3",
			"terser compress: destructuring/issue_3205_4",
			"terser compress: functions/inline_loop_1",
			"terser compress: functions/inline_loop_2",
			"terser compress: functions/inline_loop_3",
			"terser compress: functions/issue_2476",
			"terser compress: functions/issue_2604_1",
			"terser compress: functions/issue_2616",
			"terser compress: functions/issue_2630_1",
			"terser compress: functions/issue_2630_3",
			"terser compress: functions/issue_2630_4",
			"terser compress: functions/issue_2657",
			"terser compress: functions/issue_2663_2",
			"terser compress: functions/issue_2737_1",
			"terser compress: functions/issue_2737_2",
			"terser compress: functions/issue_2783",
			"terser compress: functions/loop_init_arg",
			"terser compress: hoist_props/issue_2377_1",
			"terser compress: identity/inline_identity_extra_params",
			"terser compress: identity/inline_identity_higher_order",
			"terser compress: inline/issue_308",
			"terser compress: issue-t292/no_flatten_with_arg_colliding_with_arg_value_inner_scope",
			"terser compress: issue-t292/no_flatten_with_var_colliding_with_arg_value_inner_scope",
			"terser compress: reduce_vars/variables_collision_in_immediately_invoked_func"
		]
	],
	[
		"webpack writes the same program in a spelling longer or compressing worse than swc's: `,` where swc keeps `;` between statements, operand order, `{0}` for an empty body",
		[
			"swc minifier: fixture/issues/11084/input.js",
			"swc minifier: fixture/issues/11684/identifier-aliases/input.js",
			"swc minifier: fixture/issues/12282/call/input.js",
			"swc minifier: fixture/issues/3256/1/input.js",
			"swc minifier: fixture/issues/4515/input.js",
			"swc minifier: fixture/issues/5588/input.js",
			"swc minifier: fixture/issues/6791/1/input.js",
			"swc minifier: fixture/issues/8119/input.js",
			"swc minifier: fixture/issues/9460/strict-mode/input.js",
			"swc minifier: fixture/issues/do-while-false-terminal-jump/guarded-jump/input.js",
			"swc minifier: fixture/issues/drop-console-es2015/input.js",
			"swc minifier: fixture/issues/object-accessor-function-boundary/input.js",
			"swc minifier: fixture/next/43052/input.js",
			"swc minifier: fixture/projects/backbone/12/input.js",
			"swc minifier: fixture/projects/backbone/19/input.js",
			"swc minifier: fixture/projects/jquery/.17/input.js",
			"swc minifier: fixture/projects/mootools/3/input.js",
			"swc minifier: fixture/projects/react/13/input.js",
			"swc minifier: fixture/projects/yui/12/input.js",
			"swc minifier: fixture/projects/yui/9/input.js",
			"swc minifier: fixture/terser/issue-2435-1/2/input.js",
			"swc minifier: fixture/terser/issue-2535-2/1/input.js",
			"swc minifier: fixture/terser/issue-2535-2/2-1/input.js",
			"swc minifier: fixture/terser/issue-2535-2/2/input.js",
			"swc minifier: fixture/terser/issue-2535-2/4/input.js",
			"swc minifier: full/size/54531ba076299b43c00a0d234240369f93371a41/input.js",
			"swc minifier: projects/files/underscore-1.5.2.js",
			"terser compress: collapse_vars/collapse_rhs_conditional_2",
			"terser compress: comparing/self_comparison_2",
			"terser compress: conditionals/cond_7_1",
			"terser compress: conditionals/equality_conditionals_false",
			"terser compress: conditionals/ifs_3_should_warn",
			"terser compress: const/issue_1396",
			"terser compress: drop-unused/issue_3192",
			"terser compress: evaluate/and",
			"terser compress: evaluate/issue_2207_3",
			"terser compress: evaluate/or",
			"terser compress: harmony/shorthand_keywords",
			"terser compress: if_return/issue_1437_conditionals",
			"terser compress: issue-1704/mangle_catch_redef_3",
			"terser compress: issue-1733/function_iife_catch",
			"terser compress: issue-640/negate_iife_1",
			"terser compress: issue-640/negate_iife_3",
			"terser compress: loops/issue_186_beautify_braces",
			"terser compress: loops/issue_186_braces",
			"terser compress: properties/join_object_assignments_NaN_1",
			"terser compress: reduce_vars/multi_def_2",
			"terser compress: rename/function_iife_catch"
		]
	],
	[
		"swc evaluates a built-in called on literals at build time (`toFixed`, `Object.keys`, `[…].join`, `String.fromCharCode`, `Math.*`, string methods), which terser leaves to run time",
		[
			"swc minifier: fixture/issues/11102/input.js",
			"swc minifier: fixture/issues/12213/distinct/input.js",
			"swc minifier: fixture/issues/12213/duplicate/input.js",
			"swc minifier: fixture/issues/12213/numeric-order/input.js",
			"swc minifier: fixture/issues/12214/input.js",
			"swc minifier: fixture/issues/12215/input.js",
			"swc minifier: fixture/issues/12224/input.js",
			"swc minifier: fixture/issues/6957/2/input.js",
			"swc minifier: fixture/issues/7714/1/input.js",
			"swc minifier: fixture/issues/9741_multiple_methods/input.js",
			"swc minifier: fixture/next/swc-4559/input.js",
			"swc minifier: pass-1/compute/1/input.js",
			"swc minifier: pass-default/compute/1/input.js",
			"swc minifier: pass-default/math-constant-folding/1/input.js",
			"terser compress: evaluate/issue_2207_1",
			"terser compress: issue-597/NaN_and_Infinity_must_have_parens_evaluate",
			"terser compress: issue-597/beautify_off_1",
			"terser compress: issue-597/beautify_on_1"
		]
	],
	[
		"swc restructures conditionals: an `if` as `&&` or `?:`, a shared tail or call factored out, `continue` and `break` folded into the condition",
		[
			"swc minifier: fixture/issues/2926/1/input.js",
			"swc minifier: fixture/issues/7984/input.js",
			"swc minifier: fixture/issues/do-while-false-control-flow/input.js",
			"swc minifier: fixture/issues/do-while-false-terminal-jump/rejected/input.js",
			"swc minifier: fixture/issues/do-while-false-terminal-jump/scope-directives/input.js",
			"swc minifier: fixture/projects/backbone/2/input.js",
			"swc minifier: fixture/projects/backbone/5/input.js",
			"swc minifier: fixture/projects/mootools/10/input.js",
			"swc minifier: fixture/projects/mootools/8/input.js",
			"swc minifier: fixture/simple/switch/const/call/input.js",
			"swc minifier: fixture/simple/switch/const/order/input.js",
			"swc minifier: full/size/6d52ebcc72a64f1f1ef2594baecb5dcab49b1a32/input.js",
			"swc minifier: pass-1/4/input.js",
			"terser compress: collapse_vars/boolean_binary_1",
			"terser compress: collapse_vars/boolean_binary_2",
			"terser compress: conditionals/cond_8",
			"terser compress: conditionals/cond_8b",
			"terser compress: conditionals/issue_2535_1",
			"terser compress: issue-1673/side_effects_else",
			"terser compress: issue-637/wrongly_optimized",
			"terser compress: issue-640/cond_5",
			"terser compress: issue-640/conditional",
			"terser compress: issue-640/dead_code_const_annotation_regex",
			"terser compress: issue-640/wrongly_optimized",
			"terser compress: loops/issue_1648",
			"terser compress: reduce_vars/cond_assign",
			"terser compress: reduce_vars/issue_2669",
			"terser compress: reduce_vars/issue_2774"
		]
	],
	[
		"swc writes `const` as `let`, a byte shorter and mergeable with its neighbors, and moves leading `var`s into a later declaration",
		[
			"swc minifier: fixture/issues/10824/input.js",
			"swc minifier: fixture/issues/7783/1/input.js",
			"swc minifier: fixture/issues/8907/input.js",
			"swc minifier: fixture/issues/9263/input.js",
			"swc minifier: fixture/issues/vercel/002/input.js",
			"swc minifier: fixture/issues/vercel/003/input.js",
			"swc minifier: fixture/issues/vercel/004/input.js",
			"swc minifier: fixture/projects/mootools/6/input.js",
			"swc minifier: fixture/projects/mootools/7/input.js",
			"swc minifier: fixture/projects/wmr/archive-1/chunks/json.5609c5fa/input.js",
			"terser compress: block-scope/do_not_hoist_let",
			"terser compress: collapse_vars/switch_case_2",
			"terser compress: collapse_vars/switch_case_3",
			"terser compress: dead-code/dead_code_const_declaration"
		]
	],
	[
		"swc evaluates reads on literals at build time: an index into an array or string, a missing property as `void 0`, `typeof` a class, `delete` of a binding",
		[
			"swc minifier: fixture/issues/12189/input.js",
			"swc minifier: fixture/issues/12190/input.js",
			"swc minifier: fixture/issues/9453/input.js",
			"swc minifier: fixture/issues/numeric-property-key/input.js",
			"swc minifier: fixture/issues/string-index-utf16/input.js",
			"swc minifier: fixture/member_expr/array_side_effects/input.js",
			"swc minifier: fixture/member_expr/object_side_effects/input.js",
			"swc minifier: fixture/member_expr/seq/input.js",
			"swc minifier: fixture/pr/6169/1/input.js",
			"terser compress: arrow/issue_2136_2",
			"terser compress: collapse_vars/collapse_vars_unary",
			"terser compress: collapse_vars/reduce_vars_assign",
			"terser compress: comparing/issue_2857_6",
			"terser compress: drop-unused/issue_2136_2",
			"terser compress: evaluate/delete_expr_1",
			"terser compress: evaluate/delete_expr_2",
			"terser compress: evaluate/in_boolean_context",
			"terser compress: evaluate/unsafe_array_bad_index",
			"terser compress: evaluate/unsafe_string_bad_index",
			"terser compress: harmony/array_literal_with_spread_2a",
			"terser compress: harmony/array_literal_with_spread_3a",
			"terser compress: switch/issue_1679",
			"terser compress: template-string/simple_string",
			"terser compress: typeof/issue_2728_3"
		]
	],
	[
		"swc drops `new` before a built-in that constructs the same when called (`Error`, `RegExp`, `Array`)",
		[
			"swc minifier: fixture/issues/12187/input.js",
			"swc minifier: fixture/projects/backbone/18/input.js"
		]
	],
	[
		"swc drops call and `new` arguments past the parameters of a callee it can see, and an unused parameter whose default is pure",
		[
			"swc minifier: fixture/issues/11512-exhaustive/iife-anon-arg-unused/input.js",
			"swc minifier: fixture/issues/11512-exhaustive/iife-anon-default-unused/input.js",
			"swc minifier: fixture/issues/11645/control-known-arity-drop/input.js",
			"swc minifier: fixture/issues/11684/class-decl/input.js",
			"swc minifier: fixture/issues/11684/class-expression/input.js",
			"swc minifier: fixture/issues/11684/constructor-scopes/input.js",
			"swc minifier: fixture/issues/11684/identifier-reduce-vars-only/input.js",
			"swc minifier: fixture/issues/11684/identifier-side-effects/input.js",
			"swc minifier: fixture/issues/11684/identifier-unused-only/input.js",
			"swc minifier: fixture/issues/11684/side-effects/input.js",
			"swc minifier: fixture/issues/12212/safe-unused-rest/input.js",
			"swc minifier: fixture/issues/12218/leading-argument/input.js",
			"terser compress: collapse_vars/issue_2436_12",
			"terser compress: export/issue_2131"
		]
	],
	[
		"swc merges imports of one module, drops unused specifiers, and folds a declaration into its `export default`",
		[
			"swc minifier: fixture/check/1/input.js",
			"swc minifier: fixture/issues/11133/input.js",
			"swc minifier: fixture/issues/11257/input.js",
			"swc minifier: fixture/issues/11321/input.js",
			"swc minifier: fixture/issues/12185/input.js",
			"swc minifier: fixture/issues/6192/1/input.js",
			"swc minifier: fixture/issues/7634/1/input.js",
			"swc minifier: fixture/issues/8465/input.js",
			"swc minifier: fixture/projects/wmr/archive-1/chunks/alias-outside.6e8773c7/input.js",
			"swc minifier: fixture/projects/wmr/archive-1/chunks/class-fields.43d5f69c/input.js",
			"swc minifier: fixture/projects/wmr/archive-1/chunks/index.5a544c41/input.js",
			"swc minifier: fixture/pure-annotations-not-member-pattern/input.js",
			"swc minifier: full/helpers/1/input.js",
			"terser compress: classes/class_duplication",
			"terser compress: export/issue_2126",
			"terser compress: export/redirection"
		]
	],
	[
		"swc splits a constant object into a variable per property, or reads a property or method straight off the literal, where terser keeps the object",
		[
			"swc minifier: fixture/issues/10630/input.js",
			"swc minifier: fixture/issues/10849/input.js",
			"swc minifier: fixture/issues/11083/input.js",
			"swc minifier: fixture/issues/12182/callee-safety/lexical-this/input.js",
			"swc minifier: fixture/issues/12182/callee-safety/nested-values/input.js",
			"swc minifier: fixture/issues/12182/hoist-props/input.js",
			"swc minifier: fixture/issues/12182/receiver-sensitive/input.js",
			"swc minifier: fixture/issues/8737/2/input.js",
			"swc minifier: fixture/issues/8737/input.js",
			"swc minifier: fixture/issues/9610-methods/input.js",
			"swc minifier: fixture/member_expr/callee/input.js",
			"swc minifier: fixture/projects/wmr/archive-1/chunks/index.bf24abaa/input.js",
			"swc minifier: fixture/projects/wmr/archive-1/chunks/index.ddc4110d/input.js",
			"swc minifier: pass-1/issue-6788/1/input.js",
			"terser compress: hoist_props/direct_access_2",
			"terser compress: template-string/tagged_call_with_invalid_escape_2"
		]
	],
	[
		"swc resolves a `switch` on a known value at build time, and writes a one-case `switch` as an `if`",
		[
			"swc minifier: fixture/issues/12206/hoist-var-from-retained-test/input.js",
			"swc minifier: fixture/issues/12206/preserve-selected-test/input.js",
			"swc minifier: fixture/issues/12206/preserve-visited-nonmatching-test/input.js",
			"swc minifier: fixture/issues/12298/input.js",
			"swc minifier: fixture/issues/4412/input.js",
			"swc minifier: fixture/issues/8813/input.js",
			"swc minifier: fixture/issues/9619/input.js",
			"terser compress: issue-1750/case_2",
			"terser compress: switch/if_else5",
			"terser compress: switch/if_else6",
			"terser compress: switch/issue_1690_2",
			"terser compress: switch/issue_1698",
			"terser compress: switch/issue_1750",
			"terser compress: switch/issue_2535",
			"terser compress: switch/issue_441_1",
			"terser compress: switch/issue_441_2"
		]
	],
	[
		"swc follows a variable's value through its reassignments and folds the result to a constant",
		[
			"swc minifier: fixture/issues/2011/actual/input.js",
			"swc minifier: fixture/issues/5280/input.js",
			"swc minifier: fixture/issues/8718/2/input.js",
			"swc minifier: fixture/issues/8718/5/input.js",
			"swc minifier: fixture/issues/8718/6/input.js",
			"swc minifier: fixture/issues/8919/input.js",
			"swc minifier: fixture/next/joda/input.js",
			"terser compress: collapse_vars/issue_2313_2",
			"terser compress: dead-code/issue_2860_1",
			"terser compress: hoist_props/issue_2377_2",
			"terser compress: reduce_vars/issue_1670_1",
			"terser compress: reduce_vars/issue_1670_3",
			"terser compress: reduce_vars/issue_2860_1",
			"terser compress: reduce_vars/lvalues_def_2",
			"terser compress: reduce_vars/redefine_farg_2"
		]
	],
	[
		'swc picks shorter spellings for comparisons and coercions: `"u">typeof x`, `null==x`, `==` between operands of one type, `!!x` for `Boolean(x)`, no `|0` on an int32',
		[
			"swc minifier: fixture/issues/10281/input.js",
			"swc minifier: fixture/issues/12186/nested-bitwise/input.js",
			"swc minifier: fixture/issues/12186/signed-shift/input.js",
			"swc minifier: fixture/issues/12307/input.js",
			"swc minifier: fixture/issues/array-constructor-length/input.js",
			"swc minifier: fixture/projects/yui/2/input.js",
			"terser compress: collapse_vars/collapse_vars_properties",
			"terser compress: pure_funcs/assign"
		]
	],
	[
		'swc folds arithmetic and concatenation of literals (`"1"+"2"`, `1+""`, `5+3`) that terser leaves as written',
		[
			"terser compress: concat-strings/concat_2",
			"terser compress: concat-strings/concat_3",
			"terser compress: concat-strings/concat_4",
			"terser compress: concat-strings/concat_5",
			"terser compress: concat-strings/concat_6",
			"terser compress: concat-strings/concat_7",
			"terser compress: concat-strings/concat_8",
			"terser compress: dead-code/collapse_vars_misc1",
			"terser compress: hoist_props/issue_2519"
		]
	],
	[
		"swc reads `arguments[i]` as the named parameter it aliases",
		[
			"swc minifier: fixture/issues/12209/input.js",
			"swc minifier: fixture/issues/arguments-canonical-index/input.js"
		]
	],
	[
		"real-world code, where the gap sums several of the transforms above; split it once those land",
		[
			"swc minifier: fixture/issues/10473/input.js",
			"swc minifier: fixture/issues/10807/input.js",
			"swc minifier: fixture/issues/12315/input.js",
			"swc minifier: fixture/issues/2044/full/input.js",
			"swc minifier: fixture/issues/2044/pass-1/input.js",
			"swc minifier: fixture/issues/5682/input.js",
			"swc minifier: fixture/issues/6957/exponential/input.js",
			"swc minifier: fixture/issues/6957/number-tostring/input.js",
			"swc minifier: fixture/issues/7472/1/input.js",
			"swc minifier: fixture/issues/8643/input.js",
			"swc minifier: fixture/issues/8880/1/input.js",
			"swc minifier: fixture/issues/d3-time-format/1/input.js",
			"swc minifier: fixture/issues/d3-time-format/3/input.js",
			"swc minifier: fixture/issues/emotion/react/1/input.js",
			"swc minifier: fixture/issues/emotion/react/2/input.js",
			"swc minifier: fixture/issues/firebase-core/1/input.js",
			"swc minifier: fixture/issues/firebase-firestore/1/input.js",
			"swc minifier: fixture/issues/firebase/dist/1/input.js",
			"swc minifier: fixture/issues/issue-2604/1/input.js",
			"swc minifier: fixture/issues/moment/1/input.js",
			"swc minifier: fixture/issues/quagga2/1.4.2/1/input.js",
			"swc minifier: fixture/issues/react-autosuggest/1/input.js",
			"swc minifier: fixture/issues/react-autowhatever/1/input.js",
			"swc minifier: fixture/issues/react-countup/1/input.js",
			"swc minifier: fixture/issues/react-instancesearch/002/input.js",
			"swc minifier: fixture/issues/react-instancesearch/003/input.js",
			"swc minifier: fixture/issues/react-instancesearch/004/input.js",
			"swc minifier: fixture/issues/stylis/1/input.js",
			"swc minifier: fixture/issues/stylis/2/input.js",
			"swc minifier: fixture/issues/vercel/005/input.js",
			"swc minifier: fixture/issues/vercel/006/input.js",
			"swc minifier: fixture/next/33265/static/chunks/d6e1aeb5-38a8d7ae57119c23/input.js",
			"swc minifier: fixture/next/33265/static/chunks/pages/index-cb36c1bf7f830e3c/input.js",
			"swc minifier: fixture/next/33458/static/chunks/pages/no-spread-2db60295b526e113/input.js",
			"swc minifier: fixture/next/33458/static/chunks/pages/spread-be872e60d968a0f7/input.js",
			"swc minifier: fixture/next/36127/2/3/input.js",
			"swc minifier: fixture/next/39538/static/chunks/pages/index-1bd068cedc2b5af3/input.js",
			"swc minifier: fixture/next/41527/1/input.js",
			"swc minifier: fixture/next/43208/static/chunks/pages/index-e1d69965f0f167c9/input.js",
			"swc minifier: fixture/next/46887/input.js",
			"swc minifier: fixture/next/47005/input.js",
			"swc minifier: fixture/next/54192/1/input.js",
			"swc minifier: fixture/next/54192/2/input.js",
			"swc minifier: fixture/next/56408/input.js",
			"swc minifier: fixture/next/66237/input.js",
			"swc minifier: fixture/next/66378/input.js",
			"swc minifier: fixture/next/brotli-decompress/static/chunks/545-ff8f898b276d138f/input.js",
			"swc minifier: fixture/next/chakra/input.js",
			"swc minifier: fixture/next/cryptojs/input.js",
			"swc minifier: fixture/next/feedback-2/codemirror/input.js",
			"swc minifier: fixture/next/feedback-3/579-dcac359116b2707c/input.js",
			"swc minifier: fixture/next/feedback-util-promisify/chunks/pages/_app-72ad41192608e93a/input.js",
			"swc minifier: fixture/next/octokit/static/chunks/357-72bd409f1472b1b8/input.js",
			"swc minifier: fixture/next/react-ace/chunks/8a28b14e.d8fbda268ed281a1/input.js",
			"swc minifier: fixture/next/react-chartjs/input.js",
			"swc minifier: fixture/next/styled-components/1/input.js",
			"swc minifier: fixture/next/syncfusion/933-e9f9a6bf671b96fc/input.js",
			"swc minifier: fixture/next/target-es2015/static/chunks/main-04b5934c26266542/input.js",
			"swc minifier: fixture/next/wrap-contracts/input.js",
			"swc minifier: fixture/projects/backbone/20/input.js",
			"swc minifier: fixture/projects/jquery/12/input.js",
			"swc minifier: fixture/projects/mootools/.11/input.js",
			"swc minifier: fixture/projects/next/.archive-4/266-aee26c928109d49d6151/input.js",
			"swc minifier: fixture/projects/next/.archive-4/framework-054ead69ea8124b4cb27/input.js",
			"swc minifier: fixture/projects/next/.archive-4/main-2953d6142ff4a439dbc0/input.js",
			"swc minifier: fixture/projects/next/.archive-4/pages/development-logs/link-with-no-prefetch-53313deb99cf94686856/input.js",
			"swc minifier: fixture/projects/next/.archive-4/pages/development-logs/link-with-prefetch-false-13db3186d6589f014e19/input.js",
			"swc minifier: fixture/projects/next/.archive-4/polyfills-6437a4964f697e5b0b3e/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/hmr/about-f41723bb58a39accd7f5/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/hmr/about1-337f4553e7fa4c711971/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/hmr/about2-071e285e01649f2eba6d/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/hmr/about3-4799682b161140f8d8ca/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/hmr/about4-5b76801c16eeaea0c007/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/hmr/about5-701a8a2644b1f6251651/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/hmr/about6-25feb06f767ae1c20330/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/hmr/about7-9df961ea8fb5d2c5b7a2/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/hmr/contact-e0ce31ea2cdf538f0cad/input.js",
			"swc minifier: fixture/projects/next/archive-1/pages/hmr/style-752f74ed22a8a38573be/input.js",
			"swc minifier: fixture/projects/next/archive-2/pages/._app-b4bcb0e52cac90b0d2d8/input.js",
			"swc minifier: fixture/projects/next/archive-2/pages/.development-logs-2ac9e724502f3ba1f1de/input.js",
			"swc minifier: fixture/projects/next/archive-2/pages/.dynamic-098d0d54bd014f190920/input.js",
			"swc minifier: fixture/projects/next/archive-2/pages/.hmr-ce649615cbc9a3b4c1ce/input.js",
			"swc minifier: fixture/projects/next/archive-2/pages/hmr/.counter-c6a48518c4a56e4d9ce5/input.js",
			"swc minifier: fixture/projects/next/archive-2/pages/hmr/.error-in-gip-bd210c03b443f903b86d/input.js",
			"swc minifier: fixture/projects/next/archive-2/pages/hmr/.style-dynamic-component-9a264c0c3df661f65dda/input.js",
			"swc minifier: fixture/projects/next/archive-2/pages/hmr/.style-stateful-component-6cd7bdfa37b75acb9d04/input.js",
			"swc minifier: fixture/projects/next/archive-3/pages/dynamic/chunkfilename-b114cf1d23876beaa712/input.js",
			"swc minifier: fixture/projects/next/archive-3/pages/dynamic/function-7fe8439c89afccb77983/input.js",
			"swc minifier: fixture/projects/next/archive-3/pages/dynamic/head-432fc3a9a66c90ce2ec2/input.js",
			"swc minifier: fixture/projects/next/archive-3/pages/dynamic/multiple-modules-d02ebebcfa5282e50b34/input.js",
			"swc minifier: fixture/projects/next/archive-3/pages/dynamic/nested-05a7ce04b1f7eb6da341/input.js",
			"swc minifier: fixture/projects/next/archive-3/pages/dynamic/no-chunk-e2d9573b8d7df68a6cde/input.js",
			"swc minifier: fixture/projects/next/archive-3/pages/dynamic/no-ssr-9ced90e71a0d75a11cdd/input.js",
			"swc minifier: fixture/projects/next/archive-3/pages/dynamic/no-ssr-custom-loading-7f61b2e27708ca1854e0/input.js",
			"swc minifier: fixture/projects/next/archive-3/pages/dynamic/ssr-994266264fb6ff57d32c/input.js",
			"swc minifier: fixture/projects/next/archive-3/pages/dynamic/ssr-true-6d4aa8fc503b9d073aef/input.js",
			"swc minifier: fixture/projects/react/.6/input.js",
			"swc minifier: fixture/projects/react/14/input.js",
			"swc minifier: fixture/projects/wmr/archive-1/chunks/.compat.2f7d9500/input.js",
			"swc minifier: fixture/projects/wmr/archive-1/chunks/hoofd.module.6c5395cb/input.js",
			"swc minifier: fixture/reduced/2/input.js",
			"swc minifier: full/vercel/ms/1/input.js",
			"swc minifier: pass-1/seq/1/input.js",
			"swc minifier: projects/files/backbone-1.1.0.js",
			"swc minifier: projects/files/react-17.0.1.js",
			"swc minifier: projects/files/react-dom-17.0.2.js"
		]
	],
	[
		'swc\'s output is wrong: it reads `obj["flag"]` as its first value after increments, printing 1 where the input prints 3',
		["swc minifier: fixture/issues/12313/input.js"]
	],
	[
		'swc\'s output is wrong: it moves a function above `"use strict"`, which then is no directive, so the factory runs sloppy',
		["swc minifier: fixture/issues/8284/input.js"]
	],
	[
		"swc's `drop_console` also drops `console.error[\"capture\"](…)`, which throws in the input; terser keeps a call it cannot prove is console's",
		["swc minifier: fixture/issues/drop-console-computed/input.js"]
	],
	[
		"swc's output is wrong: it keeps only `getObject()` of `#value in getObject()`, losing the TypeError a non-object throws",
		["swc minifier: fixture/pr/11814_class_effect_guards/input.js"]
	],
	[
		"swc's output is wrong: dropping unused classes loses the TypeError of extending a non-constructor and the order of key effects",
		["swc minifier: fixture/pr/11814_class_effect_order/input.js"]
	],
	[
		"swc drops `1 instanceof 1`, which throws; only the `1 in 1` before it, throwing first, hides that",
		["terser compress: comparing/dont_change_in_or_instanceof_expressions"]
	],
	[
		"swc's output is wrong: it drops the second `console.log`, printing one line where the input prints two",
		["terser compress: numbers/issue_1710"]
	],
	[
		"swc's output differs: it drops the `(0, function () {})` detaching a default, so the function takes the binding's `.name`",
		["terser compress: parameters/destructuring_arguments_3"]
	],
	[
		"swc's output is wrong: it drops the global assignment `i = typeof 1n`, so `i` is never set",
		["terser compress: typeof/typeof_evaluation"]
	],
	[
		"swc drops an `in` or `instanceof` whose right side it cannot see, which throws where that side is no object and runs a proxy's or `Symbol.hasInstance`'s code",
		["terser compress: pure_funcs/relational"]
	],
	[
		'swc drops a function\'s lone `"use strict"`, so reading its `caller` or `arguments` no longer throws',
		["terser compress: functions/drop_lone_use_strict"]
	]
];

/** @type {Record<string, string>} */
const SWC_SMALLER = {};
for (const [reason, sources] of SWC_SMALLER_BY_REASON) {
	for (const source of sources) SWC_SMALLER[source] = reason;
}

module.exports = SWC_SMALLER;
