/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author sheo13666q @sheo13666q
*/

"use strict";

// GENERATED by tooling/generate-html-data.js — do not edit.
// Reflected-attribute tables from webref's extraction of the HTML IDL (see tooling/generate-html-data.js); everything else is the
// generator's SUPPLEMENT, which carries the spec facts no dataset states.

/**
 * §13.1.2.4: the elements a `<p>` end tag may be omitted in front of.
 * @type {Set<string>}
 */
const P_FOLLOWED_BY = new Set([
	"address",
	"article",
	"aside",
	"blockquote",
	"details",
	"div",
	"dl",
	"fieldset",
	"figcaption",
	"figure",
	"footer",
	"form",
	"h1",
	"h2",
	"h3",
	"h4",
	"h5",
	"h6",
	"header",
	"hgroup",
	"hr",
	"main",
	"menu",
	"nav",
	"ol",
	"p",
	"pre",
	"section",
	"table",
	"ul"
]);

/**
 * §13.1.2.4: the element names whose end tag may be omitted when the next
 * sibling is one of the mapped names. `<html>`, `<head>` and `<body>` are
 * deliberately absent — their end tags are omissible too, but non-browser
 * consumers routinely mis-parse a document that is missing them.
 * @type {Map<string, Set<string>>}
 */
const OPTIONAL_END_TAG_FOLLOWERS = new Map([
	["li", new Set(["li"])],
	["dt", new Set(["dt", "dd"])],
	["dd", new Set(["dd", "dt"])],
	["rt", new Set(["rt", "rp"])],
	["rp", new Set(["rt", "rp"])],
	["optgroup", new Set(["optgroup"])],
	["option", new Set(["option", "optgroup"])],
	["thead", new Set(["tbody", "tfoot"])],
	["tbody", new Set(["tbody", "tfoot"])],
	["tfoot", new Set()],
	["tr", new Set(["tr"])],
	["td", new Set(["td", "th"])],
	["th", new Set(["td", "th"])],
	["p", P_FOLLOWED_BY]
]);

/**
 * §13.1.2.4: the elements whose end tag may be omitted unless ASCII whitespace
 * or a comment follows. A different condition from the follower-set rule above:
 * what closes these is the insertion mode, whatever the next element is, so only
 * a node that would move inside them keeps the tag.
 * @type {Set<string>}
 */
const OPTIONAL_END_TAG_UNLESS_TRAILING_NODE = new Set(["caption", "colgroup"]);

/**
 * The subset of `OPTIONAL_END_TAG_FOLLOWERS` that may also drop the end tag with
 * nothing left in the parent. `<dt>` and `<thead>` are absent: the spec gives
 * them no such clause.
 * @type {Set<string>}
 */
const OPTIONAL_END_TAG_AT_END = new Set([
	"li",
	"dd",
	"rt",
	"rp",
	"optgroup",
	"option",
	"tbody",
	"tfoot",
	"tr",
	"td",
	"th",
	"p"
]);

/**
 * §13.1.2.4: a trailing `</p>` stays inside these, whose content model would
 * otherwise absorb what follows.
 * @type {Set<string>}
 */
const P_KEEPS_END_TAG_IN = new Set([
	"a",
	"audio",
	"del",
	"ins",
	"map",
	"noscript",
	"video"
]);

/**
 * §2.4.2 boolean attributes, mapped to the elements each one is boolean *on*
 * (`null` = a global attribute). Elsewhere the same name is an ordinary
 * attribute whose value a script may read.
 * @type {Map<string, Set<string> | null>}
 */
const BOOLEAN_ATTRIBUTES = new Map([
	["allowfullscreen", new Set(["iframe"])],
	["alpha", new Set(["input"])],
	["async", new Set(["script"])],
	["autofocus", null],
	["autoplay", new Set(["audio", "video"])],
	["checked", new Set(["input"])],
	["compact", new Set(["dl", "menu", "ol", "ul"])],
	["controls", new Set(["audio", "img", "video"])],
	["declare", new Set(["object"])],
	["default", new Set(["track"])],
	["defer", new Set(["script"])],
	[
		"disabled",
		new Set([
			"button",
			"fieldset",
			"input",
			"link",
			"optgroup",
			"option",
			"select",
			"textarea"
		])
	],
	["formnovalidate", new Set(["button", "input"])],
	["headingreset", null],
	["inert", null],
	["ismap", new Set(["img"])],
	["itemscope", null],
	["loop", new Set(["audio", "video"])],
	["multiple", new Set(["input", "select"])],
	["muted", new Set(["audio", "video"])],
	["nohref", new Set(["area"])],
	["nomodule", new Set(["script"])],
	["noshade", new Set(["hr"])],
	["novalidate", new Set(["form"])],
	["nowrap", new Set(["td", "th"])],
	["open", new Set(["details", "dialog"])],
	["playsinline", new Set(["video"])],
	["readonly", new Set(["input", "textarea"])],
	["required", new Set(["input", "select", "textarea"])],
	["reversed", new Set(["ol"])],
	["selected", new Set(["option"])],
	["shadowrootclonable", new Set(["template"])],
	["shadowrootdelegatesfocus", new Set(["template"])],
	["shadowrootserializable", new Set(["template"])]
]);

/**
 * The attributes whose value is a srcset (WHATWG "parse a srcset attribute").
 * @type {Set<string>}
 */
const SRCSET_ATTRIBUTES = new Set(["srcset", "imagesrcset"]);

/**
 * The attributes whose value is an ASCII-whitespace-separated token list, mapped
 * to the elements they are one on (`null` = a global attribute), so collapsing
 * the separators keeps the set the DOM reads. The element matters: `for` is a
 * token list on `<output>` but one id on `<label>`, and an id may contain a
 * space; `sizes` is one on `<link>` but a source-size list on `<img>`.
 * @type {Map<string, Set<string> | null>}
 */
const TOKEN_LIST_ATTRIBUTES = new Map([
	["accesskey", null],
	["blocking", new Set(["link", "script", "style"])],
	["class", null],
	["for", new Set(["output"])],
	["headers", new Set(["td", "th"])],
	["itemprop", null],
	["itemref", null],
	["itemtype", null],
	["part", null],
	["ping", new Set(["a", "area"])],
	["rel", new Set(["a", "area", "form", "link"])],
	["sandbox", new Set(["iframe"])],
	["sizes", new Set(["link"])]
]);

/**
 * Attributes parsed as a URL, mapped to the elements they are one on. The URL
 * parser strips leading and trailing C0 controls and spaces, so trimming the
 * ASCII whitespace among them resolves to the same URL.
 * @type {Map<string, Set<string> | null>}
 */
const URL_ATTRIBUTES = new Map([
	["action", new Set(["form"])],
	["cite", new Set(["blockquote", "del", "ins", "q"])],
	["codebase", new Set(["object"])],
	["data", new Set(["object"])],
	["formaction", new Set(["button", "input"])],
	["href", new Set(["a", "area", "base", "link"])],
	["longdesc", new Set(["iframe", "img"])],
	["lowsrc", new Set(["img"])],
	["manifest", new Set(["html"])],
	["poster", new Set(["video"])],
	[
		"src",
		new Set([
			"audio",
			"embed",
			"iframe",
			"img",
			"input",
			"script",
			"source",
			"track",
			"video"
		])
	]
]);

/**
 * Attributes parsed with the integer rules, mapped to the elements they are one
 * on (`null` = a global attribute). Those rules skip leading whitespace and
 * stop at the first non-digit, so trimming and dropping leading zeros parse the
 * same. `width` / `height` are absent on `<td>` and `<table>`, where the
 * legacy dimension grammar also admits a percentage.
 * @type {Map<string, Set<string> | null>}
 */
const INTEGER_ATTRIBUTES = new Map([
	["cols", new Set(["textarea"])],
	["colspan", new Set(["td", "th"])],
	["headingoffset", null],
	[
		"height",
		new Set([
			"canvas",
			"embed",
			"iframe",
			"img",
			"input",
			"object",
			"source",
			"video"
		])
	],
	["hspace", new Set(["img", "object"])],
	["maxlength", new Set(["input", "textarea"])],
	["minlength", new Set(["input", "textarea"])],
	["rows", new Set(["textarea"])],
	["rowspan", new Set(["td", "th"])],
	["size", new Set(["input", "select"])],
	["span", new Set(["col", "colgroup"])],
	["start", new Set(["ol"])],
	["tabindex", null],
	["value", new Set(["li"])],
	["vspace", new Set(["img", "object"])],
	[
		"width",
		new Set([
			"canvas",
			"embed",
			"iframe",
			"img",
			"input",
			"object",
			"pre",
			"source",
			"video"
		])
	]
]);

/**
 * The subset of `INTEGER_ATTRIBUTES` parsed with the "rules for parsing
 * integers" rather than the non-negative ones — only those accept a `+` or
 * `-`, so elsewhere a signed value does not parse at all and has to stand.
 * @type {Set<string>}
 */
const SIGNED_INTEGER_ATTRIBUTES = new Set(["start", "tabindex", "value"]);

/**
 * Attributes whose value is a comma-separated list, so the whitespace around
 * each comma and around the ends carries nothing. Whitespace *inside* an item is
 * never dropped: it belongs to the token `accept` keeps, separates numbers in
 * `coords`, and carries the media condition in `sizes`.
 * @type {Set<string>}
 */
const COMMA_LIST_ATTRIBUTES = new Set(["accept", "coords", "sizes"]);

module.exports.BOOLEAN_ATTRIBUTES = BOOLEAN_ATTRIBUTES;
module.exports.COMMA_LIST_ATTRIBUTES = COMMA_LIST_ATTRIBUTES;
module.exports.INTEGER_ATTRIBUTES = INTEGER_ATTRIBUTES;
module.exports.OPTIONAL_END_TAG_AT_END = OPTIONAL_END_TAG_AT_END;
module.exports.OPTIONAL_END_TAG_FOLLOWERS = OPTIONAL_END_TAG_FOLLOWERS;
module.exports.OPTIONAL_END_TAG_UNLESS_TRAILING_NODE =
	OPTIONAL_END_TAG_UNLESS_TRAILING_NODE;
module.exports.P_FOLLOWED_BY = P_FOLLOWED_BY;
module.exports.P_KEEPS_END_TAG_IN = P_KEEPS_END_TAG_IN;
module.exports.SIGNED_INTEGER_ATTRIBUTES = SIGNED_INTEGER_ATTRIBUTES;
module.exports.SRCSET_ATTRIBUTES = SRCSET_ATTRIBUTES;
module.exports.TOKEN_LIST_ATTRIBUTES = TOKEN_LIST_ATTRIBUTES;
module.exports.URL_ATTRIBUTES = URL_ATTRIBUTES;
