name: Update examples

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  examples:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: yarn

      - run: yarn --frozen-lockfile

      - run: yarn link --frozen-lockfile || true

      - run: yarn link webpack --frozen-lockfile

      - run: yarn build:examples

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          commit-message: |
            docs: update examples
          title: |
            docs: update examples
          body: |
            Update examples.

            This PR was autogenerated.
          branch: update-examples
