name: Publish to pkg.pr.new

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["!**"]

permissions:
  issues: write
  pull-requests: write

jobs:
  publish:
    if: |
      github.repository == 'webpack/webpack' &&
      (github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name == github.repository)
    name: Publish to pkg.pr.new
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.publish.outputs.sha }}
      urls: ${{ steps.publish.outputs.urls }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: npx pkg-pr-new publish --compact --json output.json --comment=off
      - name: Add metadata to output
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { run } = await import('${{ github.workspace }}/.github/scripts/publish-to-pkg-pr-new.mjs');
            await run({ github, context });
